import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("pag-ibig-multi-purpose-loan-calculator", {
  description: "Estimate your Pag-IBIG Multi-Purpose Loan (MPL) monthly amortization. The MPL is available for Pag-IBIG members for personal, educational, livelihood, and emergency needs. This calculator helps you plan your monthly budget by showing the fixed amortization amount based on your loan principal, interest rate, and repayment term. The Pag-IBIG MPL is one of the most accessible government loan programs in the Philippines, requiring only 24 monthly Pag-IBIG contributions to qualify. Unlike private bank loans that require extensive credit checks and income documentation, the MPL uses your accumulated Pag-IBIG savings as the primary basis for loan amount eligibility. This makes it especially valuable for employees who may not qualify for bank loans due to limited credit history or lower income levels. The loan is repaid through automatic payroll deduction for employed members, ensuring disciplined repayment. Understanding the amortization schedule helps you evaluate whether the MPL is the right choice compared to other borrowing options.",
  formulaExplanation: "The standard diminishing balance amortization formula is used: M = P x [r(1+r)^n] / [(1+r)^n - 1], where P is the principal, r is the monthly interest rate (annual rate divided by 12), and n is the number of monthly payments. Pag-IBIG MPL uses a 10.5% annual interest rate for members with 24+ monthly contributions. The maximum repayable term is 24 months, and the maximum loan amount is 80% of your total Pag-IBIG savings (TAV or Total Accumulated Value). Monthly amortizations are deducted directly from the borrower's salary through payroll deduction. For members who have previously taken an MPL, a new loan can only be availed after completing at least 50% of the existing loan term. The interest rate may differ for members with fewer contributions or those under special programs. Pag-IBIG periodically adjusts loan terms and amounts based on fund performance and member needs.",
  exampleCalculation: "Example 1: ₱80,000 at 10.5% for 24 months — Monthly rate = 0.875%. Monthly payment = ₱80,000 x [0.00875(1.00875)^24] / [(1.00875)^24 - 1] = ₱3,707. Total repayment = ₱88,968. Total interest = ₱8,968. Example 2: ₱50,000 at 10.5% for 24 months — Monthly = ₱2,317. Total interest = ₱5,608. Example 3: ₱30,000 at 10.5% for 12 months — Monthly = ₱2,641. Total interest = ₱1,692. Shorter term saves significant interest. Example 4: Maximum loan of ₱150,000 at 10.5% for 24 months — Monthly = ₱6,951. Total interest = ₱16,824.",
  philippinesContext: "The Pag-IBIG Multi-Purpose Loan is one of the most popular government loan programs in the Philippines. To qualify, members must have at least 24 monthly contributions with the latest contribution not more than 6 months old. The loanable amount is up to 80% of the member's Total Accumulated Value (TAV), subject to a maximum that Pag-IBIG periodically adjusts. The interest rate is 10.5% per annum for regular members. Pag-IBIG calamity loan — a special MPL variant — is available to members in areas declared under state of calamity, with a lower 5.95% interest rate. MPL proceeds can be used for any personal purpose: medical expenses, education, business capital, home repairs, or debt consolidation. The application process requires: completed MPL application form, 1 valid government ID, latest payslip or income proof, and Pag-IBIG loyalty card or MID number. Processing takes 5-10 working days for complete applications. Employers are required by law to remit payroll deductions to Pag-IBIG and cannot refuse to implement salary deductions for MPL repayment. Members can check their TAV and loan status through the Virtual Pag-IBIG portal.",
  faqs: [
    { question: "What is the Pag-IBIG MPL interest rate?", answer: "The standard MPL interest rate is 10.5% per annum for members with 24+ monthly contributions. This is lower than most private bank personal loan rates (12-30%). The Pag-IBIG calamity loan variant offers an even lower 5.95% rate for members in calamity-declared areas. The rate has remained relatively stable over the years." },
    { question: "How much can I borrow from Pag-IBIG MPL?", answer: "You can borrow up to 80% of your Total Accumulated Value (TAV). If your TAV is ₱100,000, the maximum loan is ₱80,000. Check your TAV through the Virtual Pag-IBIG portal or at any Pag-IBIG branch. The actual maximum amount may be subject to periodic adjustments by the Pag-IBIG board." },
    { question: "Who qualifies for Pag-IBIG Multi-Purpose Loan?", answer: "Members with at least 24 monthly Pag-IBIG contributions and the latest contribution not more than 6 months old. You must not have any existing MPL with Pag-IBIG, or your existing MPL must be at least 50% paid. No outstanding MPL in arrears. Both employed and self-employed members can apply." },
    { question: "How long is the Pag-IBIG MPL repayment term?", answer: "The maximum repayment term is 24 months. You can choose a shorter term (6, 12, or 18 months) for lower total interest. Monthly amortizations are deducted from your salary through payroll deduction. Shorter terms mean higher monthly payments but significantly lower total interest cost." },
    { question: "How do I apply for Pag-IBIG MPL?", answer: "Apply at any Pag-IBIG branch with: completed MPL application form, 1 valid government ID with photo, latest payslip or proof of income, and Pag-IBIG MID number or loyalty card. You can also apply online through the Virtual Pag-IBIG portal. Processing takes 5-10 working days for complete applications." },
    { question: "Can I use MPL for any purpose?", answer: "Yes. Unlike housing loans with specific use requirements, the MPL can be used for any personal purpose: medical expenses, children's tuition, business capital, debt consolidation, home repairs, or travel. No documentation of loan use is required. This flexibility makes MPL one of the most versatile government loan products." },
    { question: "What happens if I miss MPL payments?", answer: "Missed payments incur a 1/10 of 1% daily penalty on the unpaid amount. Continuous non-payment can lead to the remaining balance being deducted from your Pag-IBIG savings upon membership withdrawal. Employers are required to remit salary deductions — non-remittance is the employer's violation, not the employee's." },
    { question: "Can OFWs apply for Pag-IBIG MPL?", answer: "Yes. OFW Pag-IBIG members who meet the 24-contribution requirement can apply for MPL at Pag-IBIG overseas offices or through an authorized representative in the Philippines. Proceeds can be deposited to a Philippine bank account. The contribution requirement applies to total lifetime contributions, not necessarily consecutive months." },
    { question: "How is Pag-IBIG MPL different from Pag-IBIG housing loan?", answer: "MPL is for general purposes with a 24-month maximum term at 10.5% interest. Housing loan is specifically for home purchase, construction, or renovation with terms up to 30 years at 3-5.375% interest. Housing loan amounts are much larger (up to ₱6 million). MPL has simpler requirements and faster processing." },
    { question: "Can I take a new MPL while paying an existing one?", answer: "Not simultaneously. You must complete at least 50% of your existing MPL term before applying for a new one. Alternatively, you can fully pay the existing MPL first. Some members pay off remaining balance using other funds to free up their MPL eligibility for a new, possibly larger loan." },
    { question: "What is Pag-IBIG calamity loan?", answer: "The calamity loan is a special MPL variant for members in areas under a state of calamity. It offers a reduced 5.95% interest rate (vs regular 10.5%) and faster processing. Maximum amount is 80% of TAV or the standard MPL ceiling, whichever is lower. Members can avail even if they have an existing regular MPL." },
    { question: "How do I check my Pag-IBIG TAV?", answer: "Check your Total Accumulated Value through the Virtual Pag-IBIG portal at pagibigfund.gov.ph, the Pag-IBIG mobile app, or by visiting any Pag-IBIG branch with a valid ID. Your TAV includes both your employee contributions and employer counterpart contributions plus accumulated dividends. Regular monitoring helps you plan when and how much to borrow." },
  ]
});

upgrade("slovin-formula-calculator", {
  description: "Compute your required sample size using Slovin's Formula, one of the most commonly cited sampling methods in Philippine academic research. Whether you are writing a thesis, dissertation, or survey-based capstone project, determining the correct sample size is a critical step in your methodology chapter. Slovin's formula provides a straightforward approach that requires only two inputs: the total population size and your desired margin of error. This simplicity is both its strength and its limitation — while it makes sample size determination accessible to students without advanced statistics training, it assumes a 50% response distribution and does not account for population variability. Despite these limitations, Slovin's formula remains the standard reference in Philippine undergraduate and graduate research because most thesis panels accept it as a valid sampling method. This calculator instantly computes the required sample size and helps you understand how different margin of error levels affect the number of respondents needed for your study.",
  formulaExplanation: "Slovin's formula is: n = N / (1 + Ne^2), where n is the required sample size, N is the total population, and e is the desired margin of error (expressed as a decimal). The formula is derived from a simplified version of the Cochran formula with a 50% response distribution (p = 0.5) and produces a conservative sample size estimate. For a 5% margin of error (e = 0.05), a population of 1,000 requires 286 respondents. Increasing to 10,000 population only requires 385 respondents — demonstrating diminishing returns in sample size as population grows. The margin of error represents the acceptable range of deviation from the true population value. A 5% margin means results may differ by up to 5 percentage points from what a complete census would show. Most Philippine thesis committees accept 5% as the standard margin. Using a 3% margin gives higher precision but requires significantly more respondents, increasing research costs and data collection time. Using 10% reduces respondent needs but weakens the statistical reliability of findings.",
  exampleCalculation: "Example 1: Population N = 500, margin e = 5% (0.05). n = 500 / (1 + 500 x 0.0025) = 500 / 2.25 = 222 respondents. Example 2: N = 1,000, e = 5%. n = 1,000 / (1 + 1,000 x 0.0025) = 1,000 / 3.5 = 286 respondents. Example 3: N = 10,000, e = 5%. n = 10,000 / 26 = 385 respondents. Example 4: N = 500, e = 10%. n = 500 / (1 + 500 x 0.01) = 500 / 6 = 83 respondents. Example 5: N = 5,000, e = 3%. n = 5,000 / (1 + 5,000 x 0.0009) = 5,000 / 5.5 = 909 respondents — a 3% margin nearly triples the sample compared to 5%.",
  philippinesContext: "Slovin's formula is deeply embedded in Philippine academic culture, particularly in business administration, education, nursing, and social science research. Nearly every thesis methodology chapter in Philippine universities references either Slovin's or Cochran's formula for sample size determination. CHED-accredited thesis panels generally accept Slovin's formula with a 5% margin of error as the standard approach. The formula is named after Michael Slovin, though its exact origin is debated in academic literature — some scholars attribute it to Yamane (1967). In Philippine graduate schools, thesis advisors typically require students to justify their margin of error selection and discuss the limitations of whatever sampling formula they use. For qualitative research, Slovin's formula does not apply — saturation-based approaches are used instead. Students should also consider: is the population homogeneous or heterogeneous? Are there distinct subgroups requiring stratified sampling? Slovin's formula gives the overall sample size but does not address proportional allocation across strata, which may require additional calculations.",
  faqs: [
    { question: "What is Slovin's formula?", answer: "Slovin's formula (n = N / (1 + Ne^2)) computes the minimum sample size needed for a survey-based study. N is the total population, e is the margin of error, and n is the required sample. It assumes maximum variability (p = 0.5) and is widely used in Philippine academic research for its simplicity and broad acceptance by thesis panels." },
    { question: "What margin of error should I use for my thesis?", answer: "Most Philippine thesis committees accept a 5% margin of error as the standard. A 3% margin provides better precision but requires more respondents. A 10% margin is acceptable for exploratory or pilot studies. Your choice should align with the required precision of your research findings and the feasibility of reaching the computed number of respondents." },
    { question: "Is Slovin's formula the same as Yamane's formula?", answer: "Yes, they are mathematically identical: n = N / (1 + Ne^2). Some academics attribute the formula to Taro Yamane (1967), while others reference Slovin. In Philippine universities, it is most commonly called Slovin's formula. Both names are accepted by thesis panels and produce the same results." },
    { question: "When should I NOT use Slovin's formula?", answer: "Avoid Slovin's when: your population is very small (under 100 — use complete enumeration instead), you need precise estimates for subgroups (use stratified sampling with Cochran's formula), your study is qualitative (use saturation), or the population variability is known (use Cochran's formula with specific p values for tighter estimates)." },
    { question: "How is Slovin's different from Cochran's formula?", answer: "Cochran's formula (n = Z^2pq/e^2) allows you to specify the confidence level and expected response distribution. Slovin's is a simplified version that assumes 95% confidence and 50% distribution. Cochran's gives more precise results when you have prior knowledge about the population. For most Philippine undergraduate theses, either formula is acceptable." },
    { question: "Why does sample size not increase proportionally with population?", answer: "Statistical theory shows that precision depends more on absolute sample size than on the sampling fraction. A sample of 385 from a population of 10,000 gives the same 5% margin as 385 from 100,000. This is because variability in responses follows mathematical laws that plateau. This is why national surveys can represent millions with only 1,200-2,400 respondents." },
    { question: "Can I use Slovin's formula for online surveys?", answer: "Yes, but factor in response rates. If Slovin's formula says you need 300 respondents and your expected response rate is 60%, distribute surveys to at least 500 people (300 / 0.60 = 500). Online surveys in the Philippines typically have 30-60% response rates depending on the platform and incentives offered." },
    { question: "What if my population is unknown?", answer: "If the total population is unknown or very large, use Cochran's formula without the finite population correction: n = Z^2pq/e^2. At 95% confidence and 5% margin: n = (1.96)^2(0.5)(0.5) / (0.05)^2 = 384.16, rounded to 385. This works regardless of population size when N is large." },
    { question: "How do I cite Slovin's formula in my thesis?", answer: "Cite: Slovin, M.J. (1960). Sampling. New York: Simon and Schuster. Or reference Yamane: Yamane, T. (1967). Statistics: An Introductory Analysis (2nd ed.). New York: Harper and Row. Philippine thesis panels accept either citation. Include the formula, your margin of error justification, and the computed sample size in your methodology chapter." },
    { question: "Is Slovin's formula accepted by CHED?", answer: "CHED does not mandate a specific sampling formula, but Slovin's formula is widely accepted across CHED-accredited institutions in the Philippines. It is considered appropriate for descriptive and correlational studies with known finite populations. For experimental designs or complex sampling requirements, thesis panels may prefer Cochran's or power analysis methods." },
    { question: "What sample size do I need for 1000 population at 5% error?", answer: "Using Slovin's formula: n = 1,000 / (1 + 1,000 x 0.0025) = 1,000 / 3.5 = 285.7, rounded to 286 respondents. This means surveying about 28.6% of your population. For the same population at 3% error: 526 respondents (52.6%). At 10% error: 91 respondents (9.1%)." },
    { question: "Should I round up or down when computing sample size?", answer: "Always round UP. If the formula gives 285.7, use 286 respondents. Rounding down gives a sample below the minimum required for your desired precision. In practice, aim for 5-10% above the computed number to account for incomplete responses, invalid surveys, and data cleaning exclusions." },
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 4 complete');
