import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("cronbachs-alpha-calculator", {
  description: "Calculate Cronbach's Alpha (α) to determine the internal consistency and reliability of your survey instruments, questionnaires, or psychometric tests. In academic research, a high Cronbach's Alpha indicates that a set of survey items (like a Likert scale) are closely related and are reliably measuring the same underlying construct. This calculator is designed for students, market researchers, and data analysts who need a quick estimation tool to validate their research instruments before distributing them to a larger sample size. Whether you are conducting a thesis study in a university, performing consumer behavior research, or evaluating employee satisfaction in a corporate setting, ensuring the reliability of your data collection tool is paramount. A low alpha suggests that your questions might be confusing, measuring different things, or simply too few in number. This tool helps you diagnose these issues early, saving you from collecting invalid data. It provides an immediate numerical metric that is universally recognized in academic and professional research communities.",
  formulaExplanation: "Cronbach's Alpha is calculated using the formula: α = [k / (k - 1)] * [1 - (ΣVi / Vt)], where 'k' is the total number of items (questions) in your scale, 'ΣVi' is the sum of the variances of each individual item, and 'Vt' is the variance of the total scores across all respondents. The result is a number between 0 and 1. A value of 0 indicates no internal consistency (the items are completely unrelated), while a value of 1 indicates perfect internal consistency. The multiplier [k / (k - 1)] adjusts the value based on the number of items; scales with more items generally yield higher alpha values, provided the items are inter-correlated. It is important to note that Cronbach's Alpha assumes that all items measure a single unidimensional construct. If your questionnaire has multiple sections measuring different concepts (e.g., one section on 'customer service' and another on 'product quality'), you must calculate a separate alpha for each section rather than one overall score.",
  exampleCalculation: "Example: You have a 5-item survey (k = 5) given to a pilot group. You calculate the variance for each of the 5 questions, which are: 1.2, 1.4, 1.1, 1.3, and 1.5. The sum of item variances (ΣVi) = 1.2 + 1.4 + 1.1 + 1.3 + 1.5 = 6.5. You then calculate the variance of the total survey scores across all respondents, let's say Vt = 18.0. Plugging this into the formula: α = [5 / (5 - 1)] * [1 - (6.5 / 18.0)] = (5 / 4) * [1 - 0.361] = 1.25 * 0.639 = 0.798. An alpha of 0.798 is generally considered 'Acceptable' to 'Good' for most research purposes. If the total variance (Vt) was only 8.0, the calculation would be: 1.25 * [1 - (6.5 / 8.0)] = 1.25 * [1 - 0.8125] = 1.25 * 0.1875 = 0.234, indicating unacceptable reliability, meaning the survey items need to be revised.",
  philippinesContext: "In the Philippine academic landscape, passing a thesis or dissertation defense is heavily contingent on the rigorous validation of research instruments. Institutions like the University of the Philippines (UP), Ateneo de Manila, De La Salle University (DLSU), and the University of Santo Tomas (UST) strictly require students to report Cronbach's Alpha during their methodology presentation. A pilot testing phase, usually involving 20 to 30 respondents, is a mandatory step in the research timeline. If the computed alpha falls below the acceptable threshold (typically 0.70), the research adviser or panel will reject the questionnaire, forcing the student to revise or drop unreliable items before the actual data gathering begins. This calculator is a critical companion during the thesis writing season, allowing Filipino students to quickly verify their statistical outputs from software like SPSS or JASP. For market research agencies operating in Metro Manila, maintaining high internal consistency in consumer surveys is essential to justify strategic business recommendations to corporate clients.",
  faqs: [
    { question: "What is a 'good' Cronbach's Alpha score?", answer: "Generally, an alpha of 0.70 or higher is considered 'Acceptable' for most academic and professional research. A score between 0.80 and 0.90 is 'Good', while a score above 0.90 is 'Excellent'. Scores below 0.60 are typically considered 'Unacceptable' and indicate that the survey items need revision." },
    { question: "What does it mean if my Cronbach's Alpha is too high (e.g., 0.95)?", answer: "While a high score seems desirable, an alpha above 0.95 may indicate item redundancy. This means you are essentially asking the exact same question in slightly different ways, and you could likely shorten your survey without losing information. It wastes respondents' time." },
    { question: "How can I increase my Cronbach's Alpha?", answer: "You can increase your alpha by: 1) Adding more relevant items to the scale. 2) Removing items that do not correlate well with the rest (identifiable via an 'alpha if item deleted' analysis). 3) Rewording confusing questions to ensure all respondents interpret them similarly." },
    { question: "Can Cronbach's Alpha be negative?", answer: "Yes, though it is rare. A negative alpha usually occurs when the items are negatively correlated. This often happens if you have 'reverse-scored' items in your survey (e.g., asking a negative question) and forgot to reverse their numerical values in your dataset before calculating." },
    { question: "Should I calculate one alpha for my entire survey?", answer: "No. You should calculate a separate Cronbach's Alpha for each specific construct or sub-scale in your survey. For example, if your survey measures 'Motivation' (5 items) and 'Stress' (5 items), calculate one alpha for Motivation and a different one for Stress." },
    { question: "Is a pilot test necessary to calculate Cronbach's Alpha?", answer: "Yes, a pilot test is standard practice. You distribute the draft survey to a small sample (typically 20-30 people) who resemble your target population. You calculate the alpha from this pilot data to ensure reliability before deploying the survey to hundreds of people." },
    { question: "Does Cronbach's Alpha measure validity?", answer: "No. Reliability (Alpha) means your survey measures something consistently. Validity means it measures what it is actually supposed to measure. A survey can be highly reliable (consistent) but totally invalid (missing the point). Both are required for good research." },
    { question: "Can I use Cronbach's Alpha for yes/no questions?", answer: "While technically possible using the KR-20 (Kuder-Richardson 20) formula which is mathematically equivalent to alpha for binary data, Cronbach's Alpha is most appropriate for continuous data or Likert scale items (e.g., 1 to 5, strongly disagree to strongly agree)." },
    { question: "What software normally calculates this?", answer: "Most researchers use statistical software like IBM SPSS, JASP, Jamovi, R, or SAS to calculate Cronbach's Alpha, as these programs easily process large datasets and provide item-total statistics. This online calculator is useful for quick, manual estimations during the planning phase." },
    { question: "Why is Cronbach's Alpha required in Philippine universities?", answer: "Philippine universities adhere to international research standards. To ensure that thesis conclusions are scientifically sound, the data collection instruments must be proven reliable. A certified high Cronbach's Alpha protects the research from being dismissed by the defense panel as anecdotal or flawed." },
    { question: "What is an 'alpha if item deleted' analysis?", answer: "This is a diagnostic metric provided by statistical software. It shows what the overall Cronbach's Alpha would be if a specific question were removed from the survey. If removing a question significantly increases the overall alpha, that question is flawed and should be deleted." },
    { question: "Does sample size affect Cronbach's Alpha?", answer: "While the alpha formula itself is based on item variances and not sample size, a larger sample size provides more stable and accurate estimates of those variances. A pilot test sample of fewer than 20 respondents may yield an artificially high or low alpha that won't hold true in the main study." }
  ]
});

upgrade("dlsu-gpa-calculator", {
  description: "Calculate your Grade Point Average (GPA) precisely according to the De La Salle University (DLSU) 4.0 grading system. DLSU utilizes a unique fixed-scale grading system where grades are awarded in increments of 0.5 (e.g., 4.0, 3.5, 3.0, down to 1.0, with 0.0 representing a failing grade). This calculator is an essential tool for all DLSU students—from freshmen aiming for the Dean's Lister status to graduating seniors calculating their Latin Honors eligibility. By inputting your subject units and the corresponding DLSU grade point, this tool computes your Term Grade Point Average (TGPA) or your Cumulative Grade Point Average (CGPA). Maintaining a high GPA at DLSU is critical not only for academic recognition but also for retaining scholarships, shifting to high-quota degree programs, and securing competitive internships. Unlike other Philippine universities that use a 1.0 (highest) to 5.0 (failing) system, DLSU's inverted 4.0 system requires a specific calculation method. This tool removes the mathematical guesswork, helping Lasallians strategize their academic load and target specific grades required for graduation milestones.",
  formulaExplanation: "The DLSU GPA is calculated as a weighted average. The formula is: GPA = Sum of (Grade in a Subject * Number of Units for that Subject) / Total Number of Units taken. The grading scale is strictly discrete: 4.0 (Excellent, 97-100%), 3.5 (Superior, 93-96%), 3.0 (Very Good, 89-92%), 2.5 (Good, 85-88%), 2.0 (Satisfactory, 80-84%), 1.5 (Fair, 75-79%), 1.0 (Pass, 70-74%), and 0.0 (Fail, below 70%). Note that a 0.0 heavily pulls down the GPA because its units are still included in the total divisor, but it contributes zero to the numerator. To calculate Cumulative GPA (CGPA), you must include all academic subjects taken across all terms. Non-academic subjects—such as Physical Education (PE/FTDANCE) or National Service Training Program (NSTP/CWTS)—are typically excluded from the official GPA computation. It is crucial to multiply each grade by its exact unit weight (e.g., a 3-unit major subject affects the GPA three times more than a 1-unit lab class).",
  exampleCalculation: "Example 1 (Dean's Lister Computation): A student takes 15 units in a term. Accounting (3 units) = 4.0. Finance (3 units) = 3.5. Marketing (3 units) = 3.0. Economics (3 units) = 3.5. Theology (3 units) = 4.0. Step 1: Multiply grades by units. Acc (12), Fin (10.5), Mkt (9), Eco (10.5), Theo (12). Step 2: Sum the results = 54. Step 3: Divide by total units (15). GPA = 54 / 15 = 3.60. This qualifies the student for First Honors Dean's List (cutoff is usually 3.400). Example 2 (Impact of a Failure): A student takes 12 units. Subject A (3 units) = 3.0. Subject B (3 units) = 2.5. Subject C (3 units) = 2.0. Subject D (3 units) = 0.0 (Failed). Weighted sum = (3*3) + (3*2.5) + (3*2) + (3*0) = 9 + 7.5 + 6 + 0 = 22.5. Total units = 12. GPA = 22.5 / 12 = 1.875. The 0.0 grade drastically reduced the GPA, pulling it below a 2.0.",
  philippinesContext: "De La Salle University (DLSU) operates on a trimester system, making academic pacing fast and rigorous. The university's 4.0 grading system is more akin to the American GPA standard, standing in contrast to the UP system (where 1.0 is excellent) or the Ateneo system (which uses letter grades translated to Quality Point Index). For Lasallians, the GPA dictates academic survival. First Honors Dean's List typically requires a term GPA of 3.400 with no grade below 2.0 in any academic subject. Second Honors requires a term GPA of 3.000 to 3.399. For Latin Honors upon graduation, DLSU is notoriously strict: Summa Cum Laude requires a CGPA of 3.800, Magna Cum Laude requires 3.600, and Cum Laude requires 3.400. Furthermore, students holding scholarships (like the Star Scholar or Gokongwei grants) must maintain specific CGPAs to avoid losing their funding. The fast-paced trimester means students have only 14 weeks to secure their target grades, making mid-term GPA forecasting using this calculator an essential survival tactic for DLSU undergraduates.",
  faqs: [
    { question: "What is the DLSU grading scale?", answer: "DLSU uses a 4.0 scale: 4.0 (Excellent), 3.5 (Superior), 3.0 (Very Good), 2.5 (Good), 2.0 (Satisfactory), 1.5 (Fair), 1.0 (Pass), and 0.0 (Fail). The percentage equivalents may vary slightly by college or professor, but the discrete point values are fixed across the university." },
    { question: "Are PE and NSTP included in the DLSU GPA?", answer: "No. Non-academic subjects such as Physical Education (PE/FTDANCE/FTWEIGH) and the National Service Training Program (NSTP/CWTS) are given grades but are excluded from the official computation of your Term GPA and Cumulative GPA." },
    { question: "What is the GPA required for Dean's Lister at DLSU?", answer: "To qualify for First Honors, you need a Term GPA of at least 3.400. For Second Honors, you need a Term GPA between 3.000 and 3.399. Crucially, you must have taken at least 12 academic units, have no grade lower than 2.0 in any subject, and have no failures (0.0) or withdrawn (W) marks." },
    { question: "What is the requirement for Latin Honors at DLSU?", answer: "Latin Honors require a high Cumulative GPA (CGPA) upon graduation: Summa Cum Laude (3.800 to 4.000), Magna Cum Laude (3.600 to 3.799), and Cum Laude (3.400 to 3.599). You must also have no failing grade (0.0) in any academic or non-academic course throughout your entire stay." },
    { question: "How does a 0.0 (Fail) affect my GPA?", answer: "A 0.0 grade severely pulls down your GPA. Even though the grade is zero, the units for that failed subject are still added to your total divisor. This dramatically lowers the average of your other passing grades." },
    { question: "What happens if I fail a subject and retake it?", answer: "If you retake a failed subject and pass it, the new passing grade does NOT replace the old 0.0 in your Cumulative GPA calculation. Both the original 0.0 and the new passing grade (and their respective units) are permanently included in your CGPA." },
    { question: "What does an 'Incomplete' (INC) grade mean?", answer: "An 'INC' means you have lacking requirements. It does not immediately affect your GPA. You are usually given one term to complete the requirements. If you fail to do so by the deadline, the INC automatically converts to a 0.0, which will then drag down your GPA." },
    { question: "Is a 2.5 a bad grade at DLSU?", answer: "A 2.5 is considered 'Good' and is a solid passing grade. However, if you are aiming for Dean's List or Latin Honors, accumulating too many 2.5s will make it mathematically difficult to reach the 3.400 threshold, requiring you to offset them with multiple 4.0s." },
    { question: "Does DLSU round up GPA computations?", answer: "No. DLSU is extremely strict and does not round up GPAs for honors. If your Cumulative GPA is 3.399, you will not receive Cum Laude honors, as the strict cutoff is 3.400. Every single decimal point matters." },
    { question: "What is the minimum GPA to stay in DLSU?", answer: "Students must meet a minimum CGPA to avoid academic probation or dismissal, which varies by college and year level (often starting around 1.0 or 1.5). Accumulating a certain number of failed units (usually around 15 to 18 units) can lead to forced dismissal from the university." },
    { question: "How do shifting and GPA relate?", answer: "If you want to shift to a different degree program, the accepting college will evaluate your CGPA. High-quota courses (like Accountancy or certain Engineering programs) require very high CGPAs for transferees, and having a failure on record can disqualify you." },
    { question: "Can I use this calculator for other universities?", answer: "This specific calculator is tailored for DLSU's discrete 4.0 scale (4.0, 3.5, 3.0...). While the weighted average math is universal, it is not ideal for universities that use the UP 1.0-5.0 scale or the Ateneo QPI scale. Use our GWA calculator for those systems." }
  ]
});

upgrade("gaussian-elimination-calculator", {
  description: "Solve complex systems of linear equations instantly using the Gaussian Elimination Calculator. Gaussian Elimination is a fundamental algorithm in linear algebra used to find the exact solutions for multiple variables simultaneously. By systematically applying elementary row operations, this tool transforms a given matrix of equations into row echelon form, allowing for straightforward back-substitution. This calculator is an indispensable academic companion for engineering, computer science, and mathematics students who routinely encounter large matrices in subjects like structural analysis, electrical circuit design, and algorithm optimization. Manually solving a system of 3 or more variables is highly prone to arithmetic errors—a single misplaced negative sign can ruin an entire page of calculations. This tool automates the process, displaying the final variable values instantly. Whether you are verifying your homework, debugging a programming assignment, or preparing for an exam, this calculator provides mathematical certainty and saves hours of tedious manual computation.",
  formulaExplanation: "Gaussian elimination works by representing a system of linear equations as an augmented matrix. The process involves three elementary row operations: 1) Swapping two rows, 2) Multiplying a row by a non-zero scalar, and 3) Adding a multiple of one row to another row. The goal is to perform these operations sequentially to convert the matrix into 'row echelon form' (an upper triangular matrix), where all entries below the main diagonal are zero. Once this form is achieved, the value of the last variable is directly revealed. You then use 'back-substitution'—plugging this known value into the equation above it—to find the preceding variable, repeating the process until all variables (x, y, z, etc.) are solved. The system may have a unique solution, infinite solutions (if a row becomes all zeros), or no solution (if you get an impossible row like 0 = 1).",
  exampleCalculation: "Example System: Equation 1: 2x + y - z = 8. Equation 2: -3x - y + 2z = -11. Equation 3: -2x + y + 2z = -3. Step 1: Form the augmented matrix. Row 1: [2, 1, -1 | 8]. Row 2: [-3, -1, 2 | -11]. Row 3: [-2, 1, 2 | -3]. Step 2: Use Row 1 to eliminate 'x' from Row 2 and Row 3 (e.g., Row 2 = Row 2 + 1.5 * Row 1). Step 3: Use the new Row 2 to eliminate 'y' from Row 3. Step 4: The matrix is now in upper triangular form. The bottom row reveals the value of 'z'. Step 5: Back-substitute 'z' into the second row to find 'y'. Step 6: Substitute 'y' and 'z' into the first row to find 'x'. The final unique solution for this system is: x = 2, y = 3, z = -1. The calculator performs all these fractional operations in milliseconds.",
  philippinesContext: "In Philippine engineering and technology programs—such as those at Mapúa University, UP Diliman, TIP, and various state universities—Linear Algebra and Advanced Engineering Mathematics are critical 'filter' subjects. Students in Civil Engineering use Gaussian Elimination to solve truss forces and structural equilibria. Electrical Engineering students rely on it for complex nodal and mesh circuit analysis. The Board Exams (PRC licensure exams) frequently feature problems that, at their core, require solving systems of linear equations. While advanced scientific calculators (like the widely used Casio fx-991EX) are allowed in exams and can solve 3x3 or 4x4 systems, students must understand the underlying manual process to pass their university midterms, where professors often require showing the step-by-step row operations. This online calculator serves as an excellent study tool, allowing students to check their manual work and understand where arithmetic mistakes might have occurred during the tedious matrix transformation process.",
  faqs: [
    { question: "What is Gaussian Elimination used for?", answer: "Gaussian Elimination is a method in linear algebra used primarily to solve systems of linear equations. It is also used to find the rank of a matrix, calculate the determinant of a square matrix, and compute the inverse of an invertible matrix." },
    { question: "What is an augmented matrix?", answer: "An augmented matrix is a way of writing a system of linear equations without writing the variables. It consists of the coefficients of the variables on the left side of a vertical line, and the constants (the results of the equations) on the right side." },
    { question: "What is row echelon form?", answer: "Row echelon form is a matrix structure where the leading coefficient (the first non-zero number from the left, also called a pivot) of a non-zero row is always strictly to the right of the leading coefficient of the row above it. All entries below a pivot must be zero." },
    { question: "What happens if a row becomes all zeros (e.g., 0 0 0 | 0)?", answer: "If, during elimination, an entire row (including the constant side) becomes zero, it means that equation was redundant (a linear combination of the others). If there are fewer remaining valid equations than variables, the system has an infinite number of solutions." },
    { question: "What happens if I get a row like (0 0 0 | 5)?", answer: "This translates to the equation 0x + 0y + 0z = 5, which is a mathematical impossibility. This indicates that the system of equations is 'inconsistent' and has no solution. The lines or planes represented by the equations do not intersect at a single point." },
    { question: "Can Gaussian Elimination solve non-linear equations?", answer: "No. Gaussian elimination only works for systems of linear equations (where variables are to the power of 1 and are not multiplied together). For non-linear systems, other numerical methods like the Newton-Raphson method must be used." },
    { question: "What is the difference between Gaussian and Gauss-Jordan elimination?", answer: "Gaussian elimination stops at row echelon form (upper triangular) and uses back-substitution to find the variables. Gauss-Jordan elimination continues the matrix operations to create zeros above the pivots as well (reduced row echelon form), yielding the answers directly without back-substitution." },
    { question: "Can a calculator solve a 4x4 or 5x5 system?", answer: "Yes, our online calculator can handle large matrices easily. While standard scientific calculators allowed in Philippine board exams typically top out at 4x4 systems, computer algorithms can perform Gaussian elimination on matrices with thousands of variables." },
    { question: "Why do professors require manual row operations?", answer: "While computers can solve matrices instantly, professors require manual computation to ensure students understand the logical algorithm and the properties of linear spaces. This foundational knowledge is essential for higher-level courses in numerical methods and computer programming." },
    { question: "Is partial pivoting necessary?", answer: "In computer algorithms, partial pivoting (swapping rows to put the largest absolute value at the pivot position) is crucial. It minimizes rounding errors and prevents the algorithm from crashing due to division by zero if a natural pivot happens to be zero." },
    { question: "What applications use Gaussian Elimination?", answer: "It is widely used in physics and engineering. Examples include finding currents in electrical circuits (Kirchhoff's laws), calculating forces in static bridge trusses, optimizing logistics networks, and rendering 3D graphics in computer science." },
    { question: "How do I check if my answer is correct?", answer: "The simplest way to verify the solution from a Gaussian elimination is to plug the final values of the variables (x, y, z) back into the original equations. If the left side equals the right side for every single equation, your solution is correct." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 10 complete');
