import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

// Helper: replace a calculator's content fields by slug
function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  // Replace description
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  
  // Replace formulaExplanation
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  
  // Replace exampleCalculation
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  
  // Replace philippinesContext
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  
  // Replace faqs array
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  
  console.log(`Upgraded: ${slug}`);
}

// === NIGHT DIFFERENTIAL ===
upgrade("night-differential-calculator", {
  description: "Compute your Night Shift Differential (NSD) pay based on the Philippine Labor Code. Night differential is the additional 10% of your hourly rate for work performed between 10:00 PM and 6:00 AM. Whether you work in a BPO call center, manufacturing plant, hospital, or convenience store, this calculator helps you determine exactly how much extra pay you earn during night shifts. Night differential applies to all employees regardless of rank or position — even managerial staff are entitled to NSD under the Labor Code. The computation is straightforward but often miscalculated, especially when employees work partial night hours or when overtime overlaps with the night differential window. This tool handles the standard NSD computation so you can verify your payslip accuracy. Many Filipino BPO workers rely on night differential as a significant portion of their total compensation, sometimes adding ₱2,000 to ₱5,000 monthly depending on shift schedules and base pay rates.",
  formulaExplanation: "Night shift differential is calculated as 10% of the hourly rate for each hour worked between 10:00 PM and 6:00 AM. First, compute the hourly rate by dividing the daily rate by 8 standard working hours. Then multiply the hourly rate by 10% to get the NSD premium per hour. Finally, multiply the NSD premium by the number of night hours worked. If work falls on a rest day, special holiday, or regular holiday, the NSD premium is computed on the already-adjusted holiday/overtime rate, not the regular rate. For overtime work during night hours, compute the overtime rate first (125% of hourly rate for regular overtime), then apply 10% NSD on top of the overtime rate. This layered computation is why night shift workers on holidays can earn significantly more than their standard daily rate — up to 200% or more of the regular hourly rate when all premiums stack.",
  exampleCalculation: "Example 1: Daily rate ₱600, hourly rate ₱75, NSD per hour ₱7.50. For 8 night hours: NSD = ₱60. Total night pay = ₱660. Example 2: Daily rate ₱800, hourly rate ₱100, works 4 hours during night window: NSD = ₱100 x 10% x 4 = ₱40 additional. Example 3: Rest day night shift — hourly rate ₱75 x 130% (rest day premium) = ₱97.50, NSD = ₱97.50 x 10% = ₱9.75/hour. For 8 hours: ₱78 NSD on top of rest day pay. Example 4: BPO worker earning ₱22,000 monthly (₱846/day), hourly = ₱105.77. Working 22 night shifts monthly: NSD = ₱105.77 x 10% x 8 x 22 = ₱1,861.54/month extra.",
  philippinesContext: "Under Article 86 of the Philippine Labor Code, every employee is entitled to a Night Shift Differential of not less than 10% of the regular wage for each hour of work performed between 10:00 PM and 6:00 AM. The Philippines has one of the largest BPO industries globally, with over 1.3 million Filipino workers on night shifts serving international clients. DOLE enforces NSD compliance through regular labor inspections, and employers who fail to pay face administrative penalties. For workers on compressed workweeks (e.g., 4 days x 10 hours), NSD still applies to hours falling within the 10PM-6AM window. The NSD rate increases during holidays and rest days: regular holiday night work earns the holiday premium plus 10% NSD on top of it. Many employment contracts in BPO and manufacturing include built-in NSD in the salary package, but DOLE requires that NSD be itemized separately on payslips. Workers who believe their NSD is miscalculated can verify using this tool and file complaints with DOLE through the Single Entry Approach (SEnA) process at hotline 1349.",
  faqs: [
    { question: "What time is considered night shift in the Philippines?", answer: "Night shift hours are from 10:00 PM to 6:00 AM as defined by Article 86 of the Philippine Labor Code. Any work performed during this 8-hour window qualifies for night shift differential. If your shift is 6 PM to 2 AM, only the 4 hours from 10 PM to 2 AM qualify for NSD — the 6 PM to 10 PM portion earns regular pay only." },
    { question: "What is the minimum NSD rate in the Philippines?", answer: "The minimum NSD rate is 10% additional pay on top of your regular hourly rate. If your hourly rate is ₱100, you earn ₱10 extra per night hour, making it ₱110/hour between 10 PM and 6 AM. Some companies offer higher than 10% through CBAs or company policy, but 10% is the legal minimum that DOLE enforces." },
    { question: "Does NSD apply during holidays?", answer: "Yes. NSD applies on top of holiday premiums. For a regular holiday: base rate x 200% (holiday rate), then add 10% NSD on that adjusted rate. Example: ₱75/hour regular rate becomes ₱150 on a regular holiday, plus ₱15 NSD = ₱165/hour total. This stacking makes holiday night shifts significantly more valuable for workers." },
    { question: "How is NSD computed for overtime night work?", answer: "First apply the overtime premium (125% for regular overtime), then apply 10% NSD. Example: hourly rate ₱100, overtime rate = ₱125, NSD = ₱125 x 10% = ₱12.50. Total overtime night rate = ₱137.50/hour. The premiums stack multiplicatively, not additively, which is why overtime on holiday nights can yield 3x the regular rate." },
    { question: "Are BPO workers entitled to night differential?", answer: "Yes. All BPO/call center employees working between 10 PM and 6 AM are entitled to NSD regardless of their employment arrangement — regular, probationary, or contractual. Some BPO companies include NSD in a blended salary rate, but DOLE requires it to be separately identifiable. If your payslip does not itemize NSD, ask your HR department for clarification." },
    { question: "Can my employer waive night differential?", answer: "No. NSD is a mandatory benefit under the Labor Code and cannot be waived by agreement between employer and employee. Even if an employee signs a contract agreeing to waive NSD, that clause is void and unenforceable. DOLE considers NSD a non-negotiable labor standard. Employers who do not pay NSD face penalties and back-pay orders." },
    { question: "How much extra do night shift workers earn monthly?", answer: "A worker earning ₱600/day (₱75/hour) working 22 night shifts monthly earns approximately ₱1,320 in NSD (₱7.50 x 8 hours x 22 days). For BPO workers earning ₱25,000/month, NSD adds roughly ₱2,100 monthly. Over a year, NSD can total ₱15,000 to ₱25,000 in additional income depending on base pay and shift frequency." },
    { question: "Is NSD included in 13th month pay computation?", answer: "Generally, no. The standard DOLE formula for 13th month pay uses basic salary only, which excludes night shift differential. However, some companies voluntarily include NSD in their 13th month computation through company policy or CBA provisions. Check your company handbook or ask HR for your specific policy." },
    { question: "What if my employer does not pay night differential?", answer: "File a complaint at the nearest DOLE Field or Regional Office. DOLE will conduct an inspection and issue a compliance order. Employers found in violation must pay back NSD for the affected period plus possible penalties. The complaint process is free through SEnA (Single Entry Approach). Call DOLE hotline 1349 for assistance." },
    { question: "Does NSD apply to compressed workweek schedules?", answer: "Yes. NSD applies to any work performed between 10 PM and 6 AM regardless of the workweek arrangement. If you work a compressed schedule of 4 days x 10 hours with shifts from 8 PM to 6 AM, you earn NSD for the 8 hours between 10 PM and 6 AM. The 2 hours from 8 PM to 10 PM are paid at regular rate." },
    { question: "How do I verify if my NSD computation is correct?", answer: "Check your payslip for the NSD line item. Divide your daily rate by 8 to get the hourly rate. Multiply by 10% to get the NSD premium per hour. Multiply by the number of night hours worked that pay period. Compare this amount with what appears on your payslip. If there is a discrepancy, raise it with HR first, then DOLE if unresolved." },
    { question: "Is NSD taxable income?", answer: "Yes. Night shift differential is considered part of gross compensation and is subject to income tax, SSS, PhilHealth, and Pag-IBIG contributions. It is included in your taxable gross income on BIR Form 2316 (Certificate of Compensation Payment/Tax Withheld). There is no special tax exemption for NSD earnings." },
  ]
});

// === SSS MATERNITY ===
upgrade("sss-maternity-benefit-calculator", {
  description: "Estimate your SSS maternity benefit based on your average monthly salary credit. Under the Expanded Maternity Leave Law (RA 11210), female SSS members can receive 105 days of paid maternity leave for all types of delivery, with solo parents entitled to an additional 15 days. This is one of the most searched benefits in the Philippines as expecting mothers need to plan their finances during the leave period. The SSS maternity benefit is a daily cash allowance computed from your salary credit history, not from your actual salary. Understanding the difference between your actual salary and your SSS salary credit is crucial — many members are surprised when the benefit amount is lower than expected. This calculator helps you estimate the daily allowance and total benefit amount so you can budget accordingly. The benefit covers both normal and cesarean deliveries, miscarriages, and emergency terminations of pregnancy.",
  formulaExplanation: "The SSS maternity benefit equals 100% of the average daily salary credit (ADSC) multiplied by the number of credited days. ADSC is computed by taking the 6 highest monthly salary credits (MSC) within the 12-month period before the semester of delivery, multiplying by 6, and dividing by 180 days. The semester of delivery determines which contribution months are counted. If delivery is in January-June, SSS looks at contributions from July-December of the previous year. If delivery is July-December, they look at January-June of the same year. For members with fewer than 6 months of contributions in the qualifying period, SSS uses the actual number of months contributed. The maximum MSC is ₱30,000, which caps the maximum daily allowance at ₱1,000 (₱30,000 x 6 ÷ 180). This means the maximum total maternity benefit for 105 days is ₱105,000.",
  exampleCalculation: "Example 1: MSC ₱20,000 for 6 months. ADSC = (₱20,000 x 6) ÷ 180 = ₱666.67/day. Normal delivery (105 days): Total = ₱70,000. Example 2: MSC ₱30,000 (maximum). ADSC = ₱1,000/day. For 105 days: ₱105,000. Solo parent gets 120 days: ₱120,000. Example 3: MSC ₱15,000. ADSC = ₱500/day. Miscarriage (105 days): ₱52,500. Example 4: Variable MSC — 3 months at ₱25,000 and 3 months at ₱15,000. Average MSC = ₱20,000. ADSC = ₱666.67. For 105 days: ₱70,000.",
  philippinesContext: "Under RA 11210 (Expanded Maternity Leave Law), female SSS members are entitled to 105 days of paid maternity leave for live births (both normal and cesarean), with an option to extend 30 days unpaid. Solo parents receive an additional 15 days paid, totaling 120 days. For miscarriage and emergency termination of pregnancy, the benefit is 60 days. The law requires at least 3 monthly SSS contributions in the 12-month period before the semester of contingency. SSS processes maternity benefit claims through the employer for employed members and directly for voluntary/self-employed members. Processing typically takes 15-30 working days after submission of complete documents. Required documents include MAT-1 (Maternity Notification), proof of delivery or miscarriage, and SSS ID. The employer advances the benefit to the employee and is reimbursed by SSS. For OFW members, claims can be filed at the nearest SSS branch upon return or through an authorized representative. The maternity benefit is non-taxable and is not subject to SSS, PhilHealth, or Pag-IBIG deductions.",
  faqs: [
    { question: "How many days of maternity leave do SSS members get?", answer: "105 days for all delivery types (normal, cesarean, miscarriage) under RA 11210. Solo parents get an additional 15 days (120 total). Members can extend by 30 days unpaid. An additional 7 days can be allocated to the child's father or an alternate caregiver. Previous distinctions between normal (60 days) and cesarean (78 days) delivery no longer apply." },
    { question: "Who qualifies for SSS maternity benefit?", answer: "Female SSS members who have paid at least 3 monthly contributions in the 12-month period before the semester of delivery or miscarriage. This includes employed, self-employed, voluntary, and OFW members. The member must have notified SSS of her pregnancy through the MAT-1 form. Non-working spouses of male SSS members are not covered." },
    { question: "What is the maximum SSS maternity benefit?", answer: "The maximum daily allowance is ₱1,000 (based on the maximum MSC of ₱30,000). For 105 days: maximum total is ₱105,000. For solo parents (120 days): maximum is ₱120,000. These amounts represent the SSS benefit only — employers may provide additional maternity benefits through company policy or CBA provisions." },
    { question: "How is the average daily salary credit computed?", answer: "SSS takes the 6 highest monthly salary credits in the 12-month period before the semester of delivery. Multiply the sum by 1 (since it is 6 months of MSC), then divide by 180 days. Formula: ADSC = (Sum of 6 highest MSC) ÷ 180. If MSC is ₱20,000 for all 6 months: ADSC = ₱120,000 ÷ 180 = ₱666.67 per day." },
    { question: "When should I file the MAT-1 notification?", answer: "File the SSS Maternity Notification (MAT-1) form as early as possible, ideally within the first trimester. For employed members, submit through your employer. For voluntary/self-employed, file directly at the nearest SSS branch. Late notification does not disqualify you from benefits, but it may delay processing. Include your expected delivery date and attending physician details." },
    { question: "Can I use maternity benefit for miscarriage?", answer: "Yes. RA 11210 provides 105 days of maternity leave for miscarriage and emergency termination of pregnancy (previously only 60 days). Submit medical documentation including the attending physician's certification. The benefit computation follows the same formula as live births — ADSC multiplied by the number of credited days." },
    { question: "How long does SSS maternity benefit processing take?", answer: "Processing takes 15-30 working days after submission of complete documents. Employers typically advance the benefit and seek reimbursement from SSS. For self-employed and voluntary members filing directly, disbursement goes to the member's registered bank account, UMID-ATM, or SSS-accredited disbursement channels. Incomplete documents are the most common cause of delays." },
    { question: "Is the SSS maternity benefit taxable?", answer: "No. The SSS maternity benefit is non-taxable income. It is not subject to income tax, SSS contributions, PhilHealth premiums, or Pag-IBIG contributions during the leave period. The employer should not deduct any taxes from the maternity benefit payment. This tax-exempt status applies to both the SSS benefit and any employer-paid maternity differential." },
    { question: "What documents do I need for SSS maternity claim?", answer: "Required documents include: MAT-1 (Maternity Notification), SSS ID or UMID card, proof of delivery (birth certificate or hospital certification), and for miscarriage cases, a medical certification. Employed members submit through their employer with an SSS reimbursement form. Self-employed members bring documents directly to the SSS branch. OFW members can file through an authorized representative." },
    { question: "Can I allocate maternity leave days to the father?", answer: "Yes. Under RA 11210, the mother can allocate up to 7 days of her maternity leave to the child's father or an alternate caregiver. This is separate from the 7-day paternity leave under RA 8187. The allocation must be in writing, and the father/caregiver must be an SSS member or employed by the same company. Total shared days cannot exceed the mother's entitlement." },
    { question: "What happens if I have less than 3 SSS contributions?", answer: "You will not qualify for SSS maternity benefit if you have fewer than 3 monthly contributions in the 12-month period before the semester of delivery. However, you may still be entitled to unpaid maternity leave under RA 11210. Consider making voluntary contributions to meet the 3-month requirement before your expected delivery semester." },
    { question: "How does maternity benefit work for OFW members?", answer: "OFW SSS members qualify for maternity benefit if they meet the contribution requirement. File the claim at the nearest SSS branch upon return to the Philippines or through an authorized representative while abroad. Processing may take longer for OFW claims due to document verification. Benefits are disbursed to the registered Philippine bank account or UMID-ATM card." },
  ]
});

// === PAG-IBIG MP2 ===
upgrade("pag-ibig-mp2-calculator", {
  description: "Use this Pag-IBIG MP2 calculator to estimate how your monthly savings can grow over time with projected dividends. A lot of people hear that MP2 is one of the easiest low-risk savings options in the Philippines, but the real question is always the same: how much could the account actually grow if you stay consistent? This tool helps make that answer easier to picture before you commit your money. The Pag-IBIG MP2 (Modified Pag-IBIG 2) program is a voluntary savings program open to all Pag-IBIG members. Unlike regular Pag-IBIG savings, MP2 offers higher dividend rates and tax-free earnings, making it one of the most attractive low-risk investment options available to Filipinos. The program operates on a 5-year savings cycle, after which you can withdraw your total savings plus accumulated dividends. What makes MP2 particularly appealing is its historical dividend performance — consistently outperforming bank savings accounts and time deposits while carrying significantly lower risk than stocks or mutual funds. This calculator projects your potential growth based on your monthly contribution, expected dividend rate, and investment period.",
  formulaExplanation: "The future value formula estimates how repeated monthly contributions can grow when dividends are added over time. PMT is your monthly contribution, r is the annual dividend rate, and n is the number of years. The formula compounds monthly, reflecting how dividends earned in earlier periods generate additional dividends in later periods. It is not a guarantee of the official future payout, but it gives you a useful planning estimate when comparing different contribution levels. Pag-IBIG declares dividends annually, and the actual rate varies each year based on the fund's investment performance. Historical rates have ranged from 5% to 7.5% over the past decade, significantly higher than typical bank savings rates of 0.25% to 1%. The compounding effect becomes more pronounced over longer periods — a ₱5,000 monthly contribution at 7% earns roughly ₱58,000 in dividends over 5 years, but nearly ₱300,000 in dividends over 10 years (with re-enrollment).",
  exampleCalculation: "Example 1: ₱5,000/month for 5 years at 7% = Total contributions ₱300,000, estimated value ₱358,000, dividends earned ₱58,000. Example 2: ₱2,000/month for 5 years at 7% = Contributions ₱120,000, estimated value ₱143,200, dividends ₱23,200. Example 3: ₱10,000/month for 5 years at 6% = Contributions ₱600,000, estimated value ₱697,000, dividends ₱97,000. Example 4: Lump sum ₱100,000 + ₱5,000 monthly for 5 years at 7% = Starting balance grows to ₱140,255 plus monthly contributions grow to ₱358,000 = Total ₱498,255. Example 5: ₱500/month (minimum) for 5 years at 7% = Contributions ₱30,000, estimated value ₱35,800, dividends ₱5,800.",
  philippinesContext: "Pag-IBIG MP2 is popular in the Philippines because it is simple, accessible, and offers returns that consistently beat regular savings accounts and time deposits. Dividends are tax-free, which is a major advantage over time deposits (subject to 20% withholding tax) and stock dividends (subject to 10% final tax). The minimum contribution is ₱500 per month or a one-time deposit. Contributions can be made at any Pag-IBIG branch, through partner banks (BDO, BPI, Landbank), via GCash and Maya, or through online banking. The program matures after 5 years from the date of first contribution. After maturity, members can withdraw the full amount or re-enroll for another 5-year cycle. Early withdrawal before 5 years forfeits the dividends for the current year. Historical dividend rates: 2019 (7.12%), 2020 (6.12%), 2021 (6.01%), 2022 (6.63%), 2023 (7.03%). The Pag-IBIG Fund invests MP2 contributions primarily in government securities, corporate bonds, and real estate, maintaining a conservative risk profile. For OFWs and self-employed individuals, MP2 serves as a disciplined savings mechanism with guaranteed returns above inflation. Financial advisors in the Philippines frequently recommend MP2 as a foundation for emergency funds and medium-term savings goals before diversifying into higher-risk investments.",
  faqs: [
    { question: "What is the minimum MP2 contribution?", answer: "The minimum Pag-IBIG MP2 contribution is ₱500. You can contribute monthly, quarterly, or make a one-time lump sum deposit. There is no maximum contribution limit, making it flexible for both modest savers and those who want to park larger amounts. Many members start at ₱500 and gradually increase as their income grows." },
    { question: "Are MP2 dividends taxable?", answer: "No. MP2 dividends are 100% tax-free, which is a significant advantage over other savings instruments. Bank time deposits are subject to 20% withholding tax on interest, and stock dividends face 10% final tax. A 7% MP2 dividend is equivalent to an 8.75% time deposit rate before tax — a substantial difference that compounds over years." },
    { question: "When does MP2 mature?", answer: "MP2 matures after 5 years from the date of your first contribution. After maturity, you can withdraw the total amount (contributions plus all dividends) or re-enroll for another 5-year cycle. Many experienced savers re-enroll immediately to maintain the compounding momentum. The maturity date is based on your first contribution, not your latest one." },
    { question: "Can I withdraw MP2 savings before 5 years?", answer: "Yes, but you forfeit the dividends for the current year. Your total contributions will be returned, plus dividends from completed previous years. This penalty discourages early withdrawal and is why MP2 should be treated as a medium-term savings commitment. For true emergency funds, keep 3-6 months of expenses in a regular savings account separately." },
    { question: "Is MP2 better than a regular savings account?", answer: "For medium-term savings (3-5 years), MP2 significantly outperforms regular savings accounts. MP2 has historically paid 5-7% tax-free dividends versus 0.25-1% taxable interest from bank savings. However, MP2 locks your money for 5 years, while savings accounts offer instant liquidity. The ideal strategy is maintaining both: liquid emergency fund in a bank account, growth savings in MP2." },
    { question: "How do I open a Pag-IBIG MP2 account?", answer: "Visit any Pag-IBIG branch with a valid ID and your Pag-IBIG MID number. Fill out the MP2 application form and make your initial contribution (minimum ₱500). You can also apply online through the Pag-IBIG Virtual Office. After opening, make subsequent contributions at Pag-IBIG branches, partner banks (BDO, BPI, Landbank), GCash, Maya, or online banking." },
    { question: "What dividend rate should I use for projections?", answer: "Use 6-7% as a conservative estimate based on historical performance. Actual rates: 2019 (7.12%), 2020 (6.12%), 2021 (6.01%), 2022 (6.63%), 2023 (7.03%). The rate fluctuates annually based on Pag-IBIG Fund investment returns. For financial planning, using 6% provides a margin of safety. Actual results may be higher or lower depending on market conditions." },
    { question: "Can I contribute irregularly to MP2?", answer: "Yes. Unlike regular Pag-IBIG contributions, MP2 allows flexible contribution schedules. You can contribute monthly, quarterly, annually, or make lump sum deposits whenever you have extra money. There is no penalty for skipping months. However, consistent monthly contributions maximize compounding benefits. Many members set up auto-debit arrangements for disciplined saving." },
    { question: "How is MP2 different from regular Pag-IBIG savings?", answer: "Regular Pag-IBIG is mandatory for employed members with lower dividend rates (around 2-3%). MP2 is voluntary with higher dividends (5-7%), tax-free earnings, and a fixed 5-year maturity. Regular Pag-IBIG can be withdrawn upon retirement, disability, or membership cancellation. MP2 matures after exactly 5 years. Both are managed by the Pag-IBIG Fund but serve different savings purposes." },
    { question: "Can OFWs open an MP2 account?", answer: "Yes. OFWs who are Pag-IBIG members can open and contribute to MP2. Contributions can be made through Pag-IBIG overseas offices, partner remittance channels, or online through the Virtual Pag-IBIG portal. Many OFWs use MP2 as a forced savings mechanism to build a nest egg while working abroad, with the 5-year maturity aligning with typical overseas contract cycles." },
    { question: "What happens to MP2 savings if the member dies?", answer: "MP2 savings (contributions plus accumulated dividends) are released to the member's designated legal heirs or beneficiaries. The beneficiaries must present the death certificate, proof of relationship, and other required documents at any Pag-IBIG branch. Processing takes 30-45 working days. It is important to update your MP2 beneficiary designation regularly, especially after marriage or birth of children." },
    { question: "Is MP2 insured by PDIC?", answer: "No. MP2 is not covered by PDIC (Philippine Deposit Insurance Corporation) because it is not a bank deposit. However, it is backed by the Pag-IBIG Fund, a government financial institution. The fund invests primarily in government securities and real estate, maintaining a conservative risk profile. While not explicitly insured, the government backing provides a strong safety net for member savings." },
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 1 complete: night-differential, sss-maternity, pag-ibig-mp2');
