import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, (_, g1, g2, g3) => g1 + data.description + g3);
  
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, (_, g1, g2, g3) => g1 + data.formulaExplanation + g3);
  
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, (_, g1, g2, g3) => g1 + data.exampleCalculation + g3);
  
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, (_, g1, g2, g3) => g1 + data.philippinesContext + g3);
  
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, (_, g1, g2) => g1 + '\n' + faqStr + ',\n    ' + g2);
  console.log(`Upgraded: ${slug}`);
}

upgrade("angel-number-calculator", {
  description: "Discover the hidden spiritual meanings behind your name and birthdate with this precise Angel Number Calculator. Numerology, an ancient esoteric science, suggests that the universe communicates with us through repeating number sequences known as 'Angel Numbers' (like 111, 444, or 888). Have you ever noticed that you constantly wake up at 3:33 AM, or your receipts always total ₱7.77? Numerologists believe these are not mere coincidences, but deliberate signs or 'nudges' from your guardian angels or higher self, offering guidance, reassurance, or a warning regarding your current life path. This calculator utilizes classic Pythagorean numerology to break down the letters of your full birth name and your birthdate into single-digit root numbers (1-9) or Master Numbers (11, 22, 33). By reducing your personal data into these core vibrations, it reveals your Life Path Number, Destiny Number, and personal Angel Number alignment, giving you profound insight into your overarching soul purpose and the specific cosmic energies influencing your daily decisions.",
  formulaExplanation: "The mathematical foundation of this calculator relies on the Pythagorean numerology system. Every letter in the alphabet is assigned a numerical value from 1 to 9 (A=1, B=2, C=3... I=9, J=1... etc.). When calculating a Name Number, the calculator converts each letter in your full given name into its corresponding digit. It then sums all these digits together. If the total is a multi-digit number (e.g., 45), it is further reduced by adding the digits together (4 + 5 = 9) until a single-digit root number (1-9) is achieved. The only exception to this reduction rule is if the intermediate sum is a 'Master Number'—specifically 11, 22, or 33. These numbers hold immense spiritual power and are never reduced. For calculating the Life Path Number (based on the birthdate), the day, month, and year are each reduced to a single digit or Master Number separately, and then those three remaining numbers are added together and reduced one final time.",
  exampleCalculation: "Example 1 (Life Path Calculation): Your birthdate is December 15, 1990. Month: December is the 12th month (1 + 2 = 3). Day: The 15th (1 + 5 = 6). Year: 1990 (1 + 9 + 9 + 0 = 19; 1 + 9 = 10; 1 + 0 = 1). Finally, add the reduced Month, Day, and Year together: 3 + 6 + 1 = 10. Reduce again: 1 + 0 = 1. Your Life Path Number is 1, symbolizing leadership and independence. Example 2 (Name Calculation): The name 'ANA'. A=1, N=5, A=1. The sum is 1 + 5 + 1 = 7. The Name Number is 7, symbolizing spiritual depth and analytical thinking. Example 3 (Master Number): A birthdate of November 11, 1988. Month: November (11 - do not reduce). Day: 11 (do not reduce). Year: 1988 (1+9+8+8 = 26; 2+6 = 8). Sum: 11 + 11 + 8 = 30. Reduce: 3 + 0 = 3. Life Path is 3. The calculator performs all these tedious multi-step reductions instantly and accurately.",
  philippinesContext: "In the Philippines, formal esoteric traditions seamlessly blend with deeply ingrained local superstitions and Catholic mysticism. While purely Western numerology is popular among younger, internet-savvy Filipinos on platforms like TikTok (where #AngelNumbers has billions of views), it taps into a much older cultural fascination with numbers and fate. For instance, many Filipinos consult 'feng shui' experts in Binondo or local 'manghuhula' (fortune tellers) in Quiapo before making major life decisions, such as picking a wedding date, buying a house, or choosing a license plate number that 'attracts wealth'. The concept of receiving signs from guardian angels resonates strongly in a predominantly Catholic country where devotion to protective saints and angels is a daily practice. This calculator serves as a modern, accessible bridge to these spiritual inquiries, providing Filipino users with a personalized numerical guide to help them navigate career choices, romantic relationships, and moments of profound personal uncertainty.",
  faqs: [
    { question: "What exactly are Angel Numbers?", answer: "Angel Numbers are repeating sequences of numbers (like 111, 222, 333) that you frequently encounter in your daily life. Numerologists believe these are synchronous messages from the spiritual realm, meant to offer guidance, validation, or a wake-up call." },
    { question: "How does my name calculate into a number?", answer: "In the Pythagorean system, each letter of the alphabet is assigned a value from 1 to 9 (e.g., A=1, B=2, I=9, J=1). The values of all the letters in your full birth name are added together, and that sum is reduced to a single digit." },
    { question: "Should I use my married name or my birth name?", answer: "For the most accurate assessment of your 'Destiny Number' or core soul vibration, you must use your exact, full name as it appears on your birth certificate. If you legally changed your name or married, your new name represents a secondary, acquired energy." },
    { question: "What is a Master Number?", answer: "In numerology, the numbers 11, 22, and 33 are considered Master Numbers. They are highly charged with spiritual energy and potential. When calculating your numbers, if an intermediate sum results in 11, 22, or 33, you do not reduce them to 2, 4, or 6." },
    { question: "What does seeing the number 111 mean?", answer: "111 is often considered the number of manifestation and new beginnings. It is a sign that your thoughts are rapidly becoming reality, so you should focus on your desires rather than your fears. It signals a spiritual awakening." },
    { question: "What does seeing 444 mean?", answer: "444 is widely known as the 'protection' number. It signifies that your guardian angels are physically and spiritually present around you, offering support and safety. It is a highly comforting sign during times of immense stress or danger." },
    { question: "What does seeing 777 mean?", answer: "777 is associated with divine alignment, inner wisdom, and massive spiritual growth. It is often a sign that you are on the exact right path and that good fortune, intuition, or a deep spiritual breakthrough is imminent." },
    { question: "What is the difference between my Life Path Number and my Angel Number?", answer: "Your Life Path Number is fixed; it is calculated from your birthdate and represents your overarching life purpose and inherent traits. Your 'Angel Numbers' are the repeating numbers you see dynamically in your environment, providing real-time guidance." },
    { question: "Is numerology scientifically proven?", answer: "No. Numerology is a metaphysical science, similar to astrology or tarot. It relies on the concept of synchronicity rather than empirical scientific evidence. It should be used as a tool for self-reflection and introspection, not hard scientific fact." },
    { question: "Why do I keep seeing the same number everywhere?", answer: "According to Carl Jung's theory of synchronicity, seeing the same number repeatedly is a meaningful coincidence reflecting your current psychological state. Metaphysically, it is interpreted as the universe attempting to grab your attention." },
    { question: "Does this calculator use Chaldean or Pythagorean numerology?", answer: "This calculator uses the Pythagorean numerology system, which is the most widely used and accessible system in the Western world. It maps the alphabet sequentially from 1 to 9." },
    { question: "What if my Life Path number is 8?", answer: "The number 8 is associated with power, material wealth, business acumen, and karmic balance. Individuals with an 8 Life Path are often driven, ambitious, and highly focused on achieving tangible, financial success and authority in their chosen field." }
  ]
});

upgrade("sun-moon-rising-sign-calculator", {
  description: "Unveil the complexities of your true astrological identity with this definitive Sun, Moon, and Rising Sign Calculator. While most people know their 'Star Sign' (which is technically your Sun Sign), modern astrology recognizes that you are far more than just one zodiac archetype. Your Sun sign only dictates your core ego and overarching life purpose. To truly understand your emotional reactions, hidden desires, and the 'mask' you present to the world, you must calculate your 'Big Three': your Sun, Moon, and Ascendant (Rising) signs. Your Moon sign governs your deepest emotional landscape, your subconscious instincts, and how you process grief or joy in private. Your Rising sign is the specific zodiac constellation that was cresting the eastern horizon at the exact minute of your birth; it dictates your outward appearance, your first impressions, and your social persona. This calculator uses complex ephemeris data to triangulate these three critical points, providing a comprehensive, multi-dimensional astrological profile that explains why two people with the same Sun sign can have wildly different personalities.",
  formulaExplanation: "Calculating the 'Big Three' requires precise astronomical algorithms. The Sun sign is the easiest: it is determined by the Earth's orbit around the Sun and changes approximately every 30 days (e.g., Aries from March 21 to April 19). The Moon sign requires much more precision; the Moon moves incredibly fast, changing zodiac signs every 2.5 days. The most complex calculation is the Rising Sign (Ascendant). Because the Earth rotates on its axis once every 24 hours, the zodiac sign rising on the eastern horizon changes every two hours. The formula requires three precise data points: your exact Date of Birth, your exact Time of Birth (down to the minute), and the exact Geographical Coordinates (Latitude and Longitude) of the city you were born in. The calculator uses a digital ephemeris (a table of planetary positions) to compute the exact degree of the ecliptic intersecting the horizon at that specific time and place. If your birth time is off by even 15 minutes, your Rising sign calculation could be completely incorrect.",
  exampleCalculation: "Example 1 (The Conflicted Personality): You were born on August 15th, making you a proud, outgoing Leo Sun. However, you often feel incredibly shy, emotional, and introverted. The calculator reveals you have a Cancer Moon (deeply sensitive) and a Virgo Rising (analytical and reserved). This explains the profound conflict between your core ego and your emotional instincts. Example 2 (The Fast-Changing Ascendant): You were born in Manila at 6:15 AM on October 1st. The calculator determines your Rising sign is Libra. Your twin sister was born at 6:45 AM. By that time, the Earth had rotated enough that the constellation Scorpio had crossed the eastern horizon. Despite being twins born 30 minutes apart, she has a Scorpio Rising, giving her a completely different, much more intense outward aura than your diplomatic Libra persona. Precision is everything in astrological calculation.",
  philippinesContext: "Astrology has experienced a massive resurgence among Gen Z and Millennials in the Philippines, heavily popularized by local Twitter 'astrologers' and viral TikTok readings. It has moved far beyond the daily horoscopes found in the back of local tabloids (like Abante or Bulgar). Today, knowing your 'Big Three' is practically a requirement for modern dating in Metro Manila; it is incredibly common for young Filipinos to ask for a potential partner's birth time during a first date or prominently display their Sun/Moon/Rising signs on their Bumble or Tinder profiles. The 'Co-Star' app phenomenon proved that local users crave deep, analytical, and somewhat harsh astrological truths. Because the Philippines is located in a specific time zone (GMT+8) and near the equator, the angles of the ascendant calculate slightly differently than they do in northern Europe or America. This calculator ensures the geographic math is perfectly tailored, allowing Filipino users to generate accurate natal charts without paying expensive consultation fees to private astrologers.",
  faqs: [
    { question: "What is my Sun Sign?", answer: "Your Sun sign is the zodiac sign the Sun was in when you were born. It represents your core identity, your ego, your conscious mind, and your overarching life goals. It is the basic 'star sign' everyone knows based on their birth month." },
    { question: "What is my Moon Sign?", answer: "Your Moon sign is the zodiac sign the Moon was in at your exact time of birth. It represents your subconscious mind, your deepest emotional needs, your instincts, and how you behave in private or when you feel emotionally vulnerable." },
    { question: "What is my Rising Sign (Ascendant)?", answer: "Your Rising sign is the zodiac constellation that was rising on the eastern horizon at the exact minute and location of your birth. It represents the 'mask' you wear in public, your first impressions, and your outward physical energy." },
    { question: "Why do I need to know my exact birth time?", answer: "While your Sun sign changes every 30 days and your Moon sign every 2.5 days, your Rising sign changes every 2 hours as the Earth rotates. If you do not know your exact birth time (from a birth certificate), you cannot accurately calculate your Rising sign." },
    { question: "What if I don't know my birth time?", answer: "If you don't have a birth certificate and your parents don't remember, you can usually only calculate your Sun sign accurately. You can estimate your Moon sign, but the calculator will not be able to provide your Rising sign." },
    { question: "Why do I need to enter my birth city?", answer: "The Rising sign is a geographic calculation based on the horizon. The horizon looks completely different at 8:00 AM in Manila compared to 8:00 AM in New York. The calculator needs your exact latitude and longitude to find the correct horizon line." },
    { question: "What does it mean if my Big Three are all the same sign?", answer: "This is relatively rare and is called a 'stellium'. If you are a Aries Sun, Aries Moon, and Aries Rising, the traits of Aries (impulsive, brave, aggressive) are overwhelmingly dominant in your personality, with almost no contrasting energies to balance them out." },
    { question: "Which is the most important: Sun, Moon, or Rising?", answer: "They are all equally important, but they govern different parts of your life. The Sun is your overarching purpose, the Moon is your internal emotional compass, and the Rising is your external interface with the physical world." },
    { question: "Can two people have the exact same Big Three?", answer: "Yes, but they would have to be born on the exact same day, in the same geographical region, within roughly the same two-hour window. Even then, other planetary placements (like Venus or Mars) in their full natal chart would differ." },
    { question: "Why do my calculator results differ from my horoscope app?", answer: "There are two different zodiac systems: Tropical (Western) and Sidereal (Vedic). This calculator uses the standard Tropical system. If your app uses Sidereal, which accounts for the physical shifting of constellations over 2,000 years, your signs will appear completely different." },
    { question: "What does a Scorpio Moon mean?", answer: "A Scorpio Moon indicates incredibly intense, deep, and often secretive emotional responses. People with this placement feel things profoundly, are highly intuitive, and often struggle with issues of trust and emotional control in their private lives." },
    { question: "What does a Libra Rising mean?", answer: "A Libra Rising gives a person an outward aura of charm, diplomacy, and aesthetic grace. They often prioritize harmony in their social interactions, hate conflict, and typically have a very refined or attractive physical presence." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 16 complete');
