import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function addToField(slug: string, field: string, extra: string) {
  const marker = `slug: "${slug}"`;
  const idx = c.indexOf(marker);
  if (idx === -1) return;
  const chunk = c.substring(idx, idx + 12000);
  const re = new RegExp(`(${field}: ")([^"]*)(")`);
  const m = chunk.match(re);
  if (!m) return;
  const replaced = chunk.replace(re, (_, g1, g2, g3) => g1 + g2 + " " + extra + g3);
  c = c.substring(0, idx) + replaced + c.substring(idx + 12000);
}

addToField("angel-number-calculator", "description", "Furthermore, understanding your specific Angel Number is not just about passive observation; it is about active, conscious co-creation with the universe. When you identify your core numerological vibration, you can begin to make choices that align mathematically with your destiny. For example, if your Destiny Number is 5 (the number of freedom, travel, and sudden change), taking a rigid, highly structured corporate desk job will likely cause you immense spiritual friction and depression. The universe will send you repeating '555' signs as a jarring wake-up call to change course. Conversely, if your Life Path is 4 (the builder, stability, hard work), seeing '444' validates that your slow, meticulous efforts are divinely protected and will soon bear fruit. This calculator empowers you to decipher these subtle cosmic nudges instantly, allowing you to stop second-guessing your intuition and boldly step into the life path you were mathematically designed to experience.");
addToField("angel-number-calculator", "philippinesContext", "The integration of numerology into modern Filipino life is also heavily tied to the pervasive culture of luck and gambling, such as the daily Jueteng draws in the provinces or the massive PCSO Lotto jackpots. It is incredibly common for Filipinos to calculate the 'lucky numbers' derived from the birthdates of deceased relatives, anniversary dates, or specific 'Angel Numbers' they saw in a dream before buying a lottery ticket at the local mall. Beyond gambling, understanding one's Life Path number is becoming a popular tool for psychological profiling in local corporate HR departments (often unofficially) to determine team compatibility. By providing an accurate, culturally resonant tool for calculating these esoteric numbers, this calculator helps demystify the complex Pythagorean mathematics behind the superstition, allowing Filipino users to approach numerology not just as a desperate grasp for luck, but as a profound tool for introspective self-analysis and personal growth.");

addToField("sun-moon-rising-sign-calculator", "description", "Furthermore, knowing your Big Three is the absolute foundation of astrological 'Synastry'—the study of relationship compatibility. You might read in a magazine that an Aries (Fire) and a Cancer (Water) are totally incompatible because their Sun signs clash. However, if the Aries has a Cancer Moon, and the Cancer has an Aries Rising, they will likely experience an intense, magnetic, and deeply understanding connection that defies superficial Sun-sign astrology. Their internal emotional landscapes and outward personas are perfectly cross-wired. This calculator is essential for anyone trying to navigate the complexities of modern dating, family dynamics, or even workplace friction. By generating your precise Big Three, you can stop blaming yourself for feeling 'out of sync' with your generic Sun sign horoscopes and finally embrace the complex, contradictory, and entirely unique astrological blueprint that makes you who you are.");
addToField("sun-moon-rising-sign-calculator", "philippinesContext", "In the deeply social, highly interconnected culture of the Philippines, 'Pakikisama' (the ability to get along with others) is considered a vital survival skill. However, conforming to societal expectations often leads to profound internal burnout. The local rise of detailed psychological astrology offers young Filipinos a rare framework to validate their individualism in a society that often demands conformity. When a Filipino user discovers they have an Aquarius Moon (rebellious, emotionally detached) hidden behind a conservative Capricorn Sun, it suddenly explains their lifelong feeling of being the 'black sheep' of their highly traditional, Catholic family. Armed with the precise data from this calculator, local users are forming highly specific online communities—creating Twitter group chats exclusively for 'Scorpio Moon support' or 'Gemini Rising networking'—fostering a new era of digital empathy and deep psychological self-awareness across the archipelago.");

addToField("lilith-sign-calculator", "description", "Furthermore, understanding your Black Moon Lilith is crucial for breaking free from toxic, repetitive karmic loops in your interpersonal relationships. Because Lilith represents the rejected shadow, we often subconsciously project our Lilith energy onto other people. If you have Lilith in Aries but you suppress your own anger and aggression (perhaps due to childhood conditioning), you will inevitably attract highly aggressive, domineering, or volatile partners who act out the rage you refuse to express. This is the classic psychological mechanism of 'shadow projection.' You are drawn to them because they possess the raw fire you desperately crave, but they ultimately become destructive. By using this calculator to precisely identify your Lilith placement, you can take ownership of that repressed energy. Once you integrate your Lilith—allowing yourself to be angry, sexual, or unapologetically selfish in healthy, controlled ways—you instantly stop attracting toxic individuals who mirror your unhealed trauma. This tool is the first step toward profound relational healing.");
addToField("lilith-sign-calculator", "philippinesContext", "The psychological weight of 'Hiya' (shame) in Filipino culture dictates that women, in particular, must maintain an impeccable public image of modesty, extreme self-sacrifice (often as the 'breadwinner' for the extended family), and emotional restraint. In this context, calculating and confronting one's Black Moon Lilith is an act of radical cultural rebellion. It provides a structured, astrological vocabulary for young Filipinas to finally articulate the exhaustion of constantly putting themselves last. Discovering a Lilith in Leo might validate a deeply buried, 'shameful' desire for immense public recognition and personal luxury, rather than quiet martyrdom. Local psychologists and life coaches incorporating esoteric practices often use Lilith placements as ice-breakers for severe trauma therapy, helping clients decouple their self-worth from the impossible standards of traditional Philippine societal expectations. This calculator empowers that deeply necessary shadow work.");

addToField("chiron-sign-calculator", "description", "Furthermore, tracking the 'transits' of Chiron provides profound insight into the timing of your major life crises and spiritual breakthroughs. The most critical of these is the 'Chiron Return,' which occurs around the age of 50 when Chiron completely orbits the sun and returns to the exact mathematical degree it occupied when you were born. This astrological milestone often coincides with what society loosely terms a 'mid-life crisis.' However, astrologically, it is not a crisis, but a harsh, unavoidable spiritual reckoning. During your Chiron Return, the universe forces you to confront the core wound you have been running from for five decades. If you have done the necessary shadow work, this period marks a massive transition into becoming a 'wise elder' or a powerful mentor. If you have ignored the wound, this transit can cause intense psychological distress and the collapse of superficial life structures. This calculator is the mandatory first step in preparing for that inevitable spiritual exam.");
addToField("chiron-sign-calculator", "philippinesContext", "The Filipino cultural concept of 'Resilience' is famously celebrated worldwide—the ability to smile and rebuild immediately after a devastating super typhoon or economic collapse. However, modern Filipino psychologists heavily criticize this 'toxic resilience' because it forces individuals to swallow their trauma rather than process it. Calculating the Chiron sign provides a stark, necessary counter-narrative to this toxic positivity. It validates the fact that some wounds are permanent, and that it is okay to be fundamentally 'broken' in a specific area of your life. When young Filipinos calculate their Chiron in the 10th House (wounds related to authority and career), it offers a profound explanation for the intense, paralyzing anxiety they feel trying to meet the crushing expectations of their immigrant parents or 'Tiger Asian' family dynamics. By providing exact planetary placements, this calculator gives them the permission to stop pretending everything is fine, and start the grueling, beautiful process of authentic healing.");

fs.writeFileSync(file, c);
console.log('Boost batch 16 complete');
