import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("cochran-formula-calculator", {
  description: "Compute your required sample size using the Cochran formula, a statistically rigorous method widely used in Philippine academic research. The Cochran formula is more flexible than the Slovin formula because it lets you specify your desired confidence level (90%, 95%, or 99%) and expected response distribution, giving you precise control over sample size determination. This calculator is essential for thesis students, market researchers, and survey designers who need defensible sample sizes backed by statistical theory. Unlike the simplified Slovin approach, the Cochran formula accounts for population variability through the p and q parameters, making it suitable for studies where you have prior knowledge about the expected proportion of responses. For large or unknown populations, the Cochran formula provides the infinite population sample size, which can then be adjusted using the finite population correction factor for known smaller populations. Philippine thesis panels in graduate schools increasingly prefer the Cochran formula over Slovin because it demonstrates a deeper understanding of sampling theory and produces more statistically defensible results. Whether you are conducting descriptive research, correlational studies, or quasi-experimental designs, proper sample size determination is the foundation of credible quantitative research.",
  formulaExplanation: "The Cochran formula computes sample size as: n0 = (Z squared times p times q) divided by e squared, where Z is the Z-score corresponding to your confidence level (1.645 for 90%, 1.96 for 95%, 2.576 for 99%), p is the estimated proportion of the population with the attribute of interest, q equals 1 minus p, and e is the desired margin of error. For unknown proportions, use p = 0.5 (maximum variability), which gives the largest and most conservative sample size. For finite populations, apply the correction: n = n0 divided by (1 + (n0 minus 1) divided by N). This adjusted formula prevents oversampling from small populations. The confidence level determines how sure you can be that your sample results reflect the true population — 95% means if you repeated the study 100 times, 95 would produce results within your margin of error. The margin of error is the acceptable range around your estimate — a 5% margin means your result could be 5 percentage points above or below the true value. Selecting appropriate values for each parameter requires understanding your research context, available resources, and the precision needed for meaningful conclusions.",
  exampleCalculation: "Example 1: 95% confidence, 5% margin, p = 0.5, infinite population. Z = 1.96. n0 = (1.96 squared x 0.5 x 0.5) / 0.05 squared = 3.8416 x 0.25 / 0.0025 = 384.16, rounded to 385. Example 2: Same parameters with population N = 1,000. n = 385 / (1 + 384/1000) = 385 / 1.384 = 278. Example 3: 99% confidence, 3% margin, p = 0.5, N = 5,000. n0 = (2.576 squared x 0.25) / 0.0009 = 1,843. Adjusted: n = 1,843 / (1 + 1842/5000) = 1,843 / 1.368 = 1,347. Example 4: 95% confidence, 5% margin, p = 0.3 (known from prior research), N = 2,000. n0 = (3.8416 x 0.3 x 0.7) / 0.0025 = 323. Adjusted: n = 323 / (1 + 322/2000) = 278.",
  philippinesContext: "The Cochran formula is taught in Philippine graduate-level research methodology courses and is referenced in standard Filipino research textbooks. CHED-accredited thesis panels in MBA, MA Education, and MS programs typically expect graduate students to use either Cochran or Slovin formula with proper justification. The Cochran formula is preferred when the researcher wants to specify a particular confidence level or when prior studies provide an estimated proportion (p value) for the variable of interest. In Philippine nursing research, education studies, and public administration theses, the 95% confidence level with 5% margin of error is the most commonly used parameter combination. For studies with sensitive topics where response rates may be low, researchers often increase the computed sample by 10-20% to account for non-responses and invalid questionnaires. Philippine Statistical Authority (PSA) surveys and SWS/Pulse Asia polls use similar formulas with 95% confidence and plus or minus 2-3% margins for national surveys of 1,200-2,400 respondents. Understanding the Cochran formula helps students appreciate why these national polls can represent 110 million Filipinos with relatively small samples. The formula also applies to quality control sampling in Philippine manufacturing and BPO industries where Six Sigma methodologies require statistically determined sample sizes for process evaluation.",
  faqs: [
    { question: "What is the Cochran formula for sample size?", answer: "The Cochran formula is n0 = Z squared times p times q divided by e squared. Z is the Z-score for your confidence level (1.96 for 95%), p is the expected proportion, q is 1 minus p, and e is the margin of error. For unknown proportions, use p = 0.5. This gives the minimum sample needed for statistically valid results." },
    { question: "When should I use Cochran instead of Slovin?", answer: "Use Cochran when you need to specify a confidence level other than 95%, when you have prior knowledge about the population proportion (p is not 0.5), or when your thesis panel requires a more rigorous sampling justification. Cochran is also preferred for graduate-level research. Slovin is a simplified special case of Cochran with fixed 95% confidence and p = 0.5." },
    { question: "What confidence level should I use for my thesis?", answer: "95% confidence is the standard for most Philippine academic research and is accepted by virtually all thesis panels. Use 99% for medical, pharmaceutical, or high-stakes research where errors have serious consequences. Use 90% only for preliminary or exploratory studies. Your thesis methodology chapter should justify the chosen confidence level." },
    { question: "What is the finite population correction factor?", answer: "The correction formula n = n0 / (1 + (n0-1)/N) adjusts the sample size for known finite populations. Without this correction, the Cochran formula overestimates the needed sample for small populations. Example: Cochran gives 385 for infinite population, but for N = 500, the corrected sample is only 217. Always apply this correction when your population is known and under 50,000." },
    { question: "What p value should I use if I do not know the proportion?", answer: "Use p = 0.5 (50%). This produces the maximum possible sample size, making it the most conservative estimate. As p moves away from 0.5 in either direction, the required sample decreases. If prior research suggests your attribute occurs in 30% of the population, using p = 0.3 reduces the sample by about 16% compared to p = 0.5." },
    { question: "How is Cochran formula different from Raosoft calculator?", answer: "Raosoft uses the same underlying Cochran formula but packages it in a user-friendly online interface. The mathematical foundation is identical. Raosoft adds a finite population correction automatically when you input the population size. Both produce the same results for the same parameters. In Philippine theses, citing the Cochran formula directly is more academically rigorous than citing Raosoft." },
    { question: "What Z-score corresponds to each confidence level?", answer: "90% confidence = Z of 1.645. 95% confidence = Z of 1.96. 99% confidence = Z of 2.576. These values come from the standard normal distribution table and represent the number of standard deviations from the mean needed to capture the desired proportion of the distribution. Most statistics textbooks and formula sheets include these Z-values." },
    { question: "Can I use Cochran formula for qualitative research?", answer: "No. Cochran formula is for quantitative, survey-based research. Qualitative studies use theoretical saturation to determine sample size — typically 15-30 participants for interviews or 3-6 focus groups. For mixed-methods research common in Philippine graduate programs, apply Cochran to the quantitative component and saturation to the qualitative component separately." },
    { question: "How do I cite the Cochran formula in my thesis?", answer: "Cite: Cochran, W.G. (1977). Sampling Techniques (3rd ed.). New York: John Wiley and Sons. This is the standard academic reference accepted by all Philippine universities. Include the full formula, your parameter choices (confidence level, margin, p value, population), and the computed sample size in your methodology chapter." },
    { question: "Why is 384 the magic number in sampling?", answer: "The number 384 (or 385 rounded up) appears frequently because it is the Cochran sample size for 95% confidence, 5% margin of error, and p = 0.5 with an infinite population. This is the most common parameter combination in social science research worldwide. For Philippine studies with populations over 50,000, this number applies without finite population correction." },
    { question: "How does margin of error affect sample size?", answer: "Margin of error has a dramatic impact because it is squared in the denominator. Reducing margin from 5% to 3% increases sample from 385 to 1,068 (2.8 times larger). Reducing to 1% requires 9,604 respondents. This exponential relationship means small improvements in precision require disproportionately larger samples, which directly affects research budget and timeline." },
    { question: "Is Cochran formula accepted by CHED for thesis research?", answer: "Yes. CHED does not mandate a specific formula but requires statistical justification for sample size. The Cochran formula satisfies this requirement and is considered more rigorous than Slovin. It is taught in CHED-prescribed research methodology courses and appears in approved textbooks. Both undergraduate and graduate thesis panels accept Cochran formula with proper parameter justification." },
  ]
});

upgrade("mlbb-win-rate-calculator", {
  description: "Calculate your Mobile Legends: Bang Bang (MLBB) win rate and find out how many consecutive wins you need to reach your target win rate. MLBB is the most popular mobile game in the Philippines with over 30 million Filipino players, and win rate is the primary performance metric that players track obsessively. Whether you are trying to push from Epic to Legend rank, maintain a 60% overall win rate for hero mastery, or understand why your stats feel stuck, this calculator gives you clear answers. Many players do not realize that improving a low win rate requires far more consecutive wins than they expect — going from 50% to 55% on 1,000 matches requires 111 straight wins without a single loss. This mathematical reality explains why consistent gameplay improvement matters more than occasional win streaks. The calculator also helps you set realistic goals: if your current win rate is 48% with 500 matches, achieving 55% requires winning 78 of your next 100 games — a 78% win rate over that stretch. Understanding these numbers helps you plan your ranked grind, decide when to switch heroes, and evaluate whether a hero is truly performing well for you or just feels good subjectively.",
  formulaExplanation: "The win rate formula is straightforward: Win Rate (%) = (Total Wins / Total Matches) x 100. To calculate wins needed for a target rate, solve the equation: Target WR = (Current Wins + X) / (Total Matches + X), where X is the number of additional consecutive wins needed. Rearranging gives X = (Target WR x Total Matches - Current Wins) / (1 - Target WR). This formula assumes every additional game is a win, giving the minimum number of consecutive wins needed. In reality, maintaining a perfect win streak is extremely difficult in ranked play due to team composition, matchmaking algorithms, and opponent skill variance. A more practical approach is to target a session win rate higher than your target overall — if you want 60% overall, aim for 65-70% in each session to gradually pull the average up. The formula also shows why high-match-count heroes are harder to improve: a hero with 100 matches moves 0.5% per win, while a hero with 1,000 matches moves only 0.05% per win — ten times slower.",
  exampleCalculation: "Example 1: 500 total matches, 280 wins. Current WR = 56%. To reach 60%: X = (0.60 x 500 - 280) / (1 - 0.60) = (300 - 280) / 0.40 = 50 consecutive wins. Example 2: 1,000 matches, 480 wins. Current WR = 48%. To reach 55%: X = (550 - 480) / 0.45 = 155.6, so 156 consecutive wins needed. Example 3: 200 matches, 130 wins. Current WR = 65%. To reach 70%: X = (140 - 130) / 0.30 = 33 wins. Example 4: Hero-specific — Layla with 300 matches, 150 wins (50%). To reach 55%: 33 consecutive wins. To reach 60%: 75 consecutive wins.",
  philippinesContext: "Mobile Legends: Bang Bang dominates the Philippine gaming landscape. It is the most downloaded mobile game, the most watched esport on Filipino social media, and a cultural phenomenon that transcends age and social class. The MPL Philippines (Mobile Legends Professional League) draws millions of viewers per season, with teams like Blacklist International achieving international recognition. Filipino players are known for their aggressive playstyle and innovative strategies. Win rate is deeply embedded in Filipino gaming culture — players use it to evaluate potential teammates in ranked games, and having a hero win rate below 50% often results in being asked to switch heroes during the draft phase. The game uses an MMR-based matchmaking system that pairs players of similar skill, which means maintaining a high win rate becomes progressively harder as you climb ranks. Most Mythic-rank players maintain overall win rates between 55-65%. Professional players in MPL typically have 65-75% win rates on their signature heroes. Understanding win rate mathematics helps Filipino players set realistic goals and avoid the frustration of expecting rapid improvement when the numbers make that nearly impossible without consistent high-level play.",
  faqs: [
    { question: "What is a good win rate in Mobile Legends?", answer: "Above 50% means you win more than you lose. 50-55% is average, 55-60% is above average, 60-65% is very good, and 65%+ is excellent. Professional MPL players typically maintain 65-75% on signature heroes. For ranked climbing, consistently maintaining above 55% will steadily increase your rank over time." },
    { question: "How is MLBB win rate calculated?", answer: "Win Rate = (Total Wins / Total Matches) x 100. If you played 400 matches and won 220, your win rate is 55%. Each game type (ranked, classic, brawl) has separate statistics. Your overall win rate combines all modes, while hero-specific win rates track performance per character." },
    { question: "How many wins do I need to increase my win rate by 1%?", answer: "It depends on your total matches. With 100 total matches, 1 win changes WR by about 0.5%. With 500 matches, 1 win changes WR by only 0.1%. With 1,000 matches, each win moves the needle by just 0.05%. This is why win rate improvement slows dramatically as you play more matches — the mathematical weight of each game decreases." },
    { question: "Can I reset my MLBB win rate?", answer: "You cannot reset overall statistics in MLBB. However, you can create a new account (smurf) for a fresh start. Some players use the hero mastery reset feature to hide low win rate heroes from their profile. The most sustainable approach is improving your gameplay rather than resetting — skills carry over to every match." },
    { question: "Why is my win rate dropping even though I feel like I am improving?", answer: "This happens because matchmaking places you against stronger opponents as your hidden MMR increases. The system is designed to push everyone toward a 50% win rate over time. Improvement shows up as climbing ranks while maintaining your win rate, not as a constantly increasing percentage. Plateauing at 52-55% in a higher rank means you are performing at that level." },
    { question: "Does classic mode affect ranked win rate?", answer: "No. MLBB tracks separate statistics for Ranked, Classic, Brawl, and other modes. Your ranked win rate only counts ranked games. However, your overall profile win rate combines all modes. Many players use classic mode to practice new heroes without risking their ranked statistics." },
    { question: "What win rate do I need to reach Mythic rank?", answer: "There is no minimum win rate requirement for Mythic. However, practically, you need to maintain above 50% in ranked to accumulate stars and reach Mythic. Most players who reach Mythic have ranked win rates between 55-65%. The key is consistency — even 52% win rate over 500 games produces enough stars to climb, though slowly." },
    { question: "How do Filipino pro players maintain high win rates?", answer: "MPL professionals train 8-12 hours daily, play with coordinated teams, master meta heroes, study opponent strategies, and optimize team compositions. They also tend to have fewer total matches on competition accounts, making each win more impactful on the percentage. Solo queue win rates for pros are typically lower than their team statistics." },
    { question: "Should I focus on win rate or rank?", answer: "Focus on rank. Win rate is a lagging indicator — it reflects past performance but does not determine future matchmaking. A 55% win rate in Mythic is more impressive than 70% in Grandmaster. Rank shows your current skill level while win rate shows your historical average. Improving gameplay quality naturally improves both over time." },
    { question: "How does MLBB matchmaking work?", answer: "MLBB uses a hidden MMR (Matchmaking Rating) system that considers your win rate, rank, recent performance, and hero proficiency. The system aims to create balanced 5v5 matches. This means as you win more, you face stronger opponents, naturally pushing your win rate toward 50%. The system also considers party size — full squad games are matched against other squads when possible." },
    { question: "What is the MVP win rate calculation?", answer: "MVP is awarded to the best-performing player in a match based on a scoring system that considers kills, assists, deaths, damage dealt, turret damage, and team fight participation. Getting MVP does not directly affect your win rate calculation — only the match outcome (win or loss) matters. However, consistent MVP performance correlates with higher win rates." },
    { question: "How many matches should I play before judging a hero win rate?", answer: "At least 50-100 matches provide a statistically meaningful sample. With fewer than 30 matches, win rate fluctuates wildly — going 3-0 gives 100% WR, but 3-7 drops to 30%. After 100 matches, each game changes WR by about 0.5%, giving a stable and reliable indicator of your true performance with that hero." },
  ]
});

upgrade("electricity-bill-calculator-philippines", {
  description: "Estimate your monthly electricity bill based on kilowatt-hour (kWh) consumption and per-kWh rate in the Philippines. This tool is especially useful for Meralco customers and households served by other distribution utilities like VECO, CENECO, MORE Power, and BATELEC. Electricity costs are one of the largest recurring household expenses for Filipino families, and understanding how your bill is computed empowers you to identify energy-saving opportunities and budget more accurately. Many consumers are surprised by their electricity bills because they do not understand the relationship between appliance wattage, usage hours, and the resulting kWh consumption. A 1,000-watt air conditioner running 8 hours daily consumes 8 kWh per day or 240 kWh per month — which at a rate of 11.50 pesos per kWh adds roughly 2,760 pesos to your bill from that single appliance. This calculator gives you a quick estimate based on total consumption and rate, helping you identify whether your bill aligns with your usage patterns. If the estimated amount differs significantly from your actual bill, it may indicate meter reading errors, appliance inefficiency, or unauthorized connections that warrant investigation.",
  formulaExplanation: "The basic electricity bill formula is: Bill = kWh Consumption x Rate per kWh. However, actual Meralco and utility bills include multiple charge components: Generation Charge (the largest at 50-60% of the bill, covering the cost of power plants), Transmission Charge (8-10%, for NGCP high-voltage transmission), Distribution Charge (15-20%, the utility company operating cost), Supply Charge (fixed monthly fee), Metering Charge (meter maintenance), System Loss Charge (technical and non-technical losses in the grid), Lifeline Subsidy (discount for low-consumption households under 100 kWh), Universal Charges (missionary electrification, environmental fund), and Government Taxes (VAT, local franchise tax). The per-kWh rate published by utilities like Meralco is the all-in rate combining all these components. When Meralco announces rate changes, they typically refer to the generation charge component, which fluctuates monthly based on the Wholesale Electricity Spot Market (WESM) prices, bilateral contract rates, and Power Supply Agreements (PSA). Understanding these components helps consumers identify which parts of their bill are fixed versus variable.",
  exampleCalculation: "Example 1: 200 kWh at 11.50 per kWh = 2,300 pesos estimated bill. Example 2: 350 kWh at 11.50 = 4,025 pesos. Example 3: 100 kWh qualifies for Meralco lifeline rate (lower rate for low-consumption households), estimated at around 800-900 pesos. Example 4: A household with: 2 AC units (8 hrs/day each at 1,000W = 480 kWh), refrigerator (24 hrs at 150W = 108 kWh), TV and electronics (100 kWh), lights (50 kWh), washing machine and others (30 kWh). Total = 768 kWh at 11.50 = 8,832 pesos. Example 5: Comparing inverter vs non-inverter AC — inverter AC uses 40% less power. For 8 hrs daily: non-inverter = 240 kWh (2,760 pesos), inverter = 144 kWh (1,656 pesos). Monthly savings = 1,104 pesos.",
  philippinesContext: "The Philippines has among the highest electricity rates in Asia, with Meralco residential rates typically ranging from 10 to 13 pesos per kWh depending on generation charge fluctuations. Meralco serves Metro Manila, Bulacan, Cavite, Laguna, Batangas, Rizal, and parts of Pampanga and Quezon, covering approximately 7.4 million customers. Other major utilities include Visayan Electric (VECO) in Cebu, MORE Power in Iloilo, CENECO in Negros, and various electric cooperatives in rural areas. The Energy Regulatory Commission (ERC) regulates distribution utilities and approves rate adjustments. Meralco publishes its rate schedule monthly, with generation charge being the most volatile component. The Philippine government provides a lifeline subsidy for households consuming 100 kWh or less per month, giving them a discounted rate. Net metering is available for solar panel owners under the Renewable Energy Act (RA 9513), allowing excess solar generation to offset future bills. The DOE promotes energy efficiency through the Philippine Energy Labeling Program, requiring appliance energy efficiency labels on ACs, refrigerators, and lighting. Consumers can reduce bills by switching to inverter-type appliances, LED lighting, and implementing energy-saving habits like unplugging unused devices and setting AC to 25 degrees Celsius as recommended by DOE.",
  faqs: [
    { question: "How is Meralco bill computed?", answer: "Meralco bills include: Generation Charge (largest, 50-60%), Transmission Charge (NGCP fees), Distribution Charge (Meralco operating cost), Supply Charge, Metering Charge, System Loss, Universal Charges, and taxes including 12% VAT. The all-in rate is approximately 10-13 pesos per kWh. Your bill = total kWh consumed multiplied by this all-in rate, adjusted for lifeline subsidy if applicable." },
    { question: "What is the average electricity consumption in the Philippines?", answer: "A typical Filipino household uses 150-300 kWh per month. Low-income households average 80-120 kWh, middle-income 200-400 kWh, and air-conditioned homes 400-800 kWh. National average residential consumption is approximately 200 kWh. Consumption varies significantly based on climate (hotter months increase AC usage), household size, and appliance efficiency." },
    { question: "Why is Philippine electricity so expensive?", answer: "Several factors: heavy dependence on imported fuel (coal, LNG), transmission losses across the island archipelago, the EPIRA law allowing market-based pricing, limited domestic energy production, and the cost structure of distribution utilities. The Philippines ranks among the top 3 most expensive electricity markets in Asia, behind Japan and Singapore in some comparisons." },
    { question: "What is the Meralco lifeline rate?", answer: "Households consuming 100 kWh or less per month qualify for the lifeline subsidy, receiving a discounted rate approximately 40-50% lower than the standard residential rate. The subsidy is funded by non-lifeline customers through a cross-subsidy component. This program helps low-income Filipino families afford basic electricity for lighting, fans, and essential appliances." },
    { question: "How can I reduce my electricity bill?", answer: "Top strategies: switch to inverter-type AC and refrigerator (saves 30-50%), use LED bulbs (saves 80% vs incandescent), set AC to 25 degrees Celsius (each degree lower adds 6-8% to cooling cost), unplug devices when not in use (phantom load consumes 5-10% of household electricity), and run washing machines and irons during off-peak hours. Solar panels with net metering provide long-term savings." },
    { question: "How much electricity does an air conditioner use?", answer: "A 1HP window-type AC uses approximately 900-1,000 watts. Running 8 hours daily for 30 days = 240 kWh = approximately 2,760 pesos at 11.50 per kWh. A 1HP inverter split-type uses 500-700 watts, consuming only 144-168 kWh monthly (1,656-1,932 pesos). The inverter premium pays for itself in 12-18 months through electricity savings." },
    { question: "What is net metering for solar panels?", answer: "Under RA 9513, solar panel owners can export excess electricity to the grid and receive credits on their Meralco bill. The credit rate equals the blended generation charge (approximately 5-7 pesos per kWh). A 3kW solar system producing 300 kWh monthly can offset 1,500-2,100 pesos from your bill. Net metering application is processed through your distribution utility." },
    { question: "How do I read my Meralco electric meter?", answer: "For digital meters, read the display directly in kWh. For analog meters, read the 4-5 dials from left to right, recording the lower number when the pointer is between two digits. Your consumption = current reading minus previous reading. Meralco now uses Advanced Metering Infrastructure (AMI) smart meters that transmit readings automatically, reducing estimation errors." },
    { question: "Why is my bill higher than the calculator estimate?", answer: "Possible reasons: the per-kWh rate used is lower than your actual all-in rate, your actual consumption is higher than estimated (check appliance usage), system loss charges add 8-10% above the base rate, VAT adds 12%, or there may be a meter reading adjustment from a previous month. Compare your actual kWh reading with the bill statement." },
    { question: "What appliances consume the most electricity?", answer: "Top consumers in Filipino homes: air conditioner (30-50% of bill), electric water heater (10-15%), refrigerator (10-15%), clothes iron (5-10%), and electric stove or rice cooker (5-8%). Fans, lights, and electronics typically consume 10-20% combined. Identifying your top 3 energy consumers and optimizing their use produces the largest bill reductions." },
    { question: "Can I complain about high electricity bills to ERC?", answer: "Yes. File complaints about billing disputes, meter accuracy, or service quality with the Energy Regulatory Commission (ERC). Contact ERC Consumer Welfare and Advocacy Division at (02) 8689-5372. You can also file complaints directly with your distribution utility first. Meralco has a dedicated customer service hotline at 16211 for billing inquiries and dispute resolution." },
    { question: "What is the WESM and how does it affect my bill?", answer: "WESM (Wholesale Electricity Spot Market) is where power generators sell electricity at market prices. When WESM prices spike (due to plant shutdowns, high demand, or fuel price increases), the generation charge component of your bill increases. Meralco sources approximately 10-15% of its supply from WESM. The rest comes from bilateral contracts with fixed or semi-fixed pricing." },
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 5 complete');
