import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, (_, g1, g2, g3) => g1 + data.description + g3);
  
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, (_, g1, g2, g3) => g1 + data.formulaExplanation + g3);
  
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, (_, g1, g2, g3) => g1 + data.exampleCalculation + g3);
  
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, (_, g1, g2, g3) => g1 + data.philippinesContext + g3);
  
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, (_, g1, g2) => g1 + '\n' + faqStr + ',\n    ' + g2);
  console.log(`Upgraded: ${slug}`);
}

upgrade("lilith-sign-calculator", {
  description: "Uncover your deepest, darkest, and most repressed desires with the Black Moon Lilith Calculator. In modern psychological astrology, Lilith is not a physical planet, but rather a mathematically calculated point in space that represents the shadow self, untamed feminine energy, and primal sexuality. According to ancient mythology, Lilith was Adam's first wife who refused to submit to him and was subsequently banished from the Garden of Eden. Astrologically, wherever Lilith falls in your natal chart indicates where you refuse to compromise, where you feel deeply misunderstood, and where you harbor intense, often taboo desires that society forces you to suppress. Discovering your Lilith sign is crucial for intense shadow work and personal liberation. It reveals the source of your deepest subconscious rage and your most magnetic, raw power. This calculator precisely determines the zodiac sign and the specific astrological 'house' your Lilith occupies, providing a profound roadmap for integrating your dark side and reclaiming your personal autonomy without shame or guilt. By understanding this volatile placement, you can transform destructive behavioral patterns into fierce, unapologetic self-empowerment.",
  formulaExplanation: "Calculating Black Moon Lilith is highly complex because it is not a physical celestial body; it is a mathematical abstraction relating to the Moon's elliptical orbit around the Earth. The Moon's orbit is an oval, meaning it has two focal points. The Earth occupies one focal point. The other focal point is entirely empty space—this empty point is exactly what astrologers calculate as 'Black Moon Lilith'. Because the Moon's orbit constantly shifts, calculating this empty focal point requires advanced astronomical ephemeris data to determine its exact degree on the 360-degree zodiac wheel at your precise time of birth. Furthermore, there are two distinct ways to calculate Lilith: the 'Mean' Lilith (which calculates a smooth, averaged orbit path) and the 'True' Lilith (which calculates the highly erratic, actual wobbly path of the orbit). This calculator utilizes the precise geocentric algorithms required to plot the True Lilith, cross-referencing your birth date, exact birth time, and geographic coordinates to pinpoint exactly which zodiac constellation and astrological house this shadow point occupied when you were born.",
  exampleCalculation: "Example 1 (Lilith in Scorpio): You calculate your chart and discover your Black Moon Lilith is in Scorpio. Scorpio is the sign of intensity, death, and rebirth. This placement suggests your 'shadow self' struggles with extreme jealousy, possessiveness, and a fear of betrayal, but also possesses immense, almost hypnotic sexual magnetism and psychological resilience. Example 2 (Lilith in Taurus in the 2nd House): If Lilith is in Taurus, the shadow self is fixated on materialism and bodily pleasure. If it falls in the 2nd House (the house of personal finances), this indicates a deep-seated, perhaps irrational fear of poverty or a tendency to hoard wealth, combined with an intense, rebellious desire to attain financial independence entirely on your own terms. Example 3 (The Impact of True vs Mean): The 'Mean' calculation might place your Lilith at 29 degrees Leo, while the 'True' (wobbly) calculation places it at 1 degree Virgo. The calculator provides the exact degree to prevent this massive misinterpretation of your shadow archetype.",
  philippinesContext: "In the deeply conservative, predominantly Catholic culture of the Philippines, discussions surrounding sexuality, female empowerment, and psychological 'darkness' are often heavily stigmatized. The concept of 'Lilith'—a mythological figure who explicitly rejected patriarchal submission—resonates powerfully with the growing feminist movement among Filipina youth and the local LGBTQ+ community. As younger generations in Metro Manila and Cebu move away from traditional religious dogma and explore psychological astrology, understanding the 'shadow self' has become a popular method of radical self-acceptance. Local tarot readers and esoteric content creators on platforms like TikTok heavily emphasize 'shadow work' to heal from generational trauma and societal expectations (like the pressure on Filipinas to be endlessly accommodating and demure). This calculator serves as a digital tool for this exact cultural shift, allowing Filipino users to privately map out their repressed energies and confront the specific societal conditioning that has forced them to hide their most authentic, unapologetic selves.",
  faqs: [
    { question: "What exactly is Black Moon Lilith?", answer: "Black Moon Lilith is not a planet or an asteroid. It is a mathematical point in space representing the empty focal point of the Moon's elliptical orbit around the Earth. Astrologically, it symbolizes your repressed shadow self, primal desires, and fierce independence." },
    { question: "Is Lilith an evil placement?", answer: "No placement in astrology is inherently 'evil'. Lilith represents the taboo, the rejected, and the wild aspects of our psyche. While it can manifest as destructive rage or obsession if ignored, integrating your Lilith energy leads to profound empowerment and authenticity." },
    { question: "Why do I need my exact birth time for this?", answer: "While the zodiac sign of your Lilith changes relatively slowly (spending about 9 months in a sign), the astrological 'House' it occupies changes every two hours. You need your exact birth time to know which specific area of your life (e.g., career, marriage) your shadow self impacts." },
    { question: "What is the difference between Mean Lilith and True Lilith?", answer: "The Moon's orbit is highly erratic. 'Mean' Lilith calculates an averaged, smooth orbital path. 'True' (or Osculating) Lilith calculates the actual, wobbly, real-time position. Most modern psychological astrologers prefer the precision of True Lilith, which this calculator uses." },
    { question: "What does Lilith in Aries mean?", answer: "Lilith in Aries indicates a shadow self that struggles with extreme anger, impulsivity, and a fear of being controlled. It manifests as a fierce, highly competitive drive for absolute independence and a refusal to back down from any conflict." },
    { question: "What does Lilith in Gemini mean?", answer: "Lilith in Gemini points to a shadow self that feels misunderstood intellectually. There may be a tendency toward manipulative communication, gossip, or a deep fear of being silenced. Their raw power lies in their sharp, cutting intellect." },
    { question: "What does Lilith in the 7th House mean?", answer: "The 7th House rules marriage and partnerships. Lilith here suggests intense, dramatic, and often power-struggle-laden romantic relationships. The person may attract highly controlling partners or rebel fiercely against traditional marriage structures." },
    { question: "How does Lilith affect my love life?", answer: "Lilith governs our raw, unfiltered sexuality and what we find taboo but deeply attractive. It often points to karmic, intense sexual connections that challenge societal norms, unlike Venus, which simply governs what we find romantic or beautiful." },
    { question: "Is Lilith only relevant for women?", answer: "No. While Lilith represents the 'dark feminine' archetype in mythology, everyone has a Lilith placement in their chart regardless of gender. For men, it often represents the type of untamed feminine energy they fear or are magnetically drawn to, as well as their own repressed independence." },
    { question: "How do I do 'shadow work' with my Lilith sign?", answer: "Shadow work involves consciously acknowledging the dark traits your Lilith sign represents (e.g., jealousy, greed, manipulation) rather than suppressing them. By accepting these traits exist within you, you stop projecting them onto others and learn to channel that intense energy constructively." },
    { question: "Does Lilith represent my past lives?", answer: "Some karmic astrologers believe Lilith points to areas where you were persecuted, silenced, or shamed in past incarnations. In your current life, your Lilith placement shows where you must reclaim the power that was taken from you." },
    { question: "How often does Lilith change signs?", answer: "Black Moon Lilith takes approximately 8 years and 10 months to complete a full orbit through all 12 zodiac signs. This means it spends roughly 9 months in each specific zodiac sign." }
  ]
});

upgrade("chiron-sign-calculator", {
  description: "Identify your deepest psychological wounds and your path to spiritual healing with the Chiron Sign Calculator. In astrology, Chiron is known as the 'Wounded Healer'. It is a minor planet (or comet) located between Saturn and Uranus. Mythologically, Chiron was a wise centaur who was a master healer, yet suffered an incurable wound himself. Astrologically, the placement of Chiron in your natal chart pinpoints the exact area of your life where you feel a profound, seemingly unhealable sense of inadequacy, rejection, or trauma. This is not a superficial flaw; it is a core soul wound that you carry throughout your life. However, Chiron also represents your greatest spiritual gift. The paradox of Chiron is that the area where you are most broken is exactly the area where you possess the most profound capacity to heal others. By using this calculator to find the zodiac sign and specific astrological house of your Chiron, you can stop fighting your deepest insecurities. Instead, you gain the precise astrological roadmap required to turn your greatest vulnerability into your most powerful source of empathy, wisdom, and transformative teaching.",
  formulaExplanation: "Calculating Chiron's position is a specialized astronomical task due to its highly unusual, erratic orbit. Discovered relatively recently in 1977, Chiron's orbit is highly elliptical (oval-shaped) and deeply skewed. Because of this extreme elliptical path, Chiron does not spend an equal amount of time in each zodiac sign. For example, it rushes through Libra in just 1.5 years, but it plods slowly through Aries, spending over 8 years there. This means that calculating its exact position requires highly complex, non-linear ephemeris algorithms to track its location on the 360-degree ecliptic at the exact moment of your birth. The calculator takes your birth date, time, and geographical coordinates, and queries a massive astronomical database to pinpoint Chiron's degree. Knowing the exact degree is vital, because if Chiron is situated right on the cusp between two signs (e.g., 29 degrees Pisces or 0 degrees Aries), a slight miscalculation will give you the completely wrong spiritual diagnosis.",
  exampleCalculation: "Example 1 (Chiron in Leo): You calculate your chart and find Chiron in Leo. Leo rules self-expression, creativity, and the need to be seen. A Chiron wound here indicates a deep childhood trauma of feeling invisible, unappreciated, or that your natural talents were mocked. Your healing journey involves validating your own creativity without needing external applause, ultimately allowing you to become a powerful mentor who helps others find their spotlight. Example 2 (Chiron in the 4th House): The 4th house rules home, family, and the mother figure. Chiron here points to a deep wound stemming from your childhood home environment—perhaps a fractured family, an emotionally unavailable parent, or a constant feeling of not 'belonging' anywhere. Example 3 (The Healing Paradox): You have Chiron in Gemini (communication). You may have grown up with a severe stutter or feeling that you were unintelligent. As you heal, you develop such a profound understanding of communication struggles that you become an incredibly effective speech therapist or a writer who gives a voice to the voiceless.",
  philippinesContext: "In the Philippines, the cultural concepts of 'Hiya' (shame/loss of face) and 'Utang na Loob' (debt of gratitude) often create profound, unspoken psychological burdens within the family dynamic. Many Filipinos carry deep-seated generational trauma related to strict parental expectations, the pressure to financially support the extended family, or the emotional toll of having parents work abroad as OFWs (Overseas Filipino Workers). Because seeking professional psychotherapy is still highly stigmatized and prohibitively expensive for many in the country, the younger generation is increasingly turning to psychological astrology as an alternative framework for processing their emotional pain. The concept of Chiron—identifying a specific, valid 'wound' that isn't their fault—provides immense relief. Local astrology groups frequently use Chiron placements to discuss how to heal from the specific societal pressures unique to the Filipino experience, turning private, shameful insecurities into shared, community-healing discussions.",
  faqs: [
    { question: "What is Chiron in astrology?", answer: "Chiron is an asteroid/comet located between Saturn and Uranus. It is known as the 'Wounded Healer'. Its placement in your natal chart indicates your deepest psychological wound or trauma, but also the area where you possess the greatest ability to heal and guide others." },
    { question: "Is Chiron a planet?", answer: "Astronomically, Chiron is classified as a 'Centaur'—a minor planet or comet with an unstable orbit. Astrologically, it is treated with the same weight as major planets when analyzing psychological trauma and spiritual growth." },
    { question: "What does it mean to be the 'Wounded Healer'?", answer: "The paradox of Chiron is that you often cannot completely 'cure' your own Chiron wound. However, because you understand that specific pain so deeply, you become a master at helping other people heal from that exact same trauma." },
    { question: "Why does my Chiron sign feel more accurate than my Sun sign?", answer: "Your Sun sign is your basic ego, but Chiron targets your deepest, most hidden insecurities. When people first discover their Chiron placement, it often triggers a profound 'aha!' moment because it validates a secret pain they have carried their entire lives." },
    { question: "What does Chiron in Aries mean?", answer: "Aries rules the self and personal identity. A Chiron wound here indicates a deep-seated feeling of worthlessness or feeling like you don't have the right to exist or assert yourself. Healing involves fiercely claiming your own identity and teaching others self-advocacy." },
    { question: "What does Chiron in Cancer mean?", answer: "Cancer rules the mother, nurturing, and emotional security. A Chiron wound here points to a profound feeling of being unloved, abandoned, or emotionally starved during childhood. The healing journey involves learning to aggressively nurture and parent yourself." },
    { question: "What does Chiron in the 10th House mean?", answer: "The 10th House rules career, public reputation, and the father figure. Chiron here suggests a deep fear of failure, feeling like an imposter in your career, or trauma related to authority figures. You heal by defining success on your own terms, not society's." },
    { question: "How long does Chiron stay in one sign?", answer: "Because of its highly elliptical orbit, Chiron's speed varies wildly. It can spend less than 2 years in Libra, but over 8 years in Aries. It takes approximately 50 years to complete a full orbit around the zodiac." },
    { question: "What is the 'Chiron Return'?", answer: "Your Chiron Return happens around age 50, when Chiron returns to the exact degree it was at when you were born. It is a major astrological milestone marking a profound mid-life spiritual reckoning, where you are forced to finally confront and integrate your core wounds." },
    { question: "Can a Chiron wound be completely healed?", answer: "Most psychological astrologers believe the Chiron wound is never 100% erased; it leaves a scar. Healing means the wound no longer controls your subconscious behavior or causes you toxic pain, but instead serves as a source of deep empathy and wisdom." },
    { question: "Do I need my exact birth time for this calculator?", answer: "To know the exact astrological 'House' your Chiron is in (which tells you the specific area of life the wound affects), you absolutely need your exact birth time. Without it, you can only calculate the zodiac sign of the wound." },
    { question: "How does Chiron interact with my other planets?", answer: "If Chiron is situated very close to a major planet in your chart (e.g., conjunct your Moon), it significantly amplifies the wound. A Chiron-Moon conjunction means your core trauma is deeply tied to your emotional processing and relationship with maternal figures." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 16b complete');
