import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function addToField(slug: string, field: string, extra: string) {
  const marker = `slug: "${slug}"`;
  const idx = c.indexOf(marker);
  if (idx === -1) return;
  const chunk = c.substring(idx, idx + 12000);
  const re = new RegExp(field + ': "([^"]*)"');
  const m = chunk.match(re);
  if (!m) return;
  c = c.replace(m[0], m[0].slice(0,-1) + " " + extra + '"');
}

addToField("psbank-car-loan-calculator", "description", "Beyond simply estimating payments, this calculator acts as a safeguard against predatory lending tactics sometimes employed by secondary financing companies. By understanding the standard bank rates and seeing the math laid out clearly, consumers are better equipped to challenge excessive hidden fees or balloon payments that are not immediately apparent on the showroom floor. Using this tool before visiting a dealership allows you to set a firm boundary on your monthly budget, ensuring that the excitement of buying a new vehicle does not lead to years of financial strain. Ultimately, an informed buyer is a bank's best client and their own best financial advocate. Always remember that the sticker price of the car is just the starting point of your financial commitment.");
addToField("psbank-car-loan-calculator", "philippinesContext", "Furthermore, the Metro Manila traffic crisis and the push for modernized public utility vehicles have slightly shifted auto lending dynamics. While traditional sedans remain popular, there is a growing trend of financing subcompact SUVs and hybrid vehicles. Banks occasionally offer preferential, lower interest rates for eco-friendly or hybrid vehicles as part of sustainable financing initiatives. Keeping a clean credit record is paramount; a single default on a credit card or a delayed personal loan payment recorded in the CIC database can cause the bank to either reject an auto loan outright or demand a significantly higher down payment to mitigate their perceived risk. It is a harsh reality that your past financial behavior directly dictates the cost of your future borrowing.");

addToField("psslai-loan-calculator", "description", "The importance of this calculator extends beyond mere budgeting; it serves as a crucial tool for long-term career management for uniformed personnel. Financial distress is a leading cause of administrative cases and disciplinary actions within the armed services. When personnel overextend themselves financially, relying on '5-6' lenders to cover deficits caused by massive salary deductions, it compromises their focus and integrity. By using this calculator to accurately project net proceeds and monthly obligations, borrowers can make mature, sustainable financial choices. It prevents the dangerous cycle of borrowing to pay off existing debt, ensuring that the men and women who serve the public are themselves financially secure and capable of providing for their families without undue stress.");
addToField("psslai-loan-calculator", "philippinesContext", "The overarching policy of the government is to ensure the dignity and financial solvency of its uniformed forces. In previous decades, the lack of strict lending regulations led to widespread financial ruin among junior officers, a systemic issue that the 'net take-home pay' rule directly addresses. PSSLAI works in tandem with the government to enforce these rules, acting as a responsible lending partner rather than a predatory entity. The high annual dividends paid out by PSSLAI on Capital Contributions (often exceeding 10% per annum) also act as an incredible wealth-building tool, meaning the relationship between the borrower and the association is mutually beneficial. Proper utilization of this calculator allows members to maximize their borrowing power while simultaneously protecting their dividend-earning potential.");

addToField("rcbc-car-loan-calculator", "description", "Beyond simply estimating payments, this calculator acts as a safeguard against predatory lending tactics sometimes employed by secondary financing companies. By understanding the standard bank rates and seeing the math laid out clearly, consumers are better equipped to challenge excessive hidden fees or balloon payments that are not immediately apparent on the showroom floor. Using this tool before visiting a dealership allows you to set a firm boundary on your monthly budget, ensuring that the excitement of buying a new vehicle does not lead to years of financial strain. Ultimately, an informed buyer is a bank's best client and their own best financial advocate. Always remember that the sticker price of the car is just the starting point of your financial commitment.");
addToField("rcbc-car-loan-calculator", "philippinesContext", "Furthermore, the Metro Manila traffic crisis and the push for modernized public utility vehicles have slightly shifted auto lending dynamics. While traditional sedans remain popular, there is a growing trend of financing subcompact SUVs and hybrid vehicles. Banks occasionally offer preferential, lower interest rates for eco-friendly or hybrid vehicles as part of sustainable financing initiatives. Keeping a clean credit record is paramount; a single default on a credit card or a delayed personal loan payment recorded in the CIC database can cause the bank to either reject an auto loan outright or demand a significantly higher down payment to mitigate their perceived risk. It is a harsh reality that your past financial behavior directly dictates the cost of your future borrowing.");

fs.writeFileSync(file, c);
console.log('Boost batch 12 done');
