import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("raosoft-sample-size-calculator", {
  description: "Determine the statistically valid sample size for your research study using this Raosoft-style Sample Size Calculator. Whether you are conducting a university thesis, a nationwide political poll, or a corporate customer satisfaction survey, interviewing every single person in your target population is usually impossible due to time and budget constraints. This calculator helps you determine exactly how many people you need to survey to ensure your results accurately reflect the views of the entire population. By defining your acceptable margin of error (e.g., 5%), your desired confidence level (typically 95%), and the total population size, the tool computes the minimum number of respondents required. This ensures that your research findings are mathematically defensible and not just anecdotal. Using an inadequate sample size renders your data invalid, as the results could merely be due to chance. Conversely, surveying too many people wastes valuable resources. This tool strikes the perfect balance, providing the golden number needed for robust, peer-reviewed, and actionable research.",
  formulaExplanation: "The calculator uses the standard statistical formula for sample size: n = [Z^2 * p * (1-p)] / E^2, where 'Z' is the Z-score derived from your chosen confidence level (1.96 for 95% confidence), 'p' is the estimated response distribution (usually kept at 0.5 or 50% to yield the most conservative, largest sample size), and 'E' is the margin of error expressed as a decimal (e.g., 0.05 for 5%). This formula provides the sample size for an infinitely large population. If your actual population size (N) is known and is relatively small, a 'Finite Population Correction' (FPC) is applied: Adjusted Sample Size = [n * N] / [n + (N - 1)]. This correction reduces the required sample size because when surveying a large fraction of a small population, you gain more information per respondent. A 5% margin of error means that if your survey shows 60% of people prefer Brand A, you can be confident the true population preference is between 55% and 65%.",
  exampleCalculation: "Example 1 (Large Population): You are surveying university students in Metro Manila (Population ~500,000). You want a 95% confidence level (Z=1.96) and a 5% margin of error (E=0.05), with a response distribution of 50% (p=0.5). Initial n = [1.96^2 * 0.5 * 0.5] / 0.05^2 = [3.8416 * 0.25] / 0.0025 = 0.9604 / 0.0025 = 384.16. Since 500,000 is very large, the FPC doesn't change it much. The required sample size is 385 respondents. Example 2 (Small Population): You are surveying employees in a specific company branch (Population = 300). Same 95% confidence and 5% margin of error. Initial n = 384. Applying the FPC: Adjusted n = [384 * 300] / [384 + (300 - 1)] = 115200 / 683 = 168.6. You only need to survey 169 employees to get statistically significant results for that branch. The calculator handles these complex statistical adjustments instantly.",
  philippinesContext: "In the Philippine academic and political landscape, accurate sampling is paramount. For undergraduate and graduate students writing their theses in institutions like UP, DLSU, Ateneo, or state universities, research advisers and panel members strictly scrutinize the sampling methodology. The phrase 'computed via Raosoft' is a standard fixture in Philippine methodology chapters to justify the respondent count. If a student arbitrarily chooses to survey 50 people when the formula dictates 350, the defense panel will reject the study's conclusions as statistically insignificant. Outside academia, organizations like Social Weather Stations (SWS) and Pulse Asia rely on these exact statistical principles for their national surveys. A typical nationwide political survey in the Philippines uses a sample size of 1,200 respondents, which mathematically yields a +/- 3% margin of error at a 95% confidence level, accurately reflecting the sentiments of over 60 million registered Filipino voters. This calculator brings that same level of professional statistical rigor to everyday student and corporate research.",
  faqs: [
    { question: "What is the Margin of Error?", answer: "The margin of error indicates how much you expect your survey results to reflect the views of the overall population. A 5% margin of error means if your survey finds that 70% of respondents like a product, you can be confident that between 65% and 75% of the entire population actually likes it." },
    { question: "What is the Confidence Level?", answer: "The confidence level tells you how sure you can be that the true population value lies within your margin of error. A 95% confidence level means that if you repeated the survey 100 times, the results would fall within your margin of error 95 times. 95% is the academic standard." },
    { question: "What should I put for Population Size?", answer: "The population size is the total number of people in the group you are trying to study. If you are studying all enrolled students in a specific college, put that exact enrollment number. If your population is massive (like all adults in the Philippines), you can leave it blank or put 100,000+; the math won't change much." },
    { question: "What is the Response Distribution?", answer: "This is the expected variance in responses. If you don't know what the results will be, leave it at 50% (0.5). Using 50% is the most conservative approach because it maximizes the variance in the formula, giving you the largest and safest recommended sample size." },
    { question: "Why is my required sample size 385?", answer: "385 is the 'magic number' in statistics. For any large population (over 100,000), a 95% confidence level with a 5% margin of error and a 50% distribution will always mathematically yield a required sample size of approximately 384 or 385. It represents the point of diminishing returns in sampling." },
    { question: "Can I use a 10% margin of error to lower my sample size?", answer: "Yes, increasing your margin of error to 10% will drastically reduce the required sample size (from ~385 down to ~96 for large populations). However, most academic advisers and peer-reviewed journals will reject a 10% margin of error as being too imprecise. 5% is the generally accepted maximum." },
    { question: "What if I can't reach the required sample size?", answer: "If you cannot reach the calculated sample size due to budget or time limits, you must report this as a 'limitation of the study' in your research paper. You will also have to recalculate and report a higher margin of error based on the actual number of respondents you successfully surveyed." },
    { question: "Is this calculator accepted in Philippine thesis defenses?", answer: "Yes. The math used here is identical to the standard statistical formulas taught in Philippine research methodology classes and used by the original Raosoft tool. As long as you cite the formula correctly in your paper, panels at UP, Ateneo, UST, and others will accept the computation." },
    { question: "How do Pulse Asia and SWS survey the whole Philippines with only 1,200 people?", answer: "Statistics is based on probability. A sample of 1,200 randomly selected people provides a +/- 3% margin of error at a 95% confidence level, regardless of whether the population is 1 million or 100 million. The key to their accuracy is ensuring the 1,200 people are a truly random, representative mix of demographics." },
    { question: "Does a bigger population always mean I need a much bigger sample?", answer: "No. Once a population exceeds 50,000 to 100,000, the required sample size plateaus. Whether your population is 100,000 or 100 million, the required sample size for a 5% margin of error remains right around 385. This is the power of statistical sampling." },
    { question: "What is the Finite Population Correction (FPC)?", answer: "The FPC is a mathematical adjustment applied when your sample size is a large fraction (typically more than 5%) of your total population. It reduces the required sample size because you are sampling such a large chunk of the group that there is less room for statistical error." },
    { question: "How do I deal with non-responses?", answer: "The calculator gives you the number of COMPLETED surveys needed. If you expect a low response rate (e.g., only 20% of people reply to emails), you must distribute the survey to a much larger group. To get 385 responses with a 20% response rate, you need to invite 1,925 people." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 10b complete');
