import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function addToField(slug: string, field: string, extra: string) {
  const marker = `slug: "${slug}"`;
  const idx = c.indexOf(marker);
  if (idx === -1) return;
  const chunk = c.substring(idx, idx + 12000);
  const re = new RegExp(field + ': "([^"]*)"');
  const m = chunk.match(re);
  if (!m) return;
  c = c.replace(m[0], m[0].slice(0,-1) + " " + extra + '"');
}

addToField("co-amoxiclav-pediatric-dose-calculator", "description", "Beyond preventing under-dosing and overdosing, precision in liquid antibiotic administration builds confidence for parents managing sick children at home, especially during middle-of-the-night fever spikes. Given the complex nature of the amoxicillin and clavulanate potassium combination, guessing the dose based on a child's age rather than weight is a dangerous practice that this tool explicitly aims to discourage. By empowering caregivers with exact mathematical conversions, we support better adherence to pediatric regimens and foster safer medication practices within the home.");
addToField("co-amoxiclav-pediatric-dose-calculator", "philippinesContext", "The economic reality in the Philippines often forces families to purchase medicine in tranches rather than buying the full prescribed course upfront. This practice, while understandable, severely undermines the efficacy of Co-Amoxiclav and accelerates the development of drug-resistant pathogens. The DOH's strict enforcement of the 'No Prescription, No Antibiotic' rule aims to curb this, yet challenges remain in rural areas. Public health initiatives strongly emphasize that antibiotics are not a cure for viral infections like the common cold or dengue fever; their use must be strictly limited to proven bacterial infections as diagnosed by a medical professional.");

addToField("pack-per-year-calculator", "description", "The calculation serves as a stark, numerical reflection of tobacco consumption, often acting as a powerful motivational catalyst for behavioral change. When individuals see a high pack-year number, the abstract concept of 'smoking damage' becomes a concrete, undeniable metric. This quantifiable data point is essential not just for personal awareness, but for initiating serious conversations with healthcare providers about smoking cessation aids, such as nicotine replacement therapy (NRT) or prescription medications like varenicline. Furthermore, understanding your pack-year index can influence life insurance premiums, as underwriters use this precise metric to calculate mortality risk. Ultimately, the pack-year calculator is a vital tool for preventative health management, transforming daily habits into a long-term risk assessment that cannot be ignored.");
addToField("pack-per-year-calculator", "philippinesContext", "The Philippine government has intensified its efforts to curb tobacco use through the implementation of graphic health warnings on cigarette packaging and the expansion of smoke-free public spaces under Executive Order No. 26. Despite these aggressive legislative measures and significant tax hikes, smoking remains deeply entrenched in certain socioeconomic demographics. The burden of smoking-related illnesses places immense strain on the Philippine Health Insurance Corporation (PhilHealth) and public hospital infrastructure. Recognizing this, local health units are increasingly integrating pack-year assessments into standard outpatient intake forms to identify high-risk individuals early. For the Filipino patient, knowing this number is becoming a prerequisite for accessing specialized pulmonary care and securing financial coverage for catastrophic illnesses related to tobacco use, highlighting the metric's critical role in both clinical treatment and healthcare economics.");

addToField("vo2-max-calculator", "description", "This metric transcends basic heart rate monitoring, offering a comprehensive view of how effectively your body's respiratory and cardiovascular systems collaborate to produce energy at the cellular level. By inputting accessible data such as resting heart rate or the results of a simple 1-mile walk test, users bypass the need for clinical environments, democratizing elite-level fitness tracking. For individuals recovering from sedentary lifestyles or managing weight loss programs, tracking VO2 Max provides a more encouraging and holistic measure of progress than the weighing scale alone. As your cardiovascular efficiency improves, tasks that once caused breathlessness become effortless. The calculator thus acts as both an assessment tool and a motivational benchmark, guiding users toward scientifically sound training intensities and promoting long-term cardiovascular resilience.");
addToField("vo2-max-calculator", "philippinesContext", "In response to the rising incidence of non-communicable diseases (NCDs) in the Philippines, public health advocates and corporate wellness programs are shifting focus from simple weight loss to overall cardiovascular fitness. The Department of Health's 'Pilipinas Go4Health' movement encourages regular physical activity to combat hypertension and diabetes. Consequently, understanding VO2 Max is gaining traction among Filipino urbanites, driving participation in community fun runs, weekend cycling events in places like Nuvali or Clark, and high-intensity gym classes. While specialized sports clinics in Metro Manila cater to competitive athletes seeking precise spirometry testing, the average Filipino relies on accessible estimation methods. Recognizing your VO2 Max score encourages a proactive approach to heart health, aligning personal fitness goals with national efforts to reduce the burden of lifestyle diseases on the public healthcare system.");

addToField("waist-to-hip-ratio-calculator", "description", "This ratio provides a critical dimension of health assessment that traditional weight measurements completely miss. By quantifying the disproportion between waist and hip circumferences, the tool directly highlights the presence of visceral adiposity—the metabolically active fat that wraps around the liver, pancreas, and intestines. This type of fat constantly releases inflammatory cytokines and free fatty acids into the portal vein, driving the pathogenesis of insulin resistance, dyslipidemia, and systemic inflammation. Therefore, the Waist-to-Hip Ratio is not merely a cosmetic indicator; it is a profound clinical warning sign. Monitoring this ratio empowers individuals to shift their focus from generalized weight loss to targeted metabolic health improvement, emphasizing the importance of nutritional quality and specific exercise modalities that effectively mobilize and burn dangerous intra-abdominal fat stores.");
addToField("waist-to-hip-ratio-calculator", "philippinesContext", "The Philippine context makes the Waist-to-Hip Ratio particularly crucial due to the genetic predisposition of many Southeast Asians to develop cardiometabolic complications at lower Body Mass Index (BMI) thresholds compared to Western populations. A Filipino might appear lean overall but harbor dangerous levels of visceral fat—a phenomenon exacerbated by a diet heavily reliant on white rice, sugary condiments, and highly processed fast food. The Food and Nutrition Research Institute (FNRI) continually warns about the rising rates of central obesity among Filipino adults. Consequently, local endocrinologists and preventive cardiologists heavily favor the WHR over BMI during routine physical exams. Public health initiatives are increasingly focused on educating the populace that a protruding belly is not a sign of prosperity, but a serious medical liability. Utilizing this calculator encourages early lifestyle interventions, reducing the impending burden of chronic metabolic diseases on the Philippine healthcare system.");

fs.writeFileSync(file, c);
console.log('Boost batch 9 done');
