import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function addToField(slug: string, field: string, extra: string) {
  const marker = `slug: "${slug}"`;
  const idx = c.indexOf(marker);
  if (idx === -1) return;
  const chunk = c.substring(idx, idx + 12000);
  const re = new RegExp(`(${field}: ")([^"]*)(")`);
  const m = chunk.match(re);
  if (!m) return;
  const replaced = chunk.replace(re, (_, g1, g2, g3) => g1 + g2 + " " + extra + g3);
  c = c.substring(0, idx) + replaced + c.substring(idx + 12000);
}

addToField("aquarium-gallon-calculator", "description", "Beyond simply knowing how much water fits in the glass, understanding your aquarium's exact volume is critical for maintaining water chemistry stability. A larger volume of water dilutes toxins (like ammonia from fish waste) much more effectively than a smaller volume. This is why experienced aquarists often recommend that beginners start with a 20-gallon or 29-gallon tank rather than a 5-gallon 'starter kit'. In a small volume, a slight overfeeding or a dead snail can cause a catastrophic ammonia spike within hours, killing everything in the tank. In a larger volume, that same mistake might barely register on a water test kit. Using this calculator helps you understand the 'forgiveness factor' of your chosen setup, allowing you to make informed decisions about your maintenance schedule, water change frequency, and overall bioload management.");
addToField("aquarium-gallon-calculator", "philippinesContext", "Furthermore, the frequent typhoons and resulting power outages (brownouts) in the Philippines pose a unique challenge for local fish keepers. When the power goes out, the filtration system stops, and oxygen levels in the water begin to drop rapidly. A tank with a larger water volume holds more dissolved oxygen and takes longer to become toxic, giving the hobbyist crucial extra hours to deploy battery-operated air pumps or manually aerate the water. Understanding your precise gallon capacity also helps when buying locally manufactured aquarium stands made of angle bars or tubular steel; a 50-gallon tank weighs over 400 pounds when filled, and knowing this exact weight derived from the volume calculation is essential to ensure the stand (and the floor beneath it) won't collapse under the immense pressure.");

addToField("bnb-to-php-calculator", "description", "Furthermore, as the crypto landscape evolves, BNB has transcended its original purpose as a mere discount token on the Binance centralized exchange. It now acts as the foundational layer for a massive ecosystem of decentralized applications (dApps), NFT marketplaces, and Web3 games. When you are interacting with these decentralized protocols, every single action—from swapping tokens to minting an NFT—requires a fraction of BNB to pay for network processing power (gas). Without an accurate, real-time fiat conversion tool, you might unknowingly authorize a transaction with an exorbitant network fee during times of high chain congestion. This calculator empowers users to translate these abstract, fractional cryptocurrency costs (e.g., 0.0015 BNB) into tangible Philippine Pesos, ensuring you maintain strict financial control over your Web3 interactions.");
addToField("bnb-to-php-calculator", "philippinesContext", "The integration of cryptocurrency into daily Filipino life is accelerating rapidly, moving beyond pure speculation into practical utility. Many overseas Filipino workers (OFWs) and freelance gig workers are increasingly opting to receive their salaries in stablecoins or major cryptocurrencies like BNB due to the significantly lower remittance fees compared to traditional banking channels like Western Union or MoneyGram. Upon receiving BNB, these workers rely on real-time calculators to determine the optimal moment to cash out to PHP via P2P networks, maximizing their take-home pay amidst fluctuating exchange rates. Additionally, the Philippine government's ongoing efforts to regulate Virtual Asset Service Providers (VASPs) mean that having a clear, accurate record of your crypto-to-fiat conversions is becoming increasingly important for legitimate tax filing and proving the source of funds to local banks, preventing sudden account closures or freezing of assets under Anti-Money Laundering (AML) regulations.");

addToField("excel-formula-age-calculator", "description", "Beyond simple age tracking, dynamic date calculation is the foundation of complex workforce analytics and predictive modeling. When an HR professional can instantly calculate the exact age and tenure of a 5,000-person workforce, they can begin forecasting critical business events. They can project exactly when a large cohort of senior management will reach retirement age, allowing the company to proactively initiate succession planning and leadership training programs years in advance. Similarly, in healthcare administration, calculating a patient's exact age down to the month and day is legally required for administering certain age-restricted vaccines or qualifying patients for specific government healthcare subsidies. By replacing manual math with these robust, error-free Excel formulas, organizations can transition from reactive record-keeping to proactive, data-driven strategic planning, saving countless hours of manual auditing.");
addToField("excel-formula-age-calculator", "philippinesContext", "In the highly competitive Philippine BPO (Business Process Outsourcing) industry, workforce metrics are tracked with extreme precision. Companies employing tens of thousands of call center agents must continuously monitor employee demographics to tailor their retention programs, benefits packages, and health insurance (HMO) premiums, which are heavily dependent on the average age of the workforce. Furthermore, strict adherence to Philippine Labor Code regulations regarding the employment of minors requires foolproof age verification systems. For civil servants, the Government Service Insurance System (GSIS) has highly specific age and tenure requirements for calculating pension benefits and loan eligibilities. Providing local administrators, HR managers, and government clerks with reliable, automated tools to handle these calculations minimizes bureaucratic delays, ensures compliance with national labor laws, and significantly improves the efficiency of both private enterprises and public sector services across the archipelago.");

addToField("dog-pregnancy-calculator", "description", "Furthermore, precise whelping date estimation is crucial for managing the nutritional and medical needs of the pregnant dam. During the final two weeks of gestation, the puppies undergo explosive growth, placing an immense metabolic burden on the mother. If an owner miscalculates the due date and fails to transition the dam to a high-calorie, calcium-rich diet in time, she may suffer from eclampsia (milk fever)—a life-threatening drop in blood calcium levels that causes tremors, seizures, and potentially death shortly after giving birth. Conversely, overfeeding too early in the pregnancy can lead to obesity, which drastically increases the risk of dystocia (difficult labor) due to excess fat in the birth canal. By providing a strict timeline based on the exact mating date, this calculator allows breeders to perfectly synchronize their nutritional management, ensuring the mother is in peak physical condition when labor finally begins.");
addToField("dog-pregnancy-calculator", "philippinesContext", "In the Philippines, the risk of infectious diseases such as Canine Parvovirus and Canine Distemper is exceptionally high, making proper maternal care even more critical. A pregnant dog must be fully vaccinated prior to mating because she cannot receive live vaccines while pregnant, yet she must pass on crucial maternal antibodies to her puppies through her first milk (colostrum). Knowing the exact whelping date allows Filipino breeders to isolate the mother in a sterile, safe environment well before labor begins, protecting the highly vulnerable newborns from environmental pathogens common in tropical climates. Additionally, with the rising popularity of high-value, imported breeds like the French Bulldog—which almost always require a scheduled Cesarean section due to their narrow hips and large heads—Filipino breeders absolutely rely on accurate date calculations to book surgery slots with specialized veterinarians in Metro Manila, as emergency C-sections in the middle of the night can be prohibitively expensive or completely unavailable in provincial areas.");

fs.writeFileSync(file, c);
console.log('Boost batch 14 safe complete');
