import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function addToField(slug: string, field: string, extra: string) {
  const marker = `slug: "${slug}"`;
  const idx = c.indexOf(marker);
  if (idx === -1) return;
  const chunk = c.substring(idx, idx + 12000);
  const re = new RegExp(field + ': "([^"]*)"');
  const m = chunk.match(re);
  if (!m) return;
  c = c.replace(m[0], m[0].slice(0,-1) + " " + extra + '"');
}

addToField("bore-stroke-calculator", "description", "Furthermore, calculating the bore/stroke ratio is essential when selecting other critical engine components. An oversquare engine will require specialized high-tension valve springs and forged connecting rods to withstand the immense inertial forces generated at 10,000+ RPM. An undersquare engine, relying on long leverage, will require a robust, heavy crankshaft to handle the immense low-end torque without snapping. By using this calculator, builders can ensure their theoretical displacement goals align perfectly with the physical limitations of their chosen engine block architecture, avoiding catastrophic engine failures on the dynamometer or the racetrack.");
addToField("bore-stroke-calculator", "philippinesContext", "The vibrant automotive subculture in the Philippines extends to classic car restoration and jeepney manufacturing. Custom builders in areas like Sarao Motors or independent garages across Pampanga often 'frankenstein' engines, mating blocks and cylinder heads from different manufacturers (like fitting a Toyota 2JZ head on a 1JZ block). Accurately recalculating the resulting bore and stroke is absolutely critical to avoid piston-to-valve clearance issues. Furthermore, as the DTI pushes for stricter emissions testing, local builders are forced to optimize combustion efficiency. A precise mathematical understanding of cylinder volume is the first step in tuning the air-fuel ratio via standalone ECU systems, ensuring these modified vehicles pass the mandatory Private Emission Testing Center (PETC) evaluations required for annual LTO registration renewal.");

addToField("engine-displacement-calculator", "description", "Beyond mere registration and bragging rights, accurate displacement calculations are the cornerstone of tuning an engine's Air-Fuel Ratio (AFR). If a mechanic increases an engine's displacement without proportionally upgrading the fuel injectors to match the new volume of air being drawn in, the engine will run dangerously 'lean' (too much air, too little fuel), leading to catastrophic overheating and melted pistons. Conversely, injecting too much fuel creates a 'rich' condition, wasting gas and fouling spark plugs. This calculator allows engine tuners to establish the exact baseline volume needed to calibrate aftermarket Engine Control Units (ECUs), ensuring optimal combustion, maximum horsepower extraction, and reliable daily drivability. Ultimately, understanding engine displacement transforms a mechanic from a parts-replacer into a true automotive engineer.");
addToField("engine-displacement-calculator", "philippinesContext", "The Philippine government's tax structure heavily penalizes large-displacement vehicles. Under the TRAIN Law (Tax Reform for Acceleration and Inclusion), excise taxes on automobiles are tiered aggressively based on the vehicle's retail price, which is almost always correlated directly with engine displacement. Consumers looking to buy an SUV must carefully weigh the performance benefits of a 3.0L engine against the massive tax savings of a 2.0L turbocharged variant. Furthermore, for the local transport sector, jeepney and UV Express operators closely monitor engine displacement when purchasing surplus engines from Japan (like the ubiquitous Isuzu 4BC2 or Toyota 2C). They must balance the need for high displacement to carry heavy passenger loads up steep provincial routes (like the zigzag roads of Baguio or Antipolo) against the daily crushing cost of diesel fuel. This calculator provides the exact numbers needed to make these vital logistical and financial decisions.");

addToField("differential-equation-calculator", "description", "The practical applications of solving ODEs are virtually limitless. In pharmacokinetics, differential equations model how quickly a drug metabolizes and clears from the human bloodstream, determining the exact dosage frequency required to maintain therapeutic levels without causing toxicity. In environmental engineering, they predict the dispersion rate of pollutants in a river system over time. While solving these equations manually forces students to understand the underlying mechanics of change, this calculator serves as a necessary safety net. By providing the final, exact algebraic expression instantly, it allows researchers and students to bypass the mathematical roadblocks and proceed directly to plotting the curve, interpreting the physical behavior of the system, and making data-driven decisions based on the modeled outcomes.");
addToField("differential-equation-calculator", "philippinesContext", "In the context of Philippine disaster risk reduction and management (DRRM), differential equations play a silent but critical role. The Philippine Atmospheric, Geophysical and Astronomical Services Administration (PAGASA) and the Philippine Institute of Volcanology and Seismology (PHIVOLCS) rely heavily on complex mathematical models, built upon differential equations, to predict typhoon trajectories, model flood inundation scenarios in Metro Manila, and estimate the cooling rates of volcanic magma chambers. While those models involve highly advanced partial differential equations run on supercomputers, the foundational mathematics starts with the first-order ODEs taught in local engineering colleges. Ensuring that Filipino engineering students have access to robust verification tools like this calculator helps cultivate a new generation of highly capable mathematicians and structural engineers equipped to tackle the unique geographical and climatological challenges faced by the archipelago.");

addToField("k-map-calculator", "description", "The practical impact of K-Map minimization is most visible in the economics of hardware production. Imagine designing a simple digital vending machine controller. Without minimization, the unoptimized Boolean equation might require ten separate logic gate chips, increasing the physical size of the circuit board, generating excess heat, and significantly raising the manufacturing cost per unit. By running the truth table through a K-Map, the engineer might discover that the same logical outcome can be achieved using only three logic gates. This optimization is crucial for embedded systems, IoT (Internet of Things) devices, and battery-powered electronics where space and power efficiency are paramount. This calculator not only provides the minimized equation but reinforces the visual learning process, helping students mentally grasp the patterns of logical redundancy that are critical for advanced IC (Integrated Circuit) design.");
addToField("k-map-calculator", "philippinesContext", "The Philippines is a major global player in semiconductor manufacturing and electronics assembly, hosting massive facilities for companies like Texas Instruments, Maxim Integrated, and Analog Devices in economic zones located in Baguio, Clark, and Laguna. For Filipino engineering graduates aspiring to enter the high-paying field of VLSI (Very Large Scale Integration) design or IC layout, mastering logic minimization is a non-negotiable entry requirement. During technical job interviews for these multinational corporations, applicants are routinely handed a marker and asked to solve a 4-variable K-Map on a whiteboard under time pressure to prove their foundational competency. By utilizing this online calculator as a training and verification tool, ECE and CpE students across the country can sharpen their analytical skills, ensuring they are globally competitive and ready to design the next generation of microprocessors right here in the Philippines.");

fs.writeFileSync(file, c);
console.log('Boost batch 13 done');
