import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("paracetamol-dosage-calculator", {
  description: "Calculate the recommended paracetamol dosage based on body weight for children and adults in the Philippines. Paracetamol (known globally as acetaminophen) is the most commonly used over-the-counter medication in the country, found in nearly every Filipino household under brand names like Biogesic, Tempra, Calpol, Tylenol, and Doliprane. This calculator helps parents, caregivers, and healthcare providers determine the safe dose per administration and the maximum daily dose based on a patient's weight and age group. Accurate dosing is critical because paracetamol overdose can cause serious liver damage — a risk that many Filipino parents underestimate when treating children's fever. The pediatric dose is weight-based (10-15 mg/kg per dose), while the adult dose is a fixed range (500-1000 mg per dose) with a strict daily maximum. This tool provides an immediate reference, but always consult a licensed physician or pharmacist for medical advice, especially for children under 2 years old, pregnant women, or patients with liver conditions. Understanding proper dosing intervals (every 4-6 hours) and maximum daily limits prevents accidental overdose while ensuring effective fever and pain relief.",
  formulaExplanation: "Pediatric dosing: 10-15 mg per kg of body weight per dose, given every 4-6 hours as needed, with a maximum of 5 doses in 24 hours. Maximum daily dose for children: 60 mg/kg/day, not to exceed 2,000 mg. To compute: multiply the child's weight in kilograms by 10 (minimum dose) and by 15 (maximum dose) to get the safe dose range per administration. Adult dosing: 500-1000 mg per dose every 4-6 hours, maximum 4 doses in 24 hours, not exceeding 4,000 mg daily. For adults weighing less than 50 kg, use weight-based dosing similar to pediatric guidelines. The minimum effective dose should always be preferred to reduce the risk of hepatotoxicity. When converting between liquid and tablet formulations: standard pediatric drops contain 100 mg/mL, pediatric syrup contains 120 mg/5 mL or 250 mg/5 mL (check the specific product), and adult tablets are typically 500 mg or 650 mg. Always verify the concentration of the specific product being administered, as Filipino pharmacies stock multiple formulations with different concentrations under various brand names.",
  exampleCalculation: "Example 1: Child weighing 10 kg — Dose range: 100-150 mg per dose. Using 120 mg/5 mL syrup: give 4-6 mL. Every 4-6 hours, max 5 doses/day. Example 2: Child weighing 25 kg — Dose: 250-375 mg. Can use 250 mg/5 mL syrup (5-7.5 mL) or half of a 500 mg tablet. Max daily: 1,500 mg. Example 3: Adult weighing 70 kg — Standard dose: 500-1000 mg (1-2 tablets of 500 mg). Every 4-6 hours, max 4,000 mg/day (8 tablets). Example 4: Child weighing 5 kg (infant) — Dose: 50-75 mg. Using drops at 100 mg/mL: 0.5-0.75 mL. Consult pediatrician for infants under 3 months. Example 5: Adult weighing 45 kg — Use weight-based: 450-675 mg per dose (1 tablet of 500 mg is appropriate). Max daily: 2,700 mg.",
  philippinesContext: "Paracetamol is the go-to fever and pain medication in the Philippines, available without prescription at pharmacies, sari-sari stores, and convenience stores. Common brands include Biogesic (Unilab), Tempra (Taisho), Calpol (GSK), and various generic versions. The DOH recommends paracetamol as the first-line antipyretic for dengue fever — ibuprofen and aspirin should be avoided in suspected dengue because they can worsen bleeding. Filipino parents commonly use paracetamol for childhood fever, teething pain, headaches, and post-vaccination discomfort. The FDA Philippines regulates paracetamol as an over-the-counter drug but requires pharmacist dispensing for certain formulations. Paracetamol overdose is a leading cause of acute liver failure worldwide, and the Philippine Poison Control Center handles cases annually. Warning signs of overdose include nausea, vomiting, loss of appetite, and yellowing of skin/eyes (jaundice) appearing 24-72 hours after ingestion. The antidote N-acetylcysteine (NAC) must be administered within 8 hours of overdose for maximum effectiveness. Filipino households should keep paracetamol out of children's reach and never exceed the recommended maximum daily dose. For patients with liver disease, chronic alcohol use, or those taking multiple medications, consult a physician before using paracetamol.",
  faqs: [
    { question: "What is the correct paracetamol dose for children?", answer: "The pediatric dose is 10-15 mg per kg of body weight per dose, given every 4-6 hours as needed. Maximum 5 doses in 24 hours. For a 15 kg child: 150-225 mg per dose. Always use a measuring syringe or cup for liquid formulations. Never estimate doses with household spoons as they vary significantly in volume." },
    { question: "What is the maximum daily dose of paracetamol?", answer: "For adults: 4,000 mg (4 grams) per day, which equals eight 500 mg tablets. For children: 60 mg/kg/day, not exceeding 2,000 mg. Exceeding these limits risks serious liver damage. Space doses at least 4 hours apart. If pain or fever persists beyond 3 days, consult a doctor rather than increasing the dose." },
    { question: "Can I give paracetamol to a baby under 3 months?", answer: "Consult a pediatrician first. For infants under 3 months, fever may indicate a serious infection requiring medical evaluation. If a doctor approves paracetamol, use infant drops (100 mg/mL) with the weight-based dose calculated precisely using a dosing syringe. Never use adult formulations for infants." },
    { question: "What paracetamol brands are available in the Philippines?", answer: "Popular brands include Biogesic (Unilab, most popular), Tempra (drops and syrup for children), Calpol (GSK pediatric), Tylenol, Doliprane, and numerous generic versions. All contain the same active ingredient. Generic paracetamol from FDA-approved manufacturers is equally effective and significantly cheaper than branded versions." },
    { question: "Can I take paracetamol with ibuprofen?", answer: "Yes, they can be alternated for better fever/pain control under medical guidance. They work through different mechanisms. However, avoid combining with aspirin for children under 18 (Reye syndrome risk). In dengue cases, use ONLY paracetamol — ibuprofen and aspirin can worsen bleeding. When alternating, maintain at least 2 hours between different medications." },
    { question: "What are signs of paracetamol overdose?", answer: "Early symptoms (within 24 hours): nausea, vomiting, loss of appetite, abdominal pain. Late symptoms (24-72 hours): jaundice (yellow skin/eyes), dark urine, right upper abdominal pain indicating liver damage. If overdose is suspected, go to the nearest emergency room immediately. The antidote NAC is most effective within 8 hours of ingestion." },
    { question: "Is paracetamol safe during pregnancy?", answer: "Paracetamol is generally considered the safest pain/fever medication during pregnancy (Category B). However, use the lowest effective dose for the shortest duration. Recent studies suggest prolonged use may affect fetal development. Always consult your OB-GYN before regular paracetamol use during pregnancy. Avoid ibuprofen and aspirin during pregnancy." },
    { question: "How do I convert between paracetamol syrup and tablets?", answer: "Standard conversions: Syrup 120 mg/5 mL = 24 mg per mL. Syrup 250 mg/5 mL = 50 mg per mL. Drops 100 mg/mL. Tablets: 325 mg or 500 mg. For a 250 mg dose: 10.4 mL of 120mg/5mL syrup, or 5 mL of 250mg/5mL syrup, or 2.5 mL of drops, or half of a 500 mg tablet (if child can swallow)." },
    { question: "Can I take paracetamol on an empty stomach?", answer: "Yes. Unlike ibuprofen and aspirin, paracetamol does not irritate the stomach lining and can be taken without food. It is absorbed faster on an empty stomach, reaching peak blood levels in 30-60 minutes versus 1-2 hours with food. For faster fever relief, take on an empty stomach with a full glass of water." },
    { question: "How long does paracetamol take to work?", answer: "Oral paracetamol begins working within 15-30 minutes, with peak effect at 1-2 hours. Fever typically drops by 1-2 degrees Celsius within 30-60 minutes. Effects last 4-6 hours. Rectal suppositories take longer to work (1-2 hours onset) but are useful when the child is vomiting and cannot take oral medication." },
    { question: "Is it safe to drink alcohol with paracetamol?", answer: "Combining paracetamol with alcohol significantly increases the risk of liver damage. Regular alcohol drinkers (3+ drinks daily) should limit paracetamol to 2,000 mg/day maximum — half the normal adult limit. Chronic alcoholics should avoid paracetamol entirely or use it only under medical supervision. This warning applies to beer, wine, and hard liquor equally." },
    { question: "Should I use paracetamol or ibuprofen for fever in dengue?", answer: "Use ONLY paracetamol for dengue fever. The DOH strictly warns against ibuprofen, aspirin, and other NSAIDs because they inhibit platelet function and can worsen the bleeding complications of dengue. Paracetamol manages fever safely without affecting blood clotting. If fever exceeds 40 degrees Celsius or persists beyond 3 days, seek immediate medical attention." },
  ]
});

upgrade("home-credit-interest-rate-calculator", {
  description: "Estimate your Home Credit monthly payments and total interest cost for consumer financing in the Philippines. Home Credit Philippines is one of the most widely used consumer lending companies, offering point-of-sale financing for smartphones, laptops, appliances, and personal loans. This calculator uses the add-on interest method that Home Credit employs, helping you see the true cost of financing before you commit to an installment plan at the store. Many Filipino consumers choose Home Credit because of its fast approval process — often just minutes at the store counter with minimal documentation (1-2 valid IDs). However, the convenience comes at a cost: Home Credit monthly add-on rates typically range from 2.0% to 3.5%, which translates to effective annual interest rates of 40-70%, significantly higher than bank credit card installments or personal loans. Understanding the total cost helps you make an informed decision about whether the convenience of instant approval is worth the premium. This tool is especially useful for comparing Home Credit terms with alternative financing options like credit card installments, digital bank loans, or saving up to buy outright.",
  formulaExplanation: "Home Credit uses the add-on interest method: Total Interest = Item Price x Monthly Rate x Number of Months. Monthly Payment = (Item Price + Total Interest) / Number of Months. The add-on method charges interest on the full original price for every month, even as your balance decreases through payments. This results in an Effective Interest Rate (EIR) approximately double the stated monthly rate. For example, a 3% monthly add-on rate over 12 months translates to approximately 62% EIR per annum. Compare this to bank personal loans at 12-24% EIR to understand the premium you pay for Home Credit convenience. Some Home Credit promotions offer 0% interest at partner merchants — these are genuinely free but may include processing fees. For personal cash loans through the Home Credit app, rates may differ from in-store financing. Always check the total amount payable (principal plus all interest and fees) before signing the agreement. Home Credit is required by BSP to disclose the EIR, so ask the sales agent for this number if it is not prominently displayed.",
  exampleCalculation: "Example 1: Smartphone at 15,000 pesos, 3.5% monthly for 12 months — Interest = 15,000 x 0.035 x 12 = 6,300. Monthly = (15,000 + 6,300) / 12 = 1,775. Total = 21,300 (42% premium). Example 2: Laptop at 35,000 pesos, 2.5% monthly for 18 months — Interest = 15,750. Monthly = 2,819.44. Total = 50,750 (45% premium). Example 3: Appliance at 25,000 pesos, 0% promo for 12 months — Monthly = 2,083.33. Total = 25,000 (free financing). Example 4: Personal cash loan of 20,000 pesos, 3.0% for 6 months — Interest = 3,600. Monthly = 3,933.33. Total = 23,600. Example 5: Compare — same 15,000 phone: Home Credit at 3.5% costs 21,300 total; BDO installment at 1.5% costs 17,700; saving 1,775/month and buying outright after 8.5 months costs exactly 15,000.",
  philippinesContext: "Home Credit Philippines is a subsidiary of Home Credit Group (Netherlands/Czech Republic) and has become one of the largest consumer financing companies in the country since entering in 2013. They operate through thousands of partner merchants including SM, Robinsons, Octagon, PC Express, and numerous local appliance and phone stores. The company has extended loans to millions of Filipino consumers, many of whom are first-time borrowers with no prior credit history. Home Credit reports to the Credit Information Corporation (CIC), so positive repayment history helps build your credit record for future bank loan applications. However, the high interest rates mean consumers often pay 30-50% more than the cash price over the installment period. The BSP regulates Home Credit as a financing company under RA 8556. Consumers can file complaints with the BSP Financial Consumer Protection Department if they encounter unfair practices. Home Credit has expanded beyond in-store financing to offer personal cash loans through their mobile app, with loan amounts ranging from 5,000 to 60,000 pesos. The app also offers a virtual credit line for online purchases. For Filipino consumers without credit cards, Home Credit fills an important market gap — but the cost of that convenience should be understood before committing.",
  faqs: [
    { question: "What is Home Credit interest rate in the Philippines?", answer: "Home Credit monthly add-on rates typically range from 2.0% to 3.5% depending on the product, term, and your credit profile. The EIR (Effective Interest Rate) is approximately double: a 3% monthly add-on equals roughly 62% EIR per annum. Promotional 0% interest plans are available at select partner merchants during sale events." },
    { question: "How do I apply for Home Credit financing?", answer: "Apply at any Home Credit partner store (SM, Robinsons, Octagon, etc.) with 1-2 valid government IDs. The process takes 5-15 minutes. A Home Credit representative processes your application on a tablet. Approval or denial is instant. No income documents or bank statements required for in-store purchases. For app-based cash loans, download the Home Credit app and complete the digital application." },
    { question: "What are the requirements for Home Credit?", answer: "Minimum requirements: Filipino citizen, 18-65 years old, 1-2 valid government IDs (SSS, PhilHealth, UMID, passport, or voter ID). No proof of income needed for in-store purchases. For cash loans through the app, additional requirements may include selfie verification and a linked bank account or GCash/Maya wallet for disbursement." },
    { question: "Is Home Credit expensive compared to other options?", answer: "Yes, Home Credit is one of the more expensive consumer financing options. A 15,000 peso phone at 3.5% monthly for 12 months costs 21,300 total (42% premium). The same phone on BDO installment at 1.5% costs 17,700 (18% premium). On a 0% credit card promo: 15,000 exact. The convenience of no-credit-check instant approval comes at a significant cost premium." },
    { question: "What happens if I miss a Home Credit payment?", answer: "Late payments incur penalty fees (typically 100-500 pesos per late payment plus percentage-based charges). Home Credit sends SMS and call reminders. Continued non-payment can result in collection agency involvement and negative reporting to CIC, affecting your future loan applications. Contact Home Credit immediately if you anticipate difficulty paying to discuss restructuring options." },
    { question: "Can I pay Home Credit early?", answer: "Yes. Contact Home Credit customer service to request early payoff. Some plans offer interest rebates for early termination while others charge the full interest regardless. Ask about the specific early termination terms for your contract before making a lump-sum payment. Early payoff helps clear your credit record faster and frees up your borrowing capacity." },
    { question: "Does Home Credit report to CIC?", answer: "Yes. Home Credit reports both positive and negative payment history to the Credit Information Corporation (CIC). This means on-time payments help build your credit record, potentially qualifying you for bank loans and credit cards in the future. Conversely, missed payments create negative records that stay on your CIC file for up to 5 years." },
    { question: "Where can I use Home Credit?", answer: "Home Credit partners with thousands of stores nationwide: SM malls, Robinsons, Octagon Computer Superstore, PC Express, Silicon Valley, Western Appliances, Abenson, and many local electronics and appliance shops. The Home Credit app also offers a virtual credit line for online purchases on Lazada and Shopee. Check the Home Credit store locator for the nearest partner merchant." },
    { question: "What is Home Credit 0% installment?", answer: "Home Credit periodically offers 0% interest promotions at select partner merchants. The item price is split into equal monthly payments with zero interest charged. Processing fees may apply (typically 200-500 pesos). These promos are genuinely cost-effective if you pay on time. Missing a payment on a 0% plan may trigger regular interest charges on the remaining balance." },
    { question: "How does Home Credit cash loan work?", answer: "Through the Home Credit mobile app, existing customers with good payment history can apply for personal cash loans of 5,000 to 60,000 pesos. Approval takes minutes. Funds are disbursed to your bank account, GCash, or Maya wallet within 1 business day. Interest rates for cash loans are typically 2-4% monthly add-on with terms of 3-18 months." },
    { question: "Can I apply for Home Credit with no valid ID?", answer: "No. At least 1 valid government-issued ID is required. Accepted IDs include: SSS, UMID, PhilHealth, TIN ID, passport, voter ID, postal ID, and PRC license. Barangay clearance and cedula are typically not accepted as primary IDs. Some stores may accept company ID as secondary identification alongside a government ID." },
    { question: "Is Home Credit safe and legitimate?", answer: "Yes. Home Credit Philippines is registered with the SEC as a financing company and regulated by BSP under RA 8556. They have been operating in the Philippines since 2013 and have served millions of customers. Their operations are transparent and they are required to disclose all fees and interest rates before contract signing. Complaints can be filed with BSP Consumer Protection." },
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 6 complete');
