import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("time-deposit-calculator", {
  description: "Estimate your time deposit interest earnings based on deposit amount, interest rate, and term. This calculator automatically accounts for the 20% withholding tax that the BIR mandates on all time deposit interest income in the Philippines. Time deposits remain one of the most popular low-risk savings instruments for Filipino depositors who want guaranteed returns and capital preservation. Unlike regular savings accounts with rates of 0.25% to 1%, time deposits offer significantly higher interest rates ranging from 3% to 6.5% per annum depending on the bank, amount, and term. The tradeoff is that your money is locked for a fixed period — typically 30 days to 5 years — and early withdrawal usually incurs a penalty that reduces or eliminates the interest earned. This tool helps you compare different time deposit offers by showing the gross interest, tax deducted, and net interest you actually receive. Whether you are parking emergency funds, saving for a down payment, or simply looking for better returns than a regular savings account, this calculator gives you the numbers to make informed decisions across BDO, BPI, Metrobank, Landbank, and other Philippine banks.",
  formulaExplanation: "Gross interest is calculated by multiplying the principal by the annual rate and the fraction of the year. The formula is: Gross Interest = Principal x (Annual Rate / 100) x (Term in Days / 365). The net interest deducts the 20% final withholding tax mandated by the BIR under Section 24(B)(1) of the NIRC. Net Interest = Gross Interest x 0.80. For deposits with terms of 5 years or longer, the tax rate drops to zero if the deposit is in a long-term deposit or investment certificate (LTDIC) that is not pre-terminated. Pre-terminating an LTDIC before 5 years triggers graduated withholding: 20% if held less than 3 years, 12% if held 3-4 years, and 5% if held 4-5 years. Interest is typically credited at maturity for short-term deposits and monthly or quarterly for longer terms. The effective annual yield after tax is always lower than the advertised nominal rate — a 5.5% gross rate yields approximately 4.4% net after the 20% tax.",
  exampleCalculation: "Example 1: ₱100,000 at 5.5% for 365 days — Gross interest = ₱5,500, Tax (20%) = ₱1,100, Net interest = ₱4,400, Total at maturity = ₱104,400. Example 2: ₱500,000 at 6% for 90 days — Gross = ₱500,000 x 6% x 90/365 = ₱7,397, Tax = ₱1,479, Net = ₱5,918. Example 3: ₱1,000,000 at 5% for 180 days — Gross = ₱24,658, Tax = ₱4,932, Net = ₱19,726. Example 4: Comparing two offers — Bank A offers 5.5% for 1 year vs Bank B offers 5.75% for 6 months. Bank A net: ₱4,400 per ₱100K. Bank B net for 6 months: ₱2,301, annualized: ₱4,602 — Bank B is actually better despite the lower-seeming rate.",
  philippinesContext: "Philippine time deposits are subject to a 20% final withholding tax on interest income under the BIR Tax Code. Time deposit rates vary significantly by bank and deposit amount — BDO, BPI, and Metrobank typically offer 3-5% for amounts under ₱1 million, while rates for ₱5 million+ can reach 5.5-6.5%. Digital banks like Tonik, Maya Bank, and CIMB often offer higher rates (4-6%) even for smaller deposits to attract customers. The minimum deposit ranges from ₱10,000 (Landbank) to ₱100,000 (BDO, Metrobank). PDIC insures time deposits up to ₱500,000 per depositor per bank — amounts above this threshold are at risk if the bank fails. BSP interest rate decisions directly impact time deposit offerings: when BSP raises rates, banks follow within weeks. For amounts held 5+ years in Long-Term Deposit or Investment Certificates, interest is tax-exempt — a significant advantage for patient savers. Time deposits are also commonly used as collateral for bank loans, allowing depositors to borrow up to 90% of their deposit value at preferential rates. When choosing between banks, compare the effective annual yield after tax, not just the headline rate.",
  faqs: [
    { question: "Is time deposit interest taxable in the Philippines?", answer: "Yes. A 20% final withholding tax is automatically deducted from time deposit interest by the bank. If you earn ₱10,000 gross interest, the bank remits ₱2,000 to BIR and credits ₱8,000 to your account. For long-term deposits held 5+ years without pre-termination, interest is tax-exempt. This tax exemption makes LTDICs attractive for patient investors." },
    { question: "What is the minimum time deposit amount in Philippine banks?", answer: "Minimums vary by bank: Landbank starts at ₱10,000, BPI at ₱50,000, BDO and Metrobank at ₱100,000. Digital banks often have lower minimums — CIMB accepts ₱1,000 and Tonik starts at ₱5,000. Higher deposit amounts typically qualify for better interest rates. Ask your bank about tiered rates for deposits above ₱500,000 and ₱1 million." },
    { question: "Can I withdraw my time deposit early?", answer: "Most banks allow early withdrawal but impose penalties — typically forfeiting all or most of the accrued interest. Some banks charge a pre-termination fee of 0.5-1% of the principal. BPI charges the higher of ₱500 or the interest rate differential. For long-term deposit certificates, early withdrawal also triggers graduated withholding tax: 20% if held under 3 years, 12% for 3-4 years, 5% for 4-5 years." },
    { question: "Which Philippine bank offers the highest time deposit rate?", answer: "Rates change frequently based on BSP policy and market conditions. As a general pattern, digital banks (Tonik, Maya Bank, CIMB) offer 4-6% for shorter terms. Traditional banks (BDO, BPI, Metrobank) offer 3-5.5% depending on amount and term. CTBC Bank and ING Philippines have historically offered competitive rates. Always compare current offers across at least 3 banks before committing." },
    { question: "Is my time deposit covered by PDIC insurance?", answer: "Yes. PDIC insures time deposits up to ₱500,000 per depositor per bank. If you have ₱500,000 at BDO and ₱500,000 at BPI, both are fully insured. If you have ₱1,000,000 at one bank, only ₱500,000 is covered. For large deposits, consider spreading across multiple banks or using government-backed instruments like Pag-IBIG MP2 for additional safety." },
    { question: "How does BSP interest rate affect time deposit rates?", answer: "When BSP raises its overnight borrowing rate, banks increase time deposit rates within 1-4 weeks to attract deposits. A 0.25% BSP hike typically translates to 0.15-0.30% increase in time deposit rates. Conversely, BSP rate cuts lead to lower deposit rates. Monitor BSP monetary policy announcements to time your deposits for maximum returns." },
    { question: "What is the difference between time deposit and savings account?", answer: "Time deposits offer higher rates (3-6.5%) but lock your money for a fixed term. Savings accounts offer lower rates (0.25-2%) but allow anytime withdrawal. Time deposit interest is taxed at 20%, same as savings. The key advantage of time deposits is guaranteed higher returns in exchange for reduced liquidity. Digital bank savings accounts now offer 3-6%, narrowing this gap significantly." },
    { question: "Can I use time deposit as loan collateral?", answer: "Yes. Most Philippine banks allow you to borrow 80-90% of your time deposit value at rates 1-2% above the deposit rate. This is called a hold-out loan or deposit-secured loan. You keep earning interest on your deposit while accessing funds. It is often cheaper than a personal loan and has faster approval since the collateral is already with the bank." },
    { question: "How is time deposit interest computed for partial years?", answer: "Interest is prorated based on the number of days. Formula: Principal x Rate x (Days/365). A ₱200,000 deposit at 5% for 90 days earns ₱200,000 x 0.05 x (90/365) = ₱2,466 gross interest, or ₱1,973 net after 20% tax. Banks use actual calendar days, and leap years use 366 in the denominator." },
    { question: "Should I choose time deposit or Pag-IBIG MP2?", answer: "MP2 typically offers higher returns (5-7% tax-free) compared to time deposits (3-6.5% with 20% tax). MP2 equivalent after-tax comparison: 7% MP2 equals roughly 8.75% time deposit. However, MP2 locks funds for 5 years while time deposits can be as short as 30 days. For money you will not need for 5 years, MP2 is almost always better. For shorter-term savings, time deposits win on flexibility." },
    { question: "What happens to time deposit interest if the bank fails?", answer: "PDIC insures both principal and accrued interest up to ₱500,000 combined per depositor per bank. If your principal is ₱490,000 with ₱15,000 accrued interest, only ₱500,000 is covered — you lose ₱5,000. PDIC claims are processed within 6-12 months after bank closure. For deposits exceeding PDIC limits, you become a creditor in the bank liquidation process." },
    { question: "Can OFWs open time deposits in Philippine banks?", answer: "Yes. OFWs can open time deposits at BDO, BPI, Metrobank, and Landbank through overseas branches or representative offices. Some banks allow remote opening with an existing account. OFWs benefit from higher rates offered on dollar-denominated time deposits and can choose between PHP or USD accounts. Remittance-to-time-deposit products are available at some banks for automatic conversion." },
  ]
});

upgrade("pwd-discount-calculator", {
  description: "Compute the 20% discount and 12% VAT exemption for Persons with Disability (PWD) in the Philippines. This calculator instantly shows you the final discounted price after applying both the VAT removal and the PWD discount, helping you verify if establishments are giving you the correct price. Under Republic Act 10754, PWDs are entitled to a 20% discount on select goods and services including food, medicine, transportation, medical and dental services, hotels and lodging, and funeral services. The discount is applied on top of VAT exemption — meaning PWDs do not pay the 12% VAT first, then receive an additional 20% off the base price. Many PWDs and their caregivers find the discount computation confusing because the VAT removal and percentage discount must be applied in the correct order. Some establishments incorrectly compute the discount by simply taking 20% off the VAT-inclusive price, which actually gives less savings than the legally mandated computation. This tool ensures you know the exact amount you should pay and can verify whether the store, pharmacy, or service provider is applying the correct formula as specified by NCDA and DTI guidelines.",
  formulaExplanation: "The PWD discount computation follows a specific order mandated by law. First, remove the 12% VAT from the listed price to get the base price (divide VAT-inclusive price by 1.12). Then apply the 20% discount to the VAT-exclusive base price. The formula is: Final Price = (Listed Price / 1.12) x 0.80. This means PWDs get both VAT exemption AND a 20% discount — effectively paying only 71.4% of the original VAT-inclusive retail price. If the item is already priced VAT-exclusive, simply multiply by 0.80 to get the discounted price. The VAT exemption and discount cannot be used simultaneously with senior citizen discounts — a person who qualifies for both must choose one. Establishments are required to display the computation breakdown on receipts showing the original price, VAT removed, discount applied, and final amount. DTI monitors compliance and penalizes establishments that compute discounts incorrectly.",
  exampleCalculation: "Example 1: Medicine priced at ₱1,120 (VAT-inclusive). Step 1: Remove VAT — ₱1,120 / 1.12 = ₱1,000 base. Step 2: Apply 20% discount — ₱1,000 x 0.80 = ₱800. PWD pays ₱800 (saves ₱320). Example 2: Restaurant meal at ₱560 VAT-inclusive. Base = ₱500. PWD price = ₱400. Savings = ₱160. Example 3: Hotel room at ₱5,600/night. Base = ₱5,000. PWD rate = ₱4,000. Example 4: Grocery items totaling ₱2,240. Base = ₱2,000. PWD total = ₱1,600. Example 5: Medical consultation fee at ₱1,000 (VAT-exclusive). PWD price = ₱800 (no VAT to remove since already exclusive).",
  philippinesContext: "Under RA 10754, Persons with Disability in the Philippines are entitled to a 20% discount and VAT exemption on a wide range of goods and services. The law covers: medicines and medical supplies, professional medical and dental fees, hospital and clinical charges, domestic air and sea transportation, hotels and restaurants, admission fees to theaters and recreation centers, funeral and burial services, and tuition and school fees. To avail the discount, PWDs must present a valid PWD ID card issued by the local government unit (city or municipal social welfare office) along with a booklet for recording transactions. Establishments are required to honor the discount and can claim it as a tax deduction — not a tax credit — from their gross income per BIR Revenue Regulations No. 1-2009. The NCDA (National Council on Disability Affairs) oversees PWD welfare programs, while DTI and DOH monitor compliance at commercial establishments and healthcare facilities respectively. Non-compliant establishments face fines of ₱50,000 to ₱100,000 and possible revocation of business permits. Approximately 1.4 million Filipinos are registered PWDs, though disability advocacy groups estimate the actual number is much higher. The PWD discount has been instrumental in reducing the financial burden on persons with disabilities and their families, particularly for chronic medication costs that can consume a significant portion of household income.",
  faqs: [
    { question: "What is the PWD discount in the Philippines?", answer: "PWDs receive a 20% discount on eligible goods and services PLUS exemption from 12% VAT. Combined, a PWD pays approximately 71.4% of the original VAT-inclusive retail price. This applies to medicines, food, medical services, transportation, hotels, school fees, and recreation. The discount is mandated by RA 10754 and enforced by DTI and local government units." },
    { question: "How is PWD discount computed on VAT-inclusive prices?", answer: "First remove the 12% VAT by dividing the price by 1.12 to get the base amount. Then apply the 20% discount by multiplying by 0.80. Formula: Final Price = Listed Price / 1.12 x 0.80. For a ₱1,120 item: ₱1,120 / 1.12 = ₱1,000 base, then ₱1,000 x 0.80 = ₱800 final price. Total savings: ₱320." },
    { question: "What goods and services qualify for PWD discount?", answer: "RA 10754 covers: medicines and medical supplies, professional medical/dental fees, hospital charges, domestic air and sea fare, hotels and restaurants, admission to cinemas and recreation centers, funeral and burial services, and tuition fees. The discount applies to specific items — not all purchases at a store. Grocery items not classified as food are generally excluded." },
    { question: "Can PWD and senior citizen discounts be combined?", answer: "No. A person who qualifies as both a PWD and a senior citizen must choose one discount — they cannot stack both. However, both discounts use the same computation method (VAT exemption + 20% off base price), so the savings amount is identical. The PWD ID and Senior Citizen ID are issued separately by local government social welfare offices." },
    { question: "How do I get a PWD ID card?", answer: "Apply at the Persons with Disability Affairs Office (PDAO) or the City/Municipal Social Welfare and Development Office. Requirements: medical certificate with disability diagnosis from a licensed physician, 1x1 and 2x2 ID photos, birth certificate or any valid government ID, and barangay certification of residency. Processing is free and typically takes 1-2 weeks." },
    { question: "Can a PWD companion also avail the discount?", answer: "Generally, no. The discount applies only to the PWD themselves. However, for food purchases at restaurants, the discount covers one meal for the PWD. For medicines, only prescriptions under the PWD name qualify. The companion or caregiver must pay regular prices for their own purchases unless they separately qualify as a PWD or senior citizen." },
    { question: "What if a store refuses to give the PWD discount?", answer: "Report the establishment to DTI (for commercial establishments) or DOH (for healthcare facilities). File a complaint at the nearest DTI office or call the DTI hotline 1-384. Non-compliant businesses face fines of ₱50,000 to ₱100,000 for the first offense and up to ₱200,000 plus business permit revocation for repeat offenses. NCDA also accepts complaints online." },
    { question: "Does PWD discount apply to online purchases?", answer: "The law does not explicitly cover online transactions, but the NCDA encourages online pharmacies and retailers to extend the discount. Major pharmacy chains like Mercury Drug, Watsons, and Rose Pharmacy honor PWD discounts for online orders with valid PWD ID verification. Check with the specific retailer for their online PWD discount policy." },
    { question: "How do establishments claim tax deduction for PWD discounts?", answer: "Establishments claim the PWD discount as a deduction from gross income on their income tax return — not a tax credit. The deduction equals the net cost of the discount (20% of VAT-exclusive selling price minus VAT). Establishments must maintain a separate logbook recording PWD transactions including PWD ID number, name, date, and discount amount per BIR regulations." },
    { question: "Is the PWD discount applicable to all medicines?", answer: "The 20% discount applies to all medicines purchased by a PWD for their personal use, whether prescription or over-the-counter. This includes maintenance medications for chronic conditions. The PWD must present their PWD ID and the purchase must be recorded in their PWD booklet. Generic and branded medicines both qualify for the discount." },
    { question: "Does PWD discount apply to dental services?", answer: "Yes. Professional dental fees, including consultation, cleaning, extraction, and dental procedures, qualify for the 20% PWD discount and VAT exemption. The discount applies to professional fees only — dental materials and laboratory fees may or may not be included depending on how the dental clinic structures their billing. Ask the clinic for an itemized breakdown." },
    { question: "What is the difference between PWD discount and PhilHealth coverage?", answer: "They are separate benefits and can be used together. PhilHealth covers hospitalization, outpatient procedures, and Z-benefit packages based on your membership category. PWD discount applies at the point of sale for out-of-pocket expenses. After PhilHealth deducts its coverage, the remaining patient responsibility can still receive the 20% PWD discount where applicable." },
  ]
});

upgrade("bpi-credit-to-cash-calculator", {
  description: "Estimate the monthly payments and total fees for BPI Credit-to-Cash facility. This tool helps BPI credit card holders understand the true cost of converting available credit limit into cash. BPI Credit-to-Cash is a convenient facility that deposits funds directly into your BPI savings or checking account, payable in fixed monthly installments over 6 to 36 months. Unlike a regular cash advance from an ATM (which charges interest daily from the withdrawal date), Credit-to-Cash uses a fixed add-on interest rate, making monthly payments predictable. However, the add-on method means you pay interest on the original amount for the entire term, even as your balance decreases — resulting in a higher effective interest rate than the stated monthly rate. This calculator shows you the total interest cost, monthly payment breakdown, and helps you compare BPI Credit-to-Cash against alternative borrowing options like personal loans and salary loans. Understanding the real cost is essential because the convenience of quick credit access can mask an expensive borrowing decision if you are not comparing the effective annual rate to other available options.",
  formulaExplanation: "BPI Credit-to-Cash uses an add-on interest rate, which is different from the diminishing balance method used by most personal loans. Total Interest = Principal x Monthly Rate x Number of Months. Monthly Payment = (Principal + Total Interest) / Number of Months. The add-on method charges interest on the full original amount for the entire term, not on the declining balance. This means the Effective Interest Rate (EIR) is roughly double the stated add-on rate. A 1.29% monthly add-on rate translates to approximately 27-28% EIR per annum — significantly higher than a personal loan at 12-18% EIR. BPI sometimes offers promotional rates as low as 0.69% to 0.99% monthly for loyal cardholders or during seasonal campaigns. Always ask for the EIR disclosure when applying. A processing fee of ₱200 to ₱500 may also apply, which should be factored into the total borrowing cost.",
  exampleCalculation: "Example 1: ₱50,000 at 1.29% monthly for 12 months — Total interest = ₱50,000 x 0.0129 x 12 = ₱7,740. Monthly payment = (₱50,000 + ₱7,740) / 12 = ₱4,811.67. Total repayment = ₱57,740. Example 2: ₱100,000 at 1.29% for 24 months — Interest = ₱30,960. Monthly = ₱5,456.67. Total = ₱130,960 (31% over principal). Example 3: ₱30,000 at 0.99% promo rate for 6 months — Interest = ₱1,782. Monthly = ₱5,297. Total = ₱31,782 (6% over principal). Example 4: Comparing — ₱50,000 for 12 months at 1.29% add-on costs ₱7,740 interest. A BPI personal loan at 1.2% monthly diminishing balance costs approximately ₱3,940 interest — saving ₱3,800.",
  philippinesContext: "BPI (Bank of the Philippine Islands) is one of the oldest and largest banks in the Philippines, serving millions of credit card holders. The Credit-to-Cash facility is available to BPI credit card holders with sufficient available credit limit and good standing. Typical add-on rates range from 0.99% to 1.79% monthly depending on the cardholder profile, term selected, and current promotions. BPI periodically offers flash promos with rates as low as 0.69% for select customers. To avail, cardholders can call BPI customer service at (02) 889-10000, apply through the BPI app, or visit a BPI branch. Approval is usually instant for existing cardholders in good standing. The minimum amount is typically ₱10,000, and the maximum depends on your available credit limit. Proceeds are deposited to your linked BPI savings account within 1-3 business days. Monthly payments are automatically charged to your credit card statement. It is important to note that using Credit-to-Cash reduces your available credit limit by the amount availed. For larger financing needs or longer terms, a BPI personal loan at diminishing balance rates may be more cost-effective. BPI also offers installment plans for purchases (BPI SIP), which may have different rates than Credit-to-Cash. Always compare the EIR across all available options before committing.",
  faqs: [
    { question: "How does BPI Credit to Cash work?", answer: "BPI Credit-to-Cash converts your available credit card limit into cash deposited directly to your BPI savings account. You repay in fixed monthly installments (6-36 months) at a stated add-on interest rate. The monthly installment is automatically charged to your credit card billing. Your available credit limit decreases by the amount availed until fully repaid." },
    { question: "What is BPI Credit-to-Cash interest rate?", answer: "Regular rates range from 0.99% to 1.79% monthly add-on depending on your cardholder profile and selected term. BPI offers promotional rates as low as 0.69% for select customers during promo periods. The Effective Interest Rate (EIR) is approximately double the stated add-on rate — a 1.29% monthly add-on translates to roughly 27% EIR annually." },
    { question: "What is the minimum and maximum BPI Credit-to-Cash amount?", answer: "The minimum is typically ₱10,000, and the maximum depends on your available credit limit. You can check your available limit through the BPI mobile app, BPI Online, or by calling the credit card hotline. BPI may also offer pre-approved amounts based on your credit standing and payment history. Do not max out your credit limit — maintain a utilization ratio below 30%." },
    { question: "How long does BPI Credit-to-Cash disbursement take?", answer: "Once approved, funds are deposited to your linked BPI savings or checking account within 1-3 business days. Approval is usually instant for existing cardholders in good standing. Apply through BPI customer service at (02) 889-10000, the BPI mobile app, or visit any BPI branch. You will receive an SMS confirmation when the amount is credited." },
    { question: "Is BPI Credit-to-Cash better than a personal loan?", answer: "Usually not for larger amounts or longer terms. Credit-to-Cash uses add-on interest (higher effective cost), while personal loans typically use diminishing balance. A ₱100,000 Credit-to-Cash at 1.29% add-on for 24 months costs ₱30,960 in interest. A BPI personal loan at 1.2% diminishing for 24 months costs approximately ₱15,200 — saving nearly ₱15,760. Choose Credit-to-Cash only for speed and convenience on smaller amounts." },
    { question: "Can I pay BPI Credit-to-Cash early?", answer: "BPI allows early payoff, but the remaining interest for the full term may still be charged depending on the specific terms of your availment. Some promos allow interest rebate for early termination while others do not. Contact BPI credit card customer service to inquire about your specific terms before making a lump-sum payment to close the balance." },
    { question: "Does BPI Credit-to-Cash affect my credit score?", answer: "Indirectly, yes. It increases your credit utilization ratio (the percentage of your credit limit in use), which can negatively impact your credit assessment for future applications. If you avail ₱50,000 Credit-to-Cash on a ₱100,000 limit, your utilization jumps to 50%. Financial advisors recommend keeping utilization below 30% for optimal credit health." },
    { question: "What happens if I miss a BPI Credit-to-Cash payment?", answer: "The installment amount appears on your regular credit card statement. If you miss payment, BPI charges late payment fees (₱500-₱700) plus finance charges on the overdue amount (typically 3.25% monthly or 39% annually). Three consecutive missed payments can lead to credit card cancellation and negative reporting to the Credit Information Corporation (CIC)." },
    { question: "How do I apply for BPI Credit-to-Cash?", answer: "Apply through BPI mobile app (Quick Loans section), BPI Online banking, calling BPI customer service at (02) 889-10000, or visiting any BPI branch. You will need your credit card number and choose your desired amount and term. Pre-approved offers may appear in your BPI app with personalized rates. Approval is typically instant for cardholders in good standing." },
    { question: "Is there a processing fee for BPI Credit-to-Cash?", answer: "BPI may charge a processing fee of ₱200 to ₱500 depending on the amount and current terms. This fee is typically added to the first monthly installment or charged separately to your card. During promotional periods, the processing fee may be waived. Always ask about all fees upfront before confirming your application." },
    { question: "Can I avail BPI Credit-to-Cash multiple times?", answer: "Yes, as long as you have sufficient available credit limit. Multiple Credit-to-Cash availments run concurrently with separate installment schedules. However, multiple availments quickly consume your credit limit and increase your debt-to-income ratio. Ensure your total monthly obligations remain below 30% of your gross monthly income to maintain financial health." },
    { question: "What is the difference between Credit-to-Cash and cash advance?", answer: "Credit-to-Cash has fixed monthly installments at a stated add-on rate (1-1.8% monthly). ATM cash advance charges interest daily from the withdrawal date at approximately 3.25% monthly (39% annually) with no grace period and a 2.5% transaction fee. Credit-to-Cash is significantly cheaper for amounts you plan to repay over months. Cash advance is only suitable for emergency needs repaid within days." },
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 2 complete');
