import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("metrobank-car-loan-calculator", {
  description: "Calculate your monthly amortization, required down payment, and total interest for a Metrobank Car Loan. Metrobank is one of the premier universal banks in the Philippines, holding a massive market share in automotive financing. Buying a car—whether a brand-new Toyota Vios for daily commuting or a pre-owned SUV for family trips—is a major financial commitment for most Filipinos. This calculator helps prospective car buyers determine exactly how much vehicle they can afford based on their monthly budget. By inputting the vehicle's selling price, your planned down payment percentage, and your desired loan term, the tool computes the fixed monthly installment you will be paying to the bank. It also explicitly reveals the total interest cost over the life of the loan. This is critical because dealerships often focus solely on the 'low monthly payment' to close a sale, masking the true, inflated cost of the vehicle when financed over 60 months. This tool empowers Filipino consumers to negotiate better terms, decide between a 3-year or 5-year loan, and avoid the trap of car repossession caused by taking on unaffordable auto debt.",
  formulaExplanation: "Metrobank, like most Philippine banks, calculates car loan amortizations using the add-on interest method. First, you determine the Amount Financed: Amount Financed = Selling Price - Down Payment. Next, you calculate the Total Interest: Total Interest = Amount Financed * Annual Add-on Rate * Term in Years. Finally, you compute the Monthly Amortization: Monthly Amortization = (Amount Financed + Total Interest) / Total Number of Months. Because the interest is 'added on' upfront based on the original amount financed, the Effective Interest Rate (EIR)—the true cost of borrowing—is significantly higher than the quoted add-on rate. For instance, a typical 5-year auto loan might quote a total add-on rate of 27.28% (which averages to 5.45% per year), but the actual EIR is closer to 10% per annum. Furthermore, borrowers must pay upfront costs before the car is released, including Chattel Mortgage fees (the cost of registering the car as collateral with the Registry of Deeds) and Comprehensive Insurance premiums.",
  exampleCalculation: "Example: You are buying a brand-new car priced at PHP 1,000,000. You make a 20% down payment (PHP 200,000), leaving an Amount Financed of PHP 800,000. You choose a 60-month (5-year) term. The bank's 5-year total add-on rate is 27.28%. Total Interest = 800,000 * 0.2728 = PHP 218,240. Total Amount Payable to the bank = 800,000 + 218,240 = PHP 1,018,240. Monthly Amortization = 1,018,240 / 60 = PHP 16,970.67 per month. Notice that the total cost of the car becomes the down payment (200k) plus the total payable (1.018M), which equals PHP 1,218,240—meaning you are paying a 21.8% premium over the cash price for the privilege of financing. If you instead chose a 36-month term with a 15% add-on rate: Total Interest = 800,000 * 0.15 = 120,000. Monthly Amortization = 920,000 / 36 = PHP 25,555.56. While the monthly payment is higher, you save PHP 98,240 in overall interest.",
  philippinesContext: "The Philippine automotive market relies heavily on bank financing, with over 70% of new car purchases funded through auto loans. Metrobank is highly aggressive in this space, frequently partnering with major dealerships (Toyota, Mitsubishi, Honda, Ford) to offer promotional rates or 'all-in down payment' packages. These all-in promos often bundle the Chattel Mortgage, 3-year LTO Registration, and 1-year Comprehensive Insurance into the upfront payment. The Bangko Sentral ng Pilipinas (BSP) mandates that banks require a minimum down payment of 20% for auto loans to mitigate default risk, though some promotional tie-ups may offer 15% subject to strict credit approval. When applying for a Metrobank Car Loan, the golden rule of credit underwriting applies: your monthly car amortization should not exceed 30% to 40% of your gross monthly income. If you earn PHP 50,000 a month, your maximum approvable car payment is roughly PHP 15,000 to PHP 20,000. The bank retains the original OR/CR (Official Receipt / Certificate of Registration) encumbered in its name until the loan is fully paid off.",
  faqs: [
    { question: "What is the minimum down payment for a Metrobank Car Loan?", answer: "The standard minimum down payment required by Metrobank and mandated by BSP guidelines is 20% of the vehicle's selling price. During special promotional periods or specific dealer tie-ups, the bank may occasionally approve a 15% down payment for highly qualified borrowers." },
    { question: "How long can I finance a car in the Philippines?", answer: "For brand-new cars, the repayment term ranges from 12 months (1 year) up to a maximum of 60 months (5 years). For pre-owned or used cars, the maximum term is usually shorter, typically capped at 36 or 48 months depending on the age of the vehicle." },
    { question: "What is an 'All-in Down Payment' promo?", answer: "An 'All-in' promo means your initial cash out covers the down payment PLUS the typical upfront processing fees: Chattel Mortgage, 1-year Comprehensive Insurance, and 3-year LTO Registration. However, be cautious: all-in promos often hide higher interest rates in the monthly amortization." },
    { question: "What are Chattel Mortgage fees?", answer: "A chattel mortgage is a legal mechanism where the bank registers your newly purchased car as collateral for the loan with the Registry of Deeds. If you fail to pay, the bank has the legal right to repossess the car. The fee is usually 1% to 2% of the loan amount." },
    { question: "Does Metrobank finance used cars?", answer: "Yes, Metrobank offers financing for pre-owned vehicles. However, the interest rates for used cars are significantly higher than for brand-new cars, and the vehicle usually cannot be older than 5 or 6 years at the time the loan matures." },
    { question: "How much income do I need to get approved?", answer: "Banks generally require that your monthly car amortization does not exceed 30% to 40% of your gross monthly income. For example, to afford a PHP 20,000 monthly payment, your gross monthly income should be at least PHP 50,000 to PHP 66,000." },
    { question: "Can I pay off my car loan early?", answer: "Yes, you can pre-terminate your auto loan. However, Philippine banks typically charge a pre-termination fee (e.g., 5% to 8% of the outstanding principal balance). You must contact the bank to request an official payoff computation to see if early payment makes financial sense." },
    { question: "What happens if I miss a monthly payment?", answer: "Late payments incur steep penalty charges (usually around 3% to 5% per month on the overdue amount). If you default for 2 to 3 consecutive months, the bank will initiate repossession proceedings. The delinquency will also be permanently recorded in the CIC credit database." },
    { question: "Do I need comprehensive insurance?", answer: "Yes. As long as the car is mortgaged to the bank, you are strictly required to maintain an active comprehensive car insurance policy with the bank listed as the 'mortgagee'. If you fail to renew it, the bank may force-place a policy and charge your account." },
    { question: "How long does Metrobank car loan approval take?", answer: "If you submit complete documentary requirements (ITR, payslips, COE, valid IDs), standard processing takes 1 to 3 banking days. Self-employed individuals may take longer due to business verification and financial statement analysis." },
    { question: "What is the difference between add-on rate and effective interest rate (EIR)?", answer: "The add-on rate calculates interest on the full original loan amount for the entire term. The EIR reflects the true cost of the loan on a declining balance basis. Because you are constantly paying down the principal, the EIR is always much higher (almost double) the add-on rate." },
    { question: "How do I get my OR/CR after fully paying the loan?", answer: "Once your final payment clears, you must request the release of your original OR/CR and the 'Cancellation of Chattel Mortgage' document from Metrobank. You then take this document to the Registry of Deeds and the LTO to officially remove the bank's encumbrance from your car's title." }
  ]
});

upgrade("metrobank-home-loan-calculator", {
  description: "Calculate your monthly amortization and total interest for a Metrobank Home Loan. Metrobank is a dominant player in Philippine real estate financing, offering housing loans for purchasing vacant lots, house and lot packages, condominiums, or for house construction and renovation. Buying a home is the largest financial transaction most Filipinos will ever make, often requiring decades of commitment. This calculator is a vital preliminary tool for prospective homeowners, allowing you to estimate your monthly payments based on the property's selling price, your down payment equity, and the bank's prevailing interest rates. By testing different scenarios—such as a 15-year term versus a 20-year term—you can find a balance between an affordable monthly payment and the total amount of interest paid over the life of the loan. Furthermore, it helps you ensure that your target property aligns with your current income capacity, as banks strictly enforce debt-to-income ratios before approving multi-million peso housing loans. Avoid the heartbreak of a rejected application by running your numbers here first.",
  formulaExplanation: "Unlike auto or personal loans that use add-on interest, Philippine housing loans use the diminishing balance method. The formula is: M = P [ i(1 + i)^n ] / [ (1 + i)^n - 1 ], where M is the Monthly Payment, P is the Principal Loan Amount, i is the monthly interest rate (annual rate divided by 12), and n is the total number of months. Because interest is charged only on the remaining unpaid principal, your monthly payment consists of two parts: a portion that pays the interest for that month, and a portion that reduces the principal. In the early years of a 20-year loan, almost 80% of your monthly payment goes toward interest. It is also crucial to understand 'fixing periods'. Metrobank will offer an interest rate that is fixed for 1, 3, or 5 years. After this fixing period expires, the loan is subject to annual repricing based on the prevailing market rates set by the BSP, which means your monthly amortization can go up or down.",
  exampleCalculation: "Example: You are buying a condominium priced at PHP 5,000,000. You pay a 20% equity down payment (PHP 1,000,000) directly to the developer. You apply for a Metrobank Home Loan for the remaining PHP 4,000,000. You choose a 15-year term (180 months) at a fixed interest rate of 7.00% per annum (0.5833% monthly). Monthly Amortization = 4,000,000 * [0.005833 * (1.005833)^180] / [(1.005833)^180 - 1] = PHP 35,953.15 per month. Over 15 years, you will make 180 payments of PHP 35,953.15, totaling PHP 6,471,567. Since you only borrowed 4 million, the Total Interest paid to the bank is PHP 2,471,567. If you stretched the loan to 20 years to lower the monthly payment to PHP 31,011.96, your total interest paid would skyrocket to PHP 3,442,870. The calculator instantly highlights this massive difference, demonstrating the cost of long-term borrowing.",
  philippinesContext: "The Philippine real estate sector is highly reliant on bank financing. While Pag-IBIG Fund provides housing loans primarily for low to middle-income earners (with a maximum loanable amount of PHP 6 Million), universal banks like Metrobank cater to the middle-to-high-end market without hard loan ceilings, provided the borrower has the capacity to pay. The Bangko Sentral ng Pilipinas (BSP) dictates that banks require a minimum of 20% equity (down payment) for housing loans, lending a maximum of 80% of the property's appraised value. During the underwriting process, Metrobank applies a strict Debt-to-Income (DTI) ratio, typically capping total monthly debt payments at 30% to 40% of the borrower's gross monthly income. Beyond the down payment, Filipino homebuyers must also budget for substantial upfront closing costs. When taking out a home loan, you must pay for the Appraisal Fee, Mortgage Registration Fees with the Registry of Deeds, Documentary Stamp Taxes (DST), Notarial fees, and mandatory insurance premiums (Mortgage Redemption Insurance and Fire Insurance), which typically add 2% to 3% of the loan amount to your out-of-pocket expenses.",
  faqs: [
    { question: "What is the minimum equity or down payment for a Metrobank Home Loan?", answer: "The standard minimum equity required is 20% of the property's appraised value or selling price (whichever is lower). The bank will finance up to 80%. For certain properties, especially vacant lots or properties outside major cities, the bank may require a higher equity of 30% or 40%." },
    { question: "What is the maximum term for a housing loan?", answer: "Metrobank typically offers a maximum repayment term of 25 years for house and lot purchases, 15 years for condominium units, and 10 years for vacant lots. However, the loan must be fully paid before the borrower reaches the age of 65 (for employees) or 70 (for self-employed individuals)." },
    { question: "What is an interest rate fixing period?", answer: "A fixing period guarantees that your interest rate (and your monthly payment) will not change for a specific number of years, typically 1, 3, 5, or 10 years. Once this period expires, your loan is subject to 'repricing', meaning the bank will adjust your rate based on current market conditions." },
    { question: "Is Metrobank Home Loan better than Pag-IBIG?", answer: "It depends on your needs. Pag-IBIG offers lower rates for affordable housing (below PHP 3M) and longer terms (up to 30 years), but has a strict PHP 6M cap and slower processing. Metrobank has no strict loan limit, faster processing, and is ideal for premium condos and high-value properties." },
    { question: "What income is required for a home loan?", answer: "Banks use a Debt-to-Income (DTI) ratio. Your monthly home loan payment should not exceed 30% to 40% of your gross monthly income. If your calculated monthly amortization is PHP 40,000, your combined household gross income should be at least PHP 100,000 to PHP 133,000 to get approved." },
    { question: "What are the upfront fees for a housing loan?", answer: "Upfront closing costs include the Appraisal Fee (PHP 4,000 - PHP 5,000), Mortgage Registration Fees, Documentary Stamp Tax (DST), Notarial fees, and the first year's premium for MRI and Fire Insurance. These bank charges typically amount to 2% to 3% of your approved loan amount." },
    { question: "What is MRI (Mortgage Redemption Insurance)?", answer: "MRI is a mandatory life insurance policy tied to your housing loan. In the unfortunate event of the borrower's death or total permanent disability, the insurance company will pay off the remaining balance of the loan, ensuring that the borrower's family does not lose the home." },
    { question: "Can I use the home loan for construction?", answer: "Yes, Metrobank offers construction loans. Instead of a lump sum, the loan is released in 'staggered' tranches based on the completion percentage of the house construction. The bank will send an appraiser periodically to verify the construction progress before releasing the next batch of funds." },
    { question: "Can I pay extra toward my principal?", answer: "Yes, you can make partial advanced payments to the principal, which is highly recommended as it drastically reduces the total interest paid and shortens your loan term. However, it must usually be done on your repricing date or anniversary to avoid pre-termination penalties." },
    { question: "Why is the appraised value lower than the selling price?", answer: "Banks conduct their own independent appraisal of the property to determine its fair market value, which is often lower than the developer's or seller's asking price. The bank will base the 80% loanable amount on THEIR appraised value, not the selling price. You must cover any difference in cash." },
    { question: "What happens if I cannot pay my monthly amortization?", answer: "Late payments incur severe penalty fees. If you default for several months (usually 3 to 6 months), the bank will initiate foreclosure proceedings under Act No. 3135. The property will be auctioned off to recover the bank's losses, and your credit record will be ruined." },
    { question: "Does Metrobank allow co-borrowers?", answer: "Yes, you can include a co-borrower (usually a spouse, parent, or sibling) to combine your incomes and qualify for a higher loan amount. Both borrowers will be jointly responsible for the debt, and both must sign the loan documents." }
  ]
});

upgrade("bdo-installment-card-calculator", {
  description: "Calculate your monthly payments for the BDO Installment Card Cash Availment facility. The BDO Installment Card is a unique credit product in the Philippines designed specifically for cash loans rather than retail swiping. It allows cardholders to convert their credit limit into cash (Cash Availment) at remarkably low monthly add-on interest rates compared to standard personal loans. This calculator is a critical tool for BDO Installment Cardholders who are planning to withdraw cash for home renovations, business capital, tuition fees, or medical emergencies. By inputting the cash amount needed, your approved promotional add-on rate, and your desired repayment term, the calculator instantly computes the fixed monthly amortization. It provides a transparent view of the total interest you will pay over the term, preventing 'bill shock' when your monthly statement arrives. Because BDO frequently runs promotional rates (sometimes as low as 0.45% to 0.70% monthly add-on for select clients), this tool helps you quantify exactly how much money you save by utilizing this card over traditional personal loans or unregulated lending apps.",
  formulaExplanation: "The BDO Installment Card utilizes the standard add-on interest method for Cash Availments. The calculation involves three steps. First, calculate the Total Interest: Total Interest = Cash Amount * Monthly Add-on Rate * Term in Months. Second, calculate the Total Amount Payable: Total Payable = Cash Amount + Total Interest. Third, calculate the Monthly Amortization: Monthly Amortization = Total Payable / Term in Months. It is critical to understand that while the monthly add-on rate sounds low (e.g., 0.59%), it is applied to the full principal amount for the entire duration of the loan. Therefore, the Effective Interest Rate (EIR)—the true cost of money on a declining balance—is nearly double the quoted rate (an add-on of 0.59% equals roughly 13% per annum EIR). Additionally, BDO charges a Cash Availment Fee (usually PHP 200 to PHP 250 per transaction), which is typically billed on your first statement and is not factored into the monthly amortization itself.",
  exampleCalculation: "Example: You have a BDO Installment Card with an available limit of PHP 200,000. You need PHP 100,000 cash for tuition fees. BDO is offering you a promotional add-on rate of 0.59% per month for a 24-month term. Total Interest = 100,000 * 0.0059 * 24 = PHP 14,160. Total Amount Payable = 100,000 + 14,160 = PHP 114,160. Monthly Amortization = 114,160 / 24 = PHP 4,756.67. Every month for two years, exactly PHP 4,756.67 will be billed to your card. On your very first billing statement, you will also see a one-time Cash Availment fee of PHP 250. If you opted for a shorter 12-month term at the same rate, your total interest would be halved to PHP 7,080, but your monthly payment would increase to PHP 8,923.33. The calculator helps you balance your monthly cash flow against the total interest cost.",
  philippinesContext: "BDO Unibank, the largest bank in the Philippines, created the Installment Card to dominate the consumer cash loan market. Unlike regular credit cards that charge high cash advance fees (usually 3% to 5% upfront plus 2% to 3% monthly compounding interest), the Installment Card acts as a revolving personal loan facility. It is incredibly popular among middle-class Filipinos because once the card is approved and the credit limit is set, the cardholder can withdraw cash multiple times (up to their limit) without needing to re-apply or submit new income documents. You simply call BDO, use BDO Online, or withdraw at a BDO ATM. Under Bangko Sentral ng Pilipinas (BSP) regulations, banks must be transparent about interest rates, which is why BDO always discloses the Effective Interest Rate (EIR) alongside the add-on rate in their promotional texts. Failing to pay the exact monthly amortization on time will result in the loss of the promotional rate, and the outstanding balance will be subjected to standard, much higher credit card finance charges.",
  faqs: [
    { question: "What is the interest rate for BDO Installment Card Cash Availment?", answer: "The regular monthly add-on rate is usually around 1.00% to 1.50%. However, BDO frequently sends SMS and email promotions to cardholders offering special low rates ranging from 0.45% to 0.70% per month, depending on your credit standing and the loan term chosen." },
    { question: "How do I avail of cash using my BDO Installment Card?", answer: "You can avail of cash via three methods: 1) Calling the BDO Customer Contact Center. 2) Logging into BDO Online Banking and transferring the funds to your BDO savings account. 3) Withdrawing directly from any BDO ATM (subject to daily ATM withdrawal limits)." },
    { question: "Can I use the BDO Installment Card for shopping?", answer: "Yes, you can swipe the BDO Installment Card at any Mastercard-affiliated merchant. However, any straight purchase is automatically converted into an installment plan (usually 3 to 6 months) at the bank's prevailing add-on rate. It does not function like a normal credit card with a 30-day grace period." },
    { question: "What are the available repayment terms?", answer: "BDO typically offers flexible repayment terms for Cash Availments of 6, 12, 18, 24, and 36 months. During special promotions, they may even offer terms up to 48 or 60 months for large loan amounts." },
    { question: "Is there a fee to withdraw cash?", answer: "Yes, there is a fixed Cash Availment Processing Fee. It is usually PHP 200 or PHP 250 per transaction, regardless of the loan amount. This fee is charged to your card and will appear on your first billing statement along with your first monthly amortization." },
    { question: "What happens if I don't pay the full monthly amortization?", answer: "If you pay less than the exact billed monthly amortization, the unpaid portion of the installment will be subjected to the standard credit card finance charge (currently around 3% per month as per BSP caps), which compounding interest will quickly inflate your debt." },
    { question: "Can I pay off the installment plan early?", answer: "Yes, you can request an Installment Acceleration or Pre-termination. However, BDO charges a pre-termination fee (typically 5% of the remaining principal balance or PHP 300, whichever is higher). You must call BDO to process this; you cannot simply overpay your bill." },
    { question: "How fast is the cash credited to my account?", answer: "If you avail via BDO Online Banking and transfer to a BDO Savings or Checking account, the funds are usually credited almost instantly or within a few hours. Transfers to non-BDO accounts via InstaPay or PESONet may take 1 to 3 banking days." },
    { question: "Is the limit on the Installment Card the same as my other BDO credit cards?", answer: "If you have a Shared Limit arrangement with other BDO credit cards, the Installment Card shares that maximum limit. However, BDO sometimes issues the Installment Card with a completely separate, dedicated credit line. Check your card carrier or call customer service to verify." },
    { question: "Do I need to submit an ITR every time I withdraw cash?", answer: "No. That is the primary advantage of the Installment Card. Once the card is approved and you have an available credit limit, you can avail of cash instantly without submitting any new income documents, payslips, or ITRs." },
    { question: "What is the minimum amount for Cash Availment?", answer: "The minimum amount for a Cash Availment transaction is typically PHP 10,000. For amounts below this, you cannot use the installment facility and would be subject to standard cash advance rules, though the Installment Card is explicitly designed for these larger minimums." },
    { question: "Why is the Effective Interest Rate (EIR) higher than the add-on rate?", answer: "The add-on rate computes interest on the original full amount for the entire term. However, because you are paying off a portion of the principal every month, your actual outstanding debt is decreasing. Paying interest based on the full initial amount means the true cost (EIR) is much higher." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 11 complete');
