import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("psbank-car-loan-calculator", {
  description: "Calculate your monthly installment, required equity, and total interest cost for a PSBank Auto Loan. Philippine Savings Bank (PSBank), the thrift banking arm of the Metrobank Group, is renowned in the Philippines for its highly aggressive and fast-approving auto loan products. In fact, PSBank pioneered the '1-Day Auto Loan Approval' process, making it incredibly popular among Filipinos eager to drive home a new car quickly. However, the speed of approval should not overshadow the necessity of careful financial planning. This calculator is an essential tool for prospective car buyers, allowing them to instantly model different loan scenarios before stepping into a dealership. By inputting the vehicle's selling price, your planned down payment, and your desired repayment term, the calculator computes the exact monthly amortization you will face for the next 3 to 5 years. Crucially, it also reveals the total interest paid over the life of the loan. This transparency helps you decide whether to stretch your budget for a higher down payment today to save tens of thousands of pesos in compounding add-on interest tomorrow.",
  formulaExplanation: "PSBank calculates auto loan amortizations using the standard add-on interest method prevalent in the Philippine automotive financing industry. First, you determine the Amount Financed: Amount Financed = Selling Price - Down Payment (which must be at least 20%). Next, you calculate the Total Interest: Total Interest = Amount Financed * Annual Add-on Rate * Term in Years. Finally, you compute the Monthly Amortization: Monthly Amortization = (Amount Financed + Total Interest) / Total Number of Months. Because the interest is 'added on' upfront based on the original principal rather than a declining balance, the Effective Interest Rate (EIR) is significantly higher than the quoted add-on rate. PSBank often runs 'Prime Rebate' promos, where borrowers who pay their monthly amortization in advance of the due date receive a small interest rebate, effectively lowering the overall cost of the loan if you are a disciplined payer.",
  exampleCalculation: "Example: You are purchasing a brand-new MPV priced at PHP 1,200,000. You make a 20% down payment (PHP 240,000), leaving an Amount Financed of PHP 960,000. You choose a 60-month (5-year) term. The bank's 5-year total add-on rate is approximately 27.28% (or 5.45% per year). Total Interest = 960,000 * 0.2728 = PHP 261,888. Total Amount Payable to the bank = 960,000 + 261,888 = PHP 1,221,888. Monthly Amortization = 1,221,888 / 60 = PHP 20,364.80 per month. By utilizing this calculator, you can clearly see that financing a 1.2M car over 5 years actually costs you PHP 1,461,888 in total (Down Payment + Total Payable). If you shortened the term to 36 months with a 15% add-on rate, your monthly payment increases to PHP 30,666.67, but your total interest drops drastically to PHP 144,000, saving you nearly PHP 118,000.",
  philippinesContext: "In the highly competitive Philippine automotive market, PSBank stands out by aggressively marketing to both corporate employees and Overseas Filipino Workers (OFWs) through streamlined documentary requirements and rapid processing. The Bangko Sentral ng Pilipinas (BSP) regulates all auto loans, mandating a minimum 20% down payment to protect the banking system from mass defaults. However, dealerships often entice buyers with 'Zero Downpayment' or 'Low Downpayment' promos. It is critical to understand that these promos usually involve the dealer subsidizing the bank's 20% requirement by inflating the car's base price or applying the highest possible add-on interest rate, meaning you pay significantly more in the long run. Furthermore, getting approved for a PSBank Auto Loan requires passing a strict capacity-to-pay assessment: your monthly car payment generally should not exceed 30% to 40% of your gross monthly household income. A solid credit history (no unpaid credit cards or canceled loans) is mandatory for approval.",
  faqs: [
    { question: "What is the minimum down payment for a PSBank Auto Loan?", answer: "The standard minimum down payment required is 20% of the vehicle's selling price. While some dealers advertise lower down payments, the bank still requires 20% on their end, which the dealer covers through promotional subsidies that often result in higher monthly amortizations for the buyer." },
    { question: "How fast is PSBank's loan approval process?", answer: "PSBank is famous for its '1-Day Auto Loan Approval'. If you submit a complete set of required documents (ITR, COE, valid IDs, filled-out application form) early in the day, you can receive a credit decision via SMS or email within 24 hours." },
    { question: "What is the PSBank Prime Rebate?", answer: "The Prime Rebate is a unique feature where PSBank gives you a discount or rebate on your loan interest if you pay your monthly amortization in advance of your actual due date. The earlier you pay, the higher the rebate credited to your account." },
    { question: "Can I apply for a PSBank Auto Loan if I am an OFW?", answer: "Yes, OFWs are a major target market for PSBank. You will need to provide your latest POEA-authenticated contract, proof of remittance, and designate a local co-maker or attorney-in-fact (usually a spouse or immediate relative) to sign the loan documents in the Philippines." },
    { question: "What are the loan terms available?", answer: "For brand-new cars, PSBank offers repayment terms of 12, 24, 36, 48, and 60 months. For pre-owned vehicles, the maximum term is usually shorter, depending on the age and condition of the car being financed." },
    { question: "What income do I need to get approved?", answer: "Banks use a debt-to-income ratio. Your monthly car payment should ideally not exceed 30% to 40% of your gross monthly income. For a PHP 15,000 monthly amortization, your gross monthly income should be around PHP 40,000 to PHP 50,000." },
    { question: "Does PSBank finance secondhand or used cars?", answer: "Yes, PSBank offers financing for pre-owned cars, either from independent used car dealers or through their own inventory of repossessed vehicles (PSBank Pre-Owned). Note that interest rates for used cars are higher than those for brand-new units." },
    { question: "What are Chattel Mortgage fees?", answer: "A chattel mortgage is the legal process of registering the car as collateral with the Registry of Deeds. This allows the bank to repossess the car if you stop paying. You must pay this fee upfront before the car is released, usually costing 1% to 2% of the loan amount." },
    { question: "Do I need Comprehensive Car Insurance?", answer: "Yes, it is strictly mandatory. You must have comprehensive insurance for the entire duration of the loan, with PSBank listed as the 'mortgagee'. If you fail to renew your insurance annually, the bank will force-place a policy and charge it to your account." },
    { question: "Can I pay off my auto loan early?", answer: "Yes, early settlement is allowed. However, PSBank will charge a pre-termination processing fee (typically a percentage of the outstanding balance). You must request an official payoff computation from the bank, as you cannot simply pay the remaining balance on your amortization schedule." },
    { question: "What happens if I miss a payment?", answer: "Late payments incur severe penalty charges (around 3% to 5% per month on the past due amount). If you default for several consecutive months (usually 2 to 3 months), the bank will initiate repossession of the vehicle, and your credit score will be ruined." },
    { question: "How do I get my car's title (OR/CR) after paying the loan?", answer: "Once your loan is fully paid, PSBank will issue a 'Cancellation of Chattel Mortgage' document. You must take this document to the Registry of Deeds and then to the LTO to officially remove the bank's encumbrance from your Certificate of Registration (CR)." }
  ]
});

upgrade("psslai-loan-calculator", {
  description: "Estimate your monthly amortization, net proceeds, and total interest for a PSSLAI (Public Safety Savings and Loan Association, Inc.) salary or multi-purpose loan. PSSLAI is a premier non-stock savings and loan association providing exclusive, low-interest financial services to the men and women of the Philippine National Police (PNP), Bureau of Fire Protection (BFP), Bureau of Jail Management and Penology (BJMP), and their civilian employees. Because PSSLAI's primary mandate is the financial welfare of its members rather than corporate profit, its loan interest rates are exceptionally competitive compared to commercial banks. This calculator empowers uniformed personnel to independently verify their loan computations before submitting an application at a PSSLAI branch or online. By inputting the desired loan amount, the specific interest rate for the loan type, and the repayment term (up to 60 months), users can determine their exact monthly payroll deduction. Crucially, this tool helps personnel ensure that the resulting monthly deduction complies with the government's mandatory 'net take-home pay' rule, preventing loan rejections and ensuring financial stability for their families.",
  formulaExplanation: "PSSLAI generally utilizes the diminishing balance method for its primary salary and multi-purpose loans, which is highly advantageous for borrowers. The formula is: M = P * [r * (1 + r)^n] / [(1 + r)^n - 1], where M is the monthly payment, P is the principal loan amount, r is the monthly interest rate (annual rate divided by 12), and n is the total number of months. Because interest is calculated only on the remaining unpaid principal each month, the total interest paid over the life of the loan is significantly lower than a flat add-on interest loan. However, borrowers must be aware of upfront deductions. PSSLAI deducts service/processing fees (usually 1% to 2%), mandatory Capital Contribution retention (a forced savings mechanism), and sometimes advance insurance premiums (CISP) directly from the gross loan amount. Therefore, the net proceeds credited to the borrower's PSSLAI savings account or ATM card will always be lower than the approved gross loan amount.",
  exampleCalculation: "Example 1 (Multi-Purpose Loan): A PNP officer applies for a PHP 200,000 multi-purpose loan at a 9% per annum interest rate, payable over 36 months (3 years). The monthly interest rate is 0.75% (0.0075). Monthly Amortization = 200,000 * [0.0075 * (1.0075)^36] / [(1.0075)^36 - 1] = PHP 6,359.95. Total Payment over 36 months = PHP 228,958.07. Total Interest Paid = PHP 28,958.07. Example 2 (Factoring Deductions): An officer applies for a PHP 50,000 short-term emergency loan. If PSSLAI applies a 1% service fee (PHP 500) and a 1% Capital Contribution retention (PHP 500), a total of PHP 1,000 is deducted upfront. The net proceeds deposited into the officer's account will be PHP 49,000, while the monthly amortization will be calculated based on the full PHP 50,000 principal. The calculator helps clarify these initial deductions versus the ongoing monthly payments.",
  philippinesContext: "PSSLAI operates under the strict regulation of the Bangko Sentral ng Pilipinas (BSP) and caters specifically to the public safety sector. Its integration with the finance centers of the PNP, BFP, and BJMP allows for seamless automatic salary deductions. This payroll integration virtually eliminates default risk, which is why PSSLAI can offer such low interest rates and declare high annual dividends on members' Capital Contributions. A critical legal constraint for all uniformed personnel applying for loans is the General Appropriations Act (GAA), which mandates a minimum 'net take-home pay' (NTHP). As of recent GAA provisions, personnel must retain a specific minimum amount (e.g., PHP 5,000 or PHP 6,000) in their monthly payslip after all statutory deductions (GSIS, PhilHealth, Pag-IBIG) and loan amortizations are subtracted. If an applied PSSLAI loan causes the borrower's NTHP to fall below this mandatory threshold, the finance center will not process the deduction, and PSSLAI will decline or reduce the loan amount. Therefore, accurate self-computation is essential before application.",
  faqs: [
    { question: "What is the interest rate for PSSLAI loans?", answer: "PSSLAI interest rates are highly competitive, typically ranging from 6% to 12% per annum, depending on the specific loan product (e.g., Salary Loan, Emergency Loan, Vehicle Loan) and the repayment term. These rates are usually computed using the diminishing balance method." },
    { question: "Who is eligible to apply for a PSSLAI loan?", answer: "Eligible borrowers include active and retired personnel of the Philippine National Police (PNP), Bureau of Fire Protection (BFP), and Bureau of Jail Management and Penology (BJMP) who are regular members with sufficient Capital Contribution. Civilian employees of these bureaus may also be eligible." },
    { question: "How long is the repayment term for PSSLAI loans?", answer: "Repayment terms for regular multi-purpose and salary loans generally range from 12 months (1 year) up to 60 months (5 years). Shorter-term emergency loans or promotional loans may have specific shorter terms (e.g., 6 months)." },
    { question: "Are there hidden fees when taking a PSSLAI loan?", answer: "PSSLAI is transparent with its deductions. Standard upfront deductions from the gross loan amount include a processing/service fee (around 1% to 2%), mandatory Capital Contribution retention to build your savings, and Credit Insurance (CISP) to protect the loan." },
    { question: "What is the mandatory 'net take-home pay' rule?", answer: "The General Appropriations Act (GAA) requires all government personnel to retain a minimum net take-home pay (e.g., PHP 5,000 or PHP 6,000) after all mandatory and loan deductions. PSSLAI cannot approve a loan if the resulting amortization violates this rule." },
    { question: "Can I renew or top-up my PSSLAI loan before it is fully paid?", answer: "Yes, PSSLAI allows loan renewal (top-up) once you have paid a required percentage or number of months of the existing loan. The outstanding principal balance of the old loan is simply deducted from the gross proceeds of the new loan." },
    { question: "Is PSSLAI interest add-on or diminishing?", answer: "For its primary salary loans, PSSLAI uses the diminishing balance method. This means interest is calculated only on the remaining unpaid principal each month, which is much cheaper for the borrower than the flat add-on method used by most private lending institutions." },
    { question: "How are PSSLAI loans paid?", answer: "Repayment is highly convenient. It is done through an automatic salary deduction arrangement with the respective finance centers of the PNP, BFP, or BJMP. For pensioners, it is deducted directly from their monthly pension." },
    { question: "How long does it take to release PSSLAI loan proceeds?", answer: "For regular loans with complete requirements and verified salary deduction capacity, PSSLAI typically processes and releases the loan proceeds within 1 to 3 working days. Funds are credited directly to the member's PSSLAI savings account or ATM." },
    { question: "Can retired personnel apply for PSSLAI loans?", answer: "Yes, retired PNP, BFP, and BJMP personnel receiving a regular pension can apply for pension-based loans. The monthly amortization is automatically deducted from their pension, and the loan terms are structured to accommodate fixed-income retirees." },
    { question: "Can I pay off my PSSLAI loan early?", answer: "Yes, you can fully pay off your loan before the end of the term. Because PSSLAI uses diminishing interest, paying early means you avoid paying the interest that would have accrued over the remaining months. There is usually no pre-termination penalty." },
    { question: "What happens if I am discharged from the service?", answer: "If a member is separated, discharged, or dismissed from the service, the outstanding loan balance becomes immediately due and demandable. PSSLAI has the right to deduct the outstanding balance from the member's Capital Contribution, savings, or terminal leave benefits." }
  ]
});

upgrade("rcbc-car-loan-calculator", {
  description: "Calculate your monthly installment, required down payment, and total interest for an RCBC Auto Loan. The Rizal Commercial Banking Corporation (RCBC) is one of the largest universal banks in the Philippines, offering highly competitive auto financing packages for brand-new and pre-owned vehicles. Buying a car is a significant financial milestone, and understanding the long-term cost of borrowing is crucial. This calculator is designed to help prospective buyers determine exactly how much they can afford before visiting a car dealership. By inputting the vehicle's selling price, your planned down payment, and the desired loan term, the tool computes the fixed monthly amortization you will pay to the bank. More importantly, it clearly displays the total interest charged over the life of the loan. Dealerships often mask the true cost of a car by focusing only on 'low monthly payments' stretched over 60 months. This tool empowers you to compare scenarios—such as paying a 30% down payment instead of the minimum 20%, or choosing a 36-month term instead of 60 months—allowing you to save tens of thousands of pesos in compounding add-on interest.",
  formulaExplanation: "RCBC Auto Loans utilize the add-on interest method, the standard for vehicle financing in the Philippines. First, compute the Amount Financed: Amount Financed = Selling Price - Down Payment. Next, calculate the Total Interest: Total Interest = Amount Financed * Annual Add-on Rate * Term in Years. Finally, calculate the Monthly Amortization: Monthly Amortization = (Amount Financed + Total Interest) / Total Number of Months. Because add-on interest is calculated on the original principal for the entire loan duration, the Effective Interest Rate (EIR)—the true cost of borrowing on a declining balance—is nearly double the quoted add-on rate. For example, a 5-year loan with a total add-on rate of 27% yields an EIR of roughly 10% per annum. RCBC also charges upfront processing fees, including Chattel Mortgage fees (to register the car as collateral) and mandatory Comprehensive Insurance premiums, which must be paid before the vehicle is released.",
  exampleCalculation: "Example 1 (Standard 5-Year Loan): You are buying a crossover SUV priced at PHP 1,500,000. You make a 20% down payment (PHP 300,000), leaving an Amount Financed of PHP 1,200,000. The bank's 5-year total add-on rate is 27.28%. Total Interest = 1,200,000 * 0.2728 = PHP 327,360. Total Payable = 1,527,360. Monthly Amortization = 1,527,360 / 60 = PHP 25,456 per month. Example 2 (Higher Down Payment, Shorter Term): You buy the same PHP 1,500,000 SUV but put down 30% (PHP 450,000), financing only PHP 1,050,000. You choose a 36-month term with a 15% add-on rate. Total Interest = 1,050,000 * 0.15 = PHP 157,500. Total Payable = 1,207,500. Monthly Amortization = 1,207,500 / 36 = PHP 33,541.67. While the monthly payment is higher, you save nearly PHP 170,000 in total interest compared to the 5-year option. This calculator makes these financial trade-offs instantly clear.",
  philippinesContext: "RCBC is a major player in the Philippine auto loan market, frequently partnering with top automotive brands (Toyota, Mitsubishi, Nissan, Ford) to offer special promotional rates or free insurance packages. The Bangko Sentral ng Pilipinas (BSP) regulates auto lending, requiring banks to demand a minimum 20% down payment to minimize the risk of default. While car dealers often advertise 'Zero Downpayment' or 'Low Downpayment' promos, these are usually dealer-subsidized schemes where the base price of the car is inflated, or the highest possible interest rate is applied, resulting in a much more expensive loan. Getting approved by RCBC requires a solid credit history and sufficient income capacity. The standard banking rule applies: your monthly car amortization should not exceed 30% to 40% of your gross monthly household income. Once approved, the bank registers a Chattel Mortgage on the vehicle and retains the original OR/CR until the loan is fully paid.",
  faqs: [
    { question: "What is the minimum down payment for an RCBC Auto Loan?", answer: "The standard minimum down payment required by RCBC is 20% of the vehicle's selling price. For certain high-end vehicles or commercial trucks, the bank may require a higher down payment of 30% or more depending on the borrower's credit profile." },
    { question: "What are the available loan terms for RCBC?", answer: "For brand-new vehicles, RCBC offers flexible repayment terms ranging from 12 months (1 year) up to 60 months (5 years). For pre-owned vehicles, the maximum term is typically shorter, usually 36 or 48 months, depending on the car's age." },
    { question: "Does RCBC finance secondhand or used cars?", answer: "Yes, RCBC provides auto loans for pre-owned vehicles. However, the interest rates for used cars are significantly higher than those for brand-new cars, and the vehicle must meet age requirements (usually not older than 5 years at loan maturity)." },
    { question: "What income is required to get approved for an RCBC Auto Loan?", answer: "Banks use a debt-to-income (DTI) ratio for approval. Generally, your monthly car payment should not exceed 30% to 40% of your gross monthly income. For a PHP 20,000 monthly amortization, your gross monthly income should be at least PHP 50,000 to PHP 66,000." },
    { question: "What are Chattel Mortgage fees?", answer: "A chattel mortgage is the legal registration of your vehicle as collateral with the Registry of Deeds. This allows the bank to legally repossess the car if you default on payments. The fee is typically 1% to 2% of the loan amount and must be paid upfront." },
    { question: "Do I need Comprehensive Car Insurance?", answer: "Yes, comprehensive insurance is strictly mandatory for the entire duration of the loan. The policy must list RCBC as the 'mortgagee'. If you fail to renew your insurance, the bank will force-place a policy and bill the premium to your account." },
    { question: "What is an 'All-in Promo' offered by dealers?", answer: "An 'All-in Promo' bundles the down payment, Chattel Mortgage fees, 1st-year Comprehensive Insurance, and 3-year LTO Registration into one initial cash payment. However, these promos often come with higher add-on interest rates hidden in the monthly amortization." },
    { question: "Can I pay off my RCBC auto loan early?", answer: "Yes, early settlement is permitted. However, banks charge a pre-termination fee (typically a percentage of the outstanding principal balance). You must request an official payoff computation from RCBC to determine the exact amount needed to close the loan." },
    { question: "What happens if I miss a monthly payment?", answer: "Late payments will incur penalty charges (usually 3% to 5% per month on the past due amount). If you default for several consecutive months (usually 60 to 90 days), RCBC will initiate repossession proceedings, and your credit record will be severely damaged." },
    { question: "How fast is the RCBC loan approval process?", answer: "If you submit complete documentary requirements (ITR, payslips, COE, valid IDs), standard processing usually takes 1 to 3 banking days. Self-employed individuals may experience longer processing times due to business verification." },
    { question: "What is the difference between add-on rate and effective interest rate (EIR)?", answer: "The add-on rate calculates interest on the full original loan amount for the entire term. The EIR reflects the true cost of the loan on a declining balance. Because you are constantly paying down the principal, the EIR is always much higher than the add-on rate." },
    { question: "How do I get my OR/CR after fully paying the loan?", answer: "Once the loan is fully settled, RCBC will issue a 'Cancellation of Chattel Mortgage'. You must take this document to the Registry of Deeds and the LTO to officially remove the bank's encumbrance from your vehicle's Certificate of Registration (CR)." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 12 complete');
