import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, (_, g1, g2, g3) => g1 + data.description + g3);
  
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, (_, g1, g2, g3) => g1 + data.formulaExplanation + g3);
  
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, (_, g1, g2, g3) => g1 + data.exampleCalculation + g3);
  
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, (_, g1, g2, g3) => g1 + data.philippinesContext + g3);
  
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, (_, g1, g2) => g1 + '\n' + faqStr + ',\n    ' + g2);
  console.log(`Upgraded: ${slug}`);
}

upgrade("arknights-recruitment-calculator", {
  description: "Maximize your chances of recruiting high-rarity Operators in Arknights using this comprehensive Recruitment Tag Calculator. Arknights, a highly tactical tower defense gacha game by Hypergryph, features a unique 'Public Recruitment' system that allows free-to-play players to acquire powerful 4-star, 5-star, and even ultra-rare 6-star Operators without spending premium currency (Orundum). However, this system relies entirely on combining specific 'Tags' (e.g., 'Guard', 'Survival', 'Top Operator') that randomly appear on your recruitment screen. Certain tag combinations guarantee a high-rarity unit, but if you don't recognize the combination, you might accidentally refresh the tags or pick a combination that drops a common 3-star unit. This calculator completely removes the guesswork. By inputting the 5 tags currently available on your screen, it instantly cross-references the entire Arknights database to show you every possible Operator combination, highlighting the exact tag combinations that guarantee a 4-star or higher. It is an absolute necessity for any Arknights player looking to optimize their roster efficiently.",
  formulaExplanation: "The underlying logic of the Arknights recruitment system is essentially a database query with intersection filters. The calculator maintains a vast, continuously updated database of every recruitable Operator and their assigned tags. When you select a set of tags (up to 3 can be chosen in-game), the calculator performs an intersection search: it finds the Operators that possess ALL of the selected tags simultaneously. If a specific tag combination (like 'Defender' + 'DPS') only yields one possible 5-star Operator (Vulcan) and no 3-star or 4-star Operators share that exact combination, then selecting those tags guarantees Vulcan (assuming the tags don't 'drop' or cross out during the recruitment timer). The calculator sorts these results by guaranteed rarity, ensuring you immediately see the most valuable combinations first. Setting the recruitment time to 9:00:00 eliminates 1-star and 2-star Operators from the pool, which the calculator assumes as the default state for maximizing high-tier pulls.",
  exampleCalculation: "Example 1 (Guaranteed 5-Star): You receive the tags: 'Guard', 'Melee', 'Survival', 'AoE', and 'Senior Operator'. Selecting 'Senior Operator' guarantees a 5-star, but which one? The calculator shows that combining 'Senior Operator' + 'Survival' narrows the pool to Specter or Indra. Example 2 (Hidden Gem): You receive 'Supporter', 'Debuff', 'Melee', 'Fast-Redeploy', and 'DPS'. Without the 'Senior Operator' tag, you might just pick 'DPS' and get a 3-star. However, the calculator reveals that combining 'Melee' + 'Debuff' + 'Fast-Redeploy' guarantees the 5-star Operator Projekt Red, as she is the only unit in the entire game with that exact triad of tags. Example 3 (The Jackpot): You see the extremely rare 'Top Operator' tag. The calculator will show you how to combine it with your other tags (like 'Healing' to guarantee Shining or Nightingale) to target the specific 6-star Operator your squad desperately needs.",
  philippinesContext: "Arknights holds a dedicated and highly active player base in the Philippines, particularly among fans of anime-style aesthetics and deeply strategic gameplay. Unlike casual auto-battlers, Arknights requires intense critical thinking, and the Filipino community frequently congregates in massive Facebook groups (like Arknights Philippines) and Discord servers to share guides, flex their gacha pulls, and ask for recruitment tag advice. Because the game's premium currency (Originite Prime) can be expensive when converted to Philippine Pesos, free-to-play (F2P) optimization is deeply ingrained in the local community culture. Missing a 'Top Operator' tag or failing to recognize a guaranteed 5-star combination is considered a massive, painful mistake. This calculator is a daily-use tool for Filipino 'Dokutahs' (the player's title in-game), running constantly on a second monitor or mobile browser while they clear their daily missions, ensuring they squeeze every ounce of value out of their free recruitment permits.",
  faqs: [
    { question: "What is the Public Recruitment system in Arknights?", answer: "Public Recruitment is a free gacha system where players spend Recruitment Permits and LMD (in-game gold) to hire Operators. By selecting specific descriptive tags (like 'Sniper' or 'Healing') and setting a timer, players can narrow down the pool of potential Operators." },
    { question: "How does this tag calculator work?", answer: "You simply click the tags that currently appear on your in-game recruitment screen. The calculator instantly searches its database and displays every possible combination of those tags, showing you exactly which Operators you can get, sorted by rarity." },
    { question: "Why did a tag get crossed out in-game?", answer: "Tags have a random chance to 'drop' or cross out when the recruitment finishes, meaning the game ignores that tag when selecting your Operator. Setting the recruitment timer to the maximum 9:00:00 significantly reduces the chance of tags dropping." },
    { question: "What does the 'Top Operator' tag do?", answer: "The 'Top Operator' tag is extremely rare and is the ONLY way to recruit a 6-star Operator through Public Recruitment. If you see this tag, you MUST set the timer to exactly 9:00:00 to guarantee it won't drop. Never ignore this tag." },
    { question: "What does the 'Senior Operator' tag do?", answer: "Similar to the Top Operator tag, the 'Senior Operator' tag guarantees a 5-star Operator. You should always select this tag and set the timer to 9 hours, unless a better specific combination guarantees a 5-star you want more." },
    { question: "Can I get every Operator from Recruitment?", answer: "No. The Public Recruitment pool only contains a specific subset of Operators. New Operators are usually added to the recruitment pool several months or a year after their initial release banner. Limited/Event-exclusive Operators are never added." },
    { question: "What is the 'Robot' tag?", answer: "The 'Robot' tag guarantees a 1-star utility robot (like Lancet-2 or Castle-3). To get a robot, you MUST set the timer to exactly 3:50:00. If you set it to 9 hours, the game removes 1-star units from the pool, and the Robot tag will cross out." },
    { question: "Are guaranteed 4-star combinations worth it?", answer: "Yes! 4-star Operators yield 'Yellow Certificates' (Distinctions) when you get duplicates of them. You can use these highly valuable certificates in the shop to buy premium 6-star Operators directly. Farming 4-stars is a core strategy for F2P players." },
    { question: "What if none of my tags guarantee a 4-star or higher?", answer: "If your tags only yield 3-star Operators (like 'Vanguard' + 'Melee'), you can either just pick a random tag for a quick 3-star, or use an 'Expedited Plan' to refresh the tags completely if you have the Office base facility upgraded." },
    { question: "Is the calculator updated with the latest Operators?", answer: "Yes, the calculator's database is updated whenever the Arknights global server patches new Operators into the Public Recruitment pool. This usually happens during major game anniversaries or half-anniversaries." },
    { question: "Why did I get a 3-star when the calculator said 4-star?", answer: "This happens if you did not set the timer to 9:00:00, causing one of your critical tags to drop/cross out. For example, if you chose 'Shift' (guarantees 4-star) but set the timer to 1 hour, the 'Shift' tag likely dropped, leaving you with a random 3-star." },
    { question: "Who are Vulcan and Indra?", answer: "Vulcan and Indra are two 5-star Operators that are exclusively available through Public Recruitment. They cannot be pulled from standard premium headhunting banners. Players use specific tag combinations (like 'Survival' + 'Defender' for Vulcan) to hunt them." }
  ]
});

upgrade("axie-infinity-energy-calculator", {
  description: "Master your arena battles in Axie Infinity with this ultimate Energy and Card Tracking Calculator. In Axie Infinity: Classic (v2) and Axie Infinity: Origins, energy management is the single most defining factor between a top-tier leaderboard player and an average grinder. Unlike traditional turn-based RPGs where your mana regenerates fully, Axie Infinity features a strict, carrying-over energy economy. You start with a set amount of energy, gain a fixed amount per turn, and must spend it carefully to play cards. Crucially, you must also mentally track your opponent's energy. If you know your opponent has 0 energy, you know they cannot attack you forcefully this turn, allowing you to save your shields or play utility cards safely. If you lose track and assume they are out of energy when they actually saved 4, they can easily wipe out your frontline tank. This calculator acts as a digital notepad, allowing you to precisely track the opponent's energy gains, spends, and card destructions (like the 'Destroy Energy' effect of a Serious card), giving you a massive tactical advantage in the Arena.",
  formulaExplanation: "Tracking energy requires a continuous, turn-by-turn arithmetic equation. In Axie Classic, both players start Round 1 with 3 Energy. At the start of every subsequent round, they gain 2 Energy. The base formula for the opponent's current energy is: Previous Round Energy + 2 (Round Gain) + Energy Stolen/Gained from Cards - Energy Destroyed by You - Cards Played by Opponent. The maximum energy cap is 10. For example, if they start with 3, play 2 cards (-2), and you don't destroy any, they end Round 1 with 1 energy. Going into Round 2, they gain 2, starting with 3 energy. The complexity arises from specific card effects. If their Axie uses 'Vegetal Bite' (Serious part) and you have energy, they steal 1 (+1 for them, -1 for you). If they use 'Luna Absorb' (Cottontail part), they gain 1 energy for free. The calculator simplifies this into '+' and '-' buttons for cards played, energy gained, and energy destroyed, doing the math instantly so you can focus on strategy.",
  exampleCalculation: "Example 1 (The Pass Strategy): Round 1 begins. Opponent starts with 3 energy. They play 0 cards (they pass the turn). End of Round 1: they have 3 energy. Start of Round 2: they gain 2 energy. They now have 5 energy. Knowing they have 5 energy means they can unleash a devastating 4-card combo on your tank. You must play heavy shields. Example 2 (Energy Steal): Round 1 begins (3 energy). Opponent plays 2 cards. One of those cards is Vegetal Bite, which steals 1 energy from you. Calculation: 3 (start) - 2 (cards spent) + 1 (stolen) = 2 energy remaining. Start of Round 2: 2 + 2 (gain) = 4 energy. Example 3 (Nimo Spam): Opponent uses a Nimo card (0 cost, gains 1 energy) and two 1-cost attack cards. Start with 3. -0 (Nimo) + 1 (Nimo effect) - 1 (attack) - 1 (attack) = 2 energy remaining. The calculator tracks these micro-transactions flawlessly.",
  philippinesContext: "Axie Infinity triggered a massive socio-economic phenomenon in the Philippines during 2020-2021, creating the global 'Play-to-Earn' (P2E) model. Millions of Filipinos, from students in Manila to tricycle drivers in provincial barangays, became 'Scholars'—borrowing Axie teams from 'Managers' to farm Smooth Love Potion (SLP). While the hype has cooled and transitioned into Axie Origins, the Philippines remains the undisputed epicenter of the global Axie community. Professional Filipino esports teams dominate international Axie tournaments. For the average Filipino scholar trying to climb the Arena ranks to hit their daily SLP quota, energy tracking is non-negotiable. Missing an energy count often means losing an Arena match, which directly results in lower MMR (Matchmaking Rating) and less SLP earned—literally equating to lower real-world income. This calculator is a vital tool for local guilds and independent players, serving as an essential 'cheat sheet' for maximizing win rates and profitability in the highly competitive digital arena.",
  faqs: [
    { question: "Why is energy tracking important in Axie Infinity?", answer: "Knowing exactly how much energy your opponent has allows you to predict their next move. If they have 0 energy, they can't attack, so you shouldn't waste shields. If they have 4+ energy, they can kill your Axie, so you must defend or sacrifice it." },
    { question: "How much energy do you start with in Axie Classic?", answer: "In Axie Infinity Classic (v2), both players start Round 1 with exactly 3 Energy and draw 6 cards." },
    { question: "How much energy do you gain per round?", answer: "In Classic, you gain exactly 2 Energy at the beginning of every round after Round 1. You also draw 3 new cards." },
    { question: "What is the maximum energy you can hold?", answer: "The maximum energy cap is 10. If an opponent saves energy and hits 10, any further energy gained (from rounds or cards) is wasted." },
    { question: "How do 0-cost cards affect energy tracking?", answer: "0-cost cards (like Nimo, Bidens, or Cuckoo) do not consume energy when played. If your opponent plays two 1-cost cards and one 0-cost card, you only subtract 2 energy from their total." },
    { question: "What happens when an opponent uses a 'Steal Energy' card?", answer: "If they use a card like Vegetal Bite (Serious) and you have at least 1 energy saved, they steal it. This means they effectively gain +1 energy, and you lose -1 energy. If you have 0 energy, they steal nothing." },
    { question: "What is the difference between 'Destroy' and 'Steal' energy?", answer: "Destroying energy (e.g., using a Bug Splat/Goda card) simply removes 1 energy from the opponent's pool. Stealing energy removes 1 from them AND adds 1 to your pool. Tracking these specific effects is crucial." },
    { question: "Do I need to track cards as well as energy?", answer: "Yes, advanced players track both. An opponent can hold a maximum of 12 cards. If they have 5 energy but only 2 cards in hand, their threat level is limited by their lack of cards, not their lack of energy." },
    { question: "Does this calculator work for Axie Infinity: Origins?", answer: "Axie Origins completely revamped the energy system. In Origins, energy does NOT carry over to the next turn (unless using specific retain mechanics). This calculator is primarily designed for the persistent energy economy of Axie Classic." },
    { question: "How do I use the calculator during a fast-paced match?", answer: "Most players keep the calculator open on a second monitor or a smartphone next to their PC. As the opponent plays cards during the combat phase, quickly tap the '-' buttons for cards spent and '+' buttons for energy gained." },
    { question: "What is an 'Energy Pass' strategy?", answer: "This is a common tactic where a player intentionally plays 0 cards in Round 1 or Round 2 to stockpile 5 to 7 energy. This allows them to unleash a massive, unstoppable combo in Round 3 to instantly kill an opposing tank." },
    { question: "Can I get banned for using an energy calculator?", answer: "No. Using a manual, web-based energy calculator is completely legal and cannot result in a ban. It does not interact with the game client or read game data; it simply replaces you doing the mental math or writing it on a piece of paper." }
  ]
});

upgrade("ragnarok-stat-calculator", {
  description: "Optimize your character build in Ragnarok Online with this comprehensive Stat Calculator. For over two decades, Ragnarok Online (RO) has defined the MMORPG genre with its complex, unforgiving character progression system. Unlike modern MMOs where stats are automatically allocated, RO forces players to manually distribute stat points (STR, AGI, VIT, INT, DEX, LUK) every time they level up. Crucially, stat allocation in classic RO is permanent—make a mistake, and your character is ruined forever. A Knight with too much INT or a Wizard without enough DEX for cast time reduction will be utterly useless in high-level Guild vs Guild (WoE) battles. This calculator allows you to safely plan your build from Novice level 1 all the way to level 99/70 Transcendent classes. It accurately calculates exactly how many stat points you will earn at each level, how much each stat increment will cost (as the cost increases the higher the stat goes), and helps you hit crucial hidden 'Stat Bonuses' (like reaching 150 total DEX for instant casting).",
  formulaExplanation: "The math behind RO's stat system is heavily weighted by breakpoints and compounding costs. The cost to raise a stat increases based on its current level. The formula for the stat point cost is: Cost = Floor((Current Stat - 1) / 10) + 2. For example, raising a stat from 9 to 10 costs 2 points. Raising it from 98 to 99 costs a massive 11 points. The calculator tracks the total pool of points gained per base level. Furthermore, the calculator helps players hit essential 'Breakpoints'. For instance, every 10 points of total INT (Base + Job Bonus + Gear) grants a hidden bonus to Minimum Magic Attack. Every 150 total DEX results in 'Instacast' (zero variable cast time). The formula for variable cast time is: Base Cast Time * (1 - (DEX / 150)). If DEX is 150, the multiplier becomes 0. The calculator tallies your base stats and adds job class bonuses to ensure you perfectly hit these multiples without wasting a single precious point.",
  exampleCalculation: "Example 1 (The Instacast High Wizard): You want to achieve 150 total DEX for instant casting. Your High Wizard at Job Level 70 gets +16 DEX as a job bonus. You have gear (like an Apple of Archer and double Drops cards) that gives +14 DEX. Total bonus = +30 DEX. To hit 150, you need exactly 120 Base DEX. The calculator shows you that hitting 99 Base DEX (the maximum) leaves you at 129. You must adjust your gear or buffs (like Priest's Blessing for +10 DEX) to bridge the remaining gap. Example 2 (VIT Knight Immunity): In WoE, you want total immunity to Stun. The formula is: Chance to be stunned = Base Chance * (1 - (Total VIT / 100)). To reach 100 total VIT for immunity, if your Knight gets +10 VIT from job bonuses and +0 from gear, you must invest exactly 90 Base VIT. The calculator shows you exactly what level you must reach to afford 90 Base VIT.",
  philippinesContext: "Ragnarok Online (pRO) is arguably the most culturally significant video game in Philippine history. Launched locally in 2003 by Level Up! Games, it introduced an entire generation of Filipinos to online gaming, internet cafes (pisonets), and digital economies. The game is deeply embedded in local pop culture, spawning iconic songs (like Kamikazee's 'Chicksilog') and massive real-world events. Even today, classic RO private servers and official re-releases (like RO MSP) draw tens of thousands of Filipino players. In the highly competitive local server scene, 'War of Emperium' (WoE - the weekly guild vs guild castle siege) is taken incredibly seriously. Guild leaders require their members to have perfectly optimized stat builds. A 'Vit-Spear Knight' must hit exact HP thresholds to survive Asura Strikes, and a 'Professor' must hit exact DEX breakpoints to land Dispel instantly. This calculator is a nostalgic yet mandatory tool for Filipino gamers looking to dominate the Prontera PvP arenas, ensuring they don't 'mess up' a character they spent 300 hours grinding at High Orcs.",
  faqs: [
    { question: "Why is planning my stats so important in Ragnarok Online?", answer: "In classic Ragnarok Online, stat points are permanent. There is no 'reset' button (unless playing on specific modified private servers). If you allocate your points incorrectly, your character will be fundamentally broken, and you will have to create a brand new character and start from level 1." },
    { question: "What does STR (Strength) do?", answer: "STR increases your physical attack damage (ATK) for melee weapons like swords, axes, and daggers. It also increases your Maximum Weight capacity, allowing you to carry more health potions and loot." },
    { question: "What does AGI (Agility) do?", answer: "AGI increases your Attack Speed (ASPD), allowing you to hit faster. It also increases your Flee rate, which is your ability to dodge physical attacks completely. It is the primary stat for Assassins and Hunters." },
    { question: "What does VIT (Vitality) do?", answer: "VIT increases your Maximum HP and your HP regeneration rate. Crucially, it provides hidden defense against physical attacks and gives you resistance to negative status effects like Stun and Poison. 100 total VIT makes you immune to Stun." },
    { question: "What does INT (Intelligence) do?", answer: "INT increases your Magic Attack (MATK) and Magic Defense (MDEF). It also increases your Maximum SP (mana) and SP regeneration rate. It is the primary damage stat for Wizards and the primary healing stat for Priests." },
    { question: "What does DEX (Dexterity) do?", answer: "DEX increases your physical accuracy (HIT), ensuring your attacks don't miss. It is also the primary damage stat for bows and guns. For spellcasters, DEX is critical because it reduces variable cast time. 150 total DEX results in instant casting." },
    { question: "What does LUK (Luck) do?", answer: "LUK is a versatile stat that increases your Critical Hit rate (ignoring enemy defense and dodging), perfect dodge rate, and provides slight resistance to various status ailments. It also slightly increases forging and potion creation success rates." },
    { question: "What is the maximum base stat I can achieve?", answer: "For normal classes and 2-1/2-2 classes, the maximum base stat is 99. You cannot invest points past 99. However, your 'Total Stat' can exceed 99 through Job Bonuses, equipment, cards, and buffs (like Blessing or Agi Up)." },
    { question: "Why does it cost more points to upgrade a stat from 90 to 91 than 10 to 11?", answer: "Ragnarok uses a compounding cost system. Upgrading a stat from 1 to 11 costs 2 points per level. Upgrading from 91 to 99 costs 11 points per level. This forces players to specialize rather than having all stats perfectly equal." },
    { question: "What are Stat Breakpoints?", answer: "The game calculates many combat formulas based on multiples of 10. For example, every 10 points of total STR grants a massive bonus to melee ATK. If you have 99 STR, you are missing out. You want to aim for exactly 100 STR (Base + Bonus) to hit the breakpoint." },
    { question: "What is 'Instacast'?", answer: "Instacast (Instant Cast) occurs when a player reaches exactly 150 Total DEX. At this threshold, the variable casting time of spells (like a Wizard's Storm Gust or a Monk's Asura Strike) is reduced to zero, making the spell fire immediately." },
    { question: "Can I use this for Ragnarok Mobile (ROM) or Ragnarok Origin?", answer: "No. Mobile versions of Ragnarok have vastly different stat formulas, combat mechanics, and level caps. This calculator is designed specifically for the mechanics of classic PC Ragnarok Online (Pre-Renewal and early Renewal)." }
  ]
});

upgrade("nether-portal-calculator", {
  description: "Perfectly synchronize your Minecraft dimensions with this exact Nether Portal Calculator. Navigating the vast distances of a Minecraft survival world on foot or by boat can take hours of real-world time. The solution is the Nether Hub—a fast-travel network built in the hellish Nether dimension. However, the space-time physics between the Overworld and the Nether operate on a strict 8:1 ratio. Every single block you walk in the Nether equals exactly 8 blocks traveled in the Overworld. If you build a portal in your main base, and want to build a second portal to instantly teleport to a Stronghold 4,000 blocks away, you must mathematically calculate the exact X and Z coordinates to place the connecting portal inside the Nether. Failure to calculate these coordinates precisely results in 'portal linking failure,' where stepping through the Nether portal generates a completely new, random portal in the Overworld, stranding you miles away from your intended destination. This calculator takes your Overworld coordinates and instantly outputs the exact Nether coordinates (and vice versa), ensuring your fast-travel network links perfectly every single time without frustration.",
  formulaExplanation: "The mathematical translation between Minecraft dimensions is a strict ratio based on the game's coordinate grid (X, Y, Z). The X-axis represents East/West, the Z-axis represents North/South, and the Y-axis represents elevation (height). The critical rule is that the Y-axis (elevation) does not scale—it remains 1:1. Only the X and Z coordinates are subject to the 8:1 scale. To find Nether coordinates from the Overworld: Nether X = Floor(Overworld X / 8) and Nether Z = Floor(Overworld Z / 8). To find Overworld coordinates from the Nether: Overworld X = Nether X * 8 and Overworld Z = Nether Z * 8. The game's portal linking algorithm searches for the closest active portal within a 128-block radius (in the destination dimension) of the mathematically calculated coordinate. If no portal exists within that exact radius, the game forcefully generates a brand new one. Therefore, manually calculating and building the portal at the exact divided/multiplied coordinates guarantees the algorithm will link them perfectly, preventing the dreaded overlapping portal glitch.",
  exampleCalculation: "Example 1 (Overworld to Nether): Your main house is located at Overworld coordinates X: 800, Y: 64, Z: -400. You divide the X and Z by 8. 800 / 8 = 100. -400 / 8 = -50. You must go into the Nether and manually build your portal at Nether coordinates X: 100, Z: -50. (The Y coordinate can be anywhere, but matching Y: 64 helps prevent linking issues if portals are very close together). Example 2 (Nether to Overworld Fast Travel): You are building a tunnel in the Nether and reach coordinates X: 250, Z: 100. You want to know where this will exit in the Overworld. Multiply by 8. 250 * 8 = 2000. 100 * 8 = 800. Building a portal here will pop you out at Overworld X: 2000, Z: 800. You have effectively traveled 2,000 blocks in the Overworld by only walking 250 blocks in the Nether. The calculator handles these coordinate conversions, including negative numbers, instantly.",
  philippinesContext: "Minecraft remains incredibly popular in the Philippines, played by children on mobile devices (Bedrock Edition) and young adults running massive, modded Java Edition multiplayer servers. Due to the high cost of premium servers, Filipino friend groups often host local SMPs (Survival Multiplayer) on shared connections like PLDT or Globe, where server lag can make exploring vast distances tedious and dangerous. Building a highly efficient, ice-boat Nether Hub becomes a necessary community project to reduce server load and travel time. When different Filipino player 'factions' or barangays build their bases thousands of blocks apart on the server, they rely on exact coordinate calculators to safely link their bases to the central Nether Hub without accidentally overwriting a friend's portal. Precision is key; a miscalculated portal link can easily drop a player into a lava lake or generate a portal inside someone else's heavily guarded base, causing unwanted server drama.",
  faqs: [
    { question: "What is the ratio between the Nether and the Overworld?", answer: "The ratio is exactly 1:8. One block traveled in the Nether equals 8 blocks traveled in the Overworld along the X (East/West) and Z (North/South) axes. This is what allows for rapid fast-travel." },
    { question: "How do I find my coordinates in Minecraft?", answer: "If you are playing Java Edition on PC, press the F3 key to open the debug screen. Your X, Y, and Z coordinates will be listed on the left side. If you are playing Bedrock Edition (Console/Mobile), go to World Settings and toggle on 'Show Coordinates'." },
    { question: "Does the Y coordinate (height) matter?", answer: "The Y coordinate is 1:1 between dimensions; it is not divided by 8. While the game prioritizes X and Z for linking, if you have two portals very close to each other on the X/Z grid, the game will use the closest Y coordinate to determine which one to link to." },
    { question: "Why did my portal spawn me in a random cave?", answer: "When you light a portal, the game calculates the exact corresponding coordinates in the other dimension. It then searches a 128-block radius for an existing portal. If none exists, it searches for a safe, flat area to generate one. If the exact math coordinate is inside solid rock, it will spawn the portal in a nearby cave instead." },
    { question: "How do I perfectly link two portals?", answer: "1. Build Portal A in the Overworld (e.g., X:800, Z:800). 2. Light it and enter the Nether. 3. Break the portal the game generated for you in the Nether. 4. Go to the exact calculated coordinates (X:100, Z:100). 5. Build Portal B there and light it. They are now permanently synced." },
    { question: "What happens if I build a portal in the End dimension?", answer: "You cannot build Nether portals in the End dimension. Nether portals only function between the Overworld and the Nether. To leave the End, you must defeat the Ender Dragon and jump into the center exit portal." },
    { question: "Why are my two Overworld portals linking to the same Nether portal?", answer: "This happens when two Overworld portals are built too close together (within 1024 blocks of each other). When dividing by 8, their target Nether coordinates are so close that the game's 128-block search radius finds the same Nether portal for both." },
    { question: "Can I link a portal on the Nether roof?", answer: "Yes (in Java Edition). Many players break through the bedrock ceiling of the Nether to build entirely safe, flat ice-boat highways. Portals built on the Nether roof will link perfectly to the Overworld as long as the X and Z math is correct." },
    { question: "Does this calculator work for both Java and Bedrock editions?", answer: "Yes. The fundamental 8:1 dimensional mathematics and the X, Y, Z coordinate grid system are identical across all versions of Minecraft, including PC Java, Xbox, PlayStation, Switch, and mobile Bedrock." },
    { question: "What is the maximum distance a portal will search to link?", answer: "When searching for an active portal in the destination dimension, the game scans a 128-block radius horizontally (X and Z) from the mathematically calculated target coordinate, and searches the entire Y height (0 to 256/320) vertically." },
    { question: "Why did I suffocate when entering my portal?", answer: "If someone blocks your portal with solid blocks (like Obsidian) on the other side, the game might still link you to it, causing you to spawn inside solid blocks and take suffocation damage. Always protect your portals on multiplayer servers." },
    { question: "Can I make my Nether portal any size?", answer: "A standard Nether portal requires a minimum frame of 4x5 obsidian blocks (leaving a 2x3 hollow center). The maximum size allowed by the game is a massive 23x23 frame. The game links based on the bottom-center block of the portal." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 15 complete');
