import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, (_, g1, g2, g3) => g1 + data.description + g3);
  
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, (_, g1, g2, g3) => g1 + data.formulaExplanation + g3);
  
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, (_, g1, g2, g3) => g1 + data.exampleCalculation + g3);
  
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, (_, g1, g2, g3) => g1 + data.philippinesContext + g3);
  
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, (_, g1, g2) => g1 + '\n' + faqStr + ',\n    ' + g2);
  console.log(`Upgraded: ${slug}`);
}

upgrade("aquarium-gallon-calculator", {
  description: "Calculate the exact volume of your aquarium in gallons and liters based on its physical dimensions. For aquascapers, fish keepers, and marine hobbyists, guessing the volume of a tank is a recipe for disaster. The total volume of water directly dictates the fundamental life support systems of your aquarium: the size of the filtration system required, the wattage of the heater needed to maintain tropical temperatures, and the exact dosage for water conditioners, fertilizers, or fish medications. Furthermore, the volume strictly determines the 'stocking density'—how many fish you can safely keep without overwhelming the tank's biological cycle. Overstocking leads to dangerous spikes in ammonia and nitrite, resulting in fish mortality. This calculator allows you to input the length, width, and height of standard rectangular tanks, as well as bow-front or cylindrical tanks, instantly providing the precise volume capacity. It takes the guesswork out of aquarium setup, ensuring a stable, healthy aquatic environment for your pets. Whether you are maintaining a delicate nano-reef or a massive freshwater predator tank, accurate volume measurement is your first line of defense.",
  formulaExplanation: "For a standard rectangular aquarium, the mathematical formula for volume is relatively straightforward: Volume = Length * Width * Height. If you measure these dimensions in inches, the result will be in cubic inches. To convert cubic inches to US Gallons, you divide the total by 231 (since there are exactly 231 cubic inches in one US liquid gallon). The formula becomes: Gallons = (L * W * H in inches) / 231. To convert US Gallons to Liters (the standard metric unit used in most dosing instructions), you multiply the gallon value by 3.78541. For a cylindrical tank, the formula relies on the area of a circle: Volume = π * (Radius)^2 * Height. Again, if measured in inches, divide the result by 231 to find the gallon capacity. It is important to note that this calculates the GROSS volume. The ACTUAL water volume will be roughly 10% to 15% less once you add substrate (gravel/sand), large rocks, driftwood, and leave a gap at the top so the water doesn't overflow. This buffer prevents accidental overdosing of strong chemical treatments.",
  exampleCalculation: "Example 1 (Standard Rectangular Tank): You are setting up a popular '20-gallon long' tank. You measure the outside dimensions as 30 inches long, 12 inches wide, and 12 inches high. Volume = 30 * 12 * 12 = 4,320 cubic inches. Divide by 231 = 18.7 US Gallons. In metric, 18.7 * 3.785 = 70.8 Liters. Note that the actual volume is slightly less than the marketed '20 gallons' due to glass thickness. Example 2 (Nano Cube Tank): You buy a small desk aquarium measuring 10 inches on all sides (10 x 10 x 10). Volume = 1,000 cubic inches. Divide by 231 = 4.3 US Gallons (16.3 Liters). This is a crucial metric, as a 4.3-gallon tank is only suitable for a single Betta fish and perhaps some shrimp; adding multiple schooling fish would cause a toxic ammonia spike. The calculator performs these geometric conversions instantly, allowing you to confidently plan your bioload and equipment purchases without relying on the vague estimates printed on the retail packaging.",
  philippinesContext: "The aquarium hobby is massive in the Philippines, driven by the country's rich tropical marine biodiversity and the availability of cheap, locally bred ornamental fish in markets like Cartimar in Pasay City or Bio-Research branches. 'Monster fish keeping' (keeping large Arowanas or Flowerhorns) and high-tech planted aquascaping are particularly popular. In the Philippines, local glass makers in neighborhoods usually build custom tanks measured in inches (e.g., a '75-gallon' tank is typically built to 48x18x20 inches). However, all imported fish medications, water conditioners (like Seachem Prime), and liquid fertilizers are dosed strictly in milliliters per Liter or US Gallon. This creates a critical unit conversion problem for local hobbyists. A miscalculation when dosing copper-based medicine for 'Ich' (White Spot Disease) or liquid carbon for plants will instantly kill the entire tank. This calculator acts as a necessary bridge between local tank manufacturing dimensions and international chemical dosing standards, preventing costly and heartbreaking mistakes for Filipino aquarists.",
  faqs: [
    { question: "How do I calculate the gallons of my fish tank?", answer: "Measure the length, width, and height of your tank in inches. Multiply these three numbers together to get the cubic inches. Then, divide that total number by 231. The result is the total capacity of your tank in US Gallons." },
    { question: "What is the difference between US Gallons and UK (Imperial) Gallons?", answer: "A US liquid gallon is equivalent to 3.785 liters. A UK (Imperial) gallon is larger, equivalent to 4.546 liters. Most aquarium equipment, heaters, and medications use the US Gallon standard, which is the default for this calculator." },
    { question: "Is the calculated volume the exact amount of water in my tank?", answer: "No. The calculator provides the Gross Volume (the total capacity of the empty glass box). The Net Water Volume will be 10% to 15% less because you have to account for the space taken up by gravel, rocks, decorations, and the empty space at the top of the tank." },
    { question: "How many fish can I put in my tank?", answer: "A very old, outdated rule of thumb is 'One inch of fish per gallon of water'. However, this is deeply flawed. Stocking depends heavily on the filtration capacity, the 'bioload' (waste produced) of specific fish species, and their swimming space requirements. Always research the specific needs of the fish you want." },
    { question: "Why do I need to know my exact tank volume?", answer: "You must know the exact volume to accurately dose water conditioners (to remove chlorine from tap water), administer fish medications, dose liquid plant fertilizers, and choose appropriately sized equipment like filters and heaters. Guessing leads to overdosing and tank crashes." },
    { question: "What size filter do I need for my tank?", answer: "A general rule is that your filter should be able to turn over (pump) the entire volume of your tank at least 4 to 5 times per hour. If you have a 20-gallon tank, you need a filter rated for a flow rate of at least 80 to 100 Gallons Per Hour (GPH)." },
    { question: "What size heater do I need?", answer: "The standard recommendation is 3 to 5 Watts of heating power per gallon of water. For a 10-gallon tank, a 50-watt heater is sufficient. If your room gets exceptionally cold (e.g., heavily air-conditioned), you may need closer to 5 Watts per gallon." },
    { question: "Can I use this for bow-front or corner tanks?", answer: "Standard Length x Width x Height calculations only work for standard rectangular tanks. Bow-front (curved front glass) or corner pentagon tanks require much more complex geometric formulas, typically involving calculating the area of a circle segment for the curved portion." },
    { question: "How much gravel do I need for my tank?", answer: "A general estimate is 1 to 1.5 pounds of gravel per gallon of water to achieve a 1-inch to 1.5-inch substrate bed. If you are keeping live plants that require deep rooting, you may need 2 pounds per gallon." },
    { question: "Why do my fish keep dying in a small bowl?", answer: "Small bowls (under 3 gallons) have a tiny water volume that cannot dilute fish waste (ammonia). They also lack proper filtration and aeration. Ammonia builds up rapidly, effectively poisoning the fish. Almost all fish, including Bettas, require a filtered tank of at least 5 gallons to thrive." },
    { question: "Do I measure the inside or outside of the glass?", answer: "For the most precise mathematical volume, you should measure the inside dimensions to exclude the thickness of the glass (which can be 1/2 inch thick on large tanks). However, measuring the outside dimensions provides a close enough estimate for general hobbyist needs." },
    { question: "How heavy will my aquarium be when full?", answer: "Water is incredibly heavy. One US gallon of water weighs approximately 8.34 pounds (3.78 kg). A 50-gallon tank will hold over 400 pounds of water, plus the weight of the glass and gravel. You must ensure you have a specialized, heavy-duty aquarium stand to support it." }
  ]
});

upgrade("bnb-to-php-calculator", {
  description: "Convert Binance Coin (BNB) to Philippine Pesos (PHP) instantly using real-time cryptocurrency exchange rates. BNB is the native utility token of the Binance ecosystem, the largest cryptocurrency exchange in the world by trading volume. It is used to pay for trading fees on the exchange, participate in exclusive token sales (Binance Launchpad), and power the massive Binance Smart Chain (BSC) decentralized finance (DeFi) network. For Filipino crypto traders, investors, and Axie Infinity players who frequently bridge assets through the BSC network, tracking the exact fiat value of BNB is a daily necessity. The cryptocurrency market is notoriously volatile, with prices fluctuating wildly by the minute based on global trading sentiment. This calculator fetches live API data to provide the most accurate conversion possible. Whether you are cashing out your trading profits via Peer-to-Peer (P2P) platforms, calculating the gas fees required for a smart contract transaction, or evaluating your total crypto portfolio in local currency, this tool ensures you never lose money to outdated conversion rates or hidden spread margins. Accurate conversions prevent costly errors when setting limit orders or calculating your overall return on investment across different blockchain networks.",
  formulaExplanation: "The conversion calculation is simple arithmetic: Value in PHP = Amount of BNB * Current Exchange Rate (PHP per 1 BNB). The complexity lies entirely in the real-time nature of the 'Current Exchange Rate'. Unlike traditional fiat currencies (like USD to PHP) which move by fractions of a cent over a day, crypto exchange rates are highly volatile and operate 24/7. To provide an accurate conversion, this calculator interfaces with live cryptocurrency price APIs (like CoinGecko or Binance's own public API) to pull the most recent spot price. It is important to understand that the spot price is the mid-market rate. When you actually execute a trade or sell your BNB on a P2P market (like Binance P2P or GCash Crypto), the actual rate you receive will be slightly lower due to the 'spread' (the difference between the buy and sell price) and any platform transaction fees. This calculator provides the raw, unadulterated market value as a baseline for your trading decisions, helping you identify if a local P2P merchant is offering a fair exchange rate.",
  exampleCalculation: "Example 1 (Portfolio Valuation): You hold 2.5 BNB in your Trust Wallet. The current live market price of BNB is $300 USD. The USD to PHP exchange rate is 56.00 PHP. First, the BNB is converted to USD: 2.5 * 300 = $750. Then, converted to PHP: 750 * 56 = PHP 42,000. Your holdings are worth 42,000 Pesos. Example 2 (Calculating Gas Fees): You want to execute a smart contract on the Binance Smart Chain (e.g., swapping a token on PancakeSwap). The network charges a gas fee of 0.003 BNB. At the same market rate ($300 USD/BNB and 56 PHP/USD), the PHP value of 1 BNB is PHP 16,800. The transaction fee in fiat is: 0.003 * 16,800 = PHP 50.40. Knowing this exact fiat cost prevents you from overpaying for network transactions during times of high network congestion. The calculator processes these multi-currency conversions seamlessly, allowing you to instantly assess the profitability of your trades.",
  philippinesContext: "The Philippines is one of the fastest-growing cryptocurrency markets globally, heavily driven by the boom of Play-to-Earn (P2E) games like Axie Infinity, widespread remittance use cases, and the integration of crypto trading into massive local e-wallets like GCash and Maya. Binance, despite facing regulatory scrutiny from the Philippine Securities and Exchange Commission (SEC), remains the primary trading platform for advanced Filipino crypto users due to its deep liquidity and low fees. A common workflow for Filipinos is converting their earnings (like SLP or USDT) into BNB on the Binance Smart Chain, sending it to a local exchange or P2P merchant, and converting it to PHP to withdraw to their local bank accounts (UnionBank, BDO) or e-wallets. Furthermore, because BSC boasts significantly lower 'gas fees' compared to the Ethereum network, it is the preferred blockchain for Filipino retail investors exploring decentralized finance (DeFi) or buying low-cap 'meme coins'. Accurate, real-time BNB to PHP conversion is therefore not just a luxury, but a required tool for everyday digital financial survival and tax reporting compliance.",
  faqs: [
    { question: "What is Binance Coin (BNB)?", answer: "BNB is the native cryptocurrency of the Binance exchange and the Binance Smart Chain (BSC). It was initially created as a utility token to pay for discounted trading fees on Binance, but its use case has expanded massively to include paying network gas fees, booking travel, and participating in DeFi protocols." },
    { question: "Is the conversion rate on this calculator real-time?", answer: "Yes. Our calculator pulls live, real-time price data from major cryptocurrency APIs to ensure the PHP value reflects current global market conditions. However, always refresh the page right before making a major financial decision as crypto prices change by the second." },
    { question: "Why is the PHP price different when I sell on Binance P2P?", answer: "This calculator shows the global 'spot' market price. When you sell on Binance P2P (Peer-to-Peer) to get PHP directly into your GCash or bank account, merchants set their own prices. They usually buy slightly below the spot price to make a profit (the spread)." },
    { question: "How do I cash out BNB to PHP in the Philippines?", answer: "The most common methods are: 1) Using Binance P2P to sell BNB directly to a local buyer who transfers PHP to your bank or GCash. 2) Transferring the BNB to a BSP-licensed local exchange (like Coins.ph or PDAX), selling it for PHP there, and withdrawing." },
    { question: "What are 'gas fees' and why are they paid in BNB?", answer: "Gas fees are essentially the transaction costs required to use a blockchain network. If you are sending tokens or interacting with smart contracts on the Binance Smart Chain (BSC), the network validators must be paid in BNB to process your transaction." },
    { question: "Is it legal to trade BNB in the Philippines?", answer: "Yes, owning and trading cryptocurrencies is generally legal in the Philippines. The Bangko Sentral ng Pilipinas (BSP) has issued guidelines regulating Virtual Asset Service Providers (VASPs). However, users should be aware of ongoing SEC advisories regarding unregistered foreign exchanges operating locally." },
    { question: "Why does the BNB price fluctuate so much?", answer: "Cryptocurrency markets are highly volatile. Prices are driven purely by global supply and demand, macroeconomic factors, regulatory news, and overall sentiment in the crypto industry. Unlike fiat currency, crypto is not stabilized by a central bank." },
    { question: "Can I buy a fraction of a BNB?", answer: "Yes. Cryptocurrencies are highly divisible. You do not need to buy a whole BNB. You can buy 0.1 BNB, 0.05 BNB, or even smaller fractions, making it accessible to investors with smaller budgets." },
    { question: "What is the Binance Smart Chain (BSC)?", answer: "BSC is a blockchain network built by Binance to run smart contract-based applications. It is widely popular because it offers much faster transaction speeds and significantly lower gas fees compared to the Ethereum network. BNB is the fuel that runs the BSC." },
    { question: "Are my crypto gains subject to tax in the Philippines?", answer: "According to the Bureau of Internal Revenue (BIR), any income derived from cryptocurrency trading or investments is subject to regular income tax. It is the responsibility of the individual taxpayer to declare these capital gains in their annual Income Tax Return (ITR)." },
    { question: "What is token burning, and how does it affect BNB?", answer: "Binance conducts quarterly 'coin burns' where they permanently destroy a portion of the BNB supply based on the exchange's trading volume. This reduces the total supply over time, which theoretically increases the scarcity and value of the remaining BNB tokens." },
    { question: "Can I store my BNB on GCash or Maya?", answer: "Yes, both GCash (via GCrypto) and Maya offer in-app cryptocurrency trading features where you can buy, sell, and hold BNB directly using your peso balance. However, you generally cannot transfer that BNB out to an external Web3 wallet like MetaMask." }
  ]
});

upgrade("excel-formula-age-calculator", {
  description: "Generate the exact Excel formulas required to automatically calculate a person's age from their birthdate to today's date. Mastering date manipulation in Microsoft Excel or Google Sheets is a critical skill for HR professionals, data analysts, database managers, and educators. When managing a database of thousands of employees, students, or patients, manually calculating ages based on birth dates is impossible and prone to catastrophic errors. You need a formula that dynamically updates the age every single time the spreadsheet is opened. This tool provides the precise syntax for the DATEDIF function, the INT/YEARFRAC method, and complex concatenated formulas that break down age into exact Years, Months, and Days. By simply inputting the cell reference where your birth dates are stored (e.g., A2), the calculator outputs the exact formula string you can copy and paste directly into your spreadsheet. It eliminates syntax errors, misplaced commas, and formatting issues, transforming you into an Excel power user instantly and ensuring your demographic datasets are always perfectly up-to-date. Whether you are validating eligibility criteria or conducting demographic research, this tool ensures absolute accuracy.",
  formulaExplanation: "Calculating age in Excel requires dynamic functions that compare a static date of birth against the current, ever-changing date. The most reliable method uses the undocumented DATEDIF function. The formula =DATEDIF(start_date, end_date, 'unit') calculates the difference between two dates. To calculate age in full years, the syntax is: =DATEDIF(A2, TODAY(), 'Y'). 'A2' is the cell with the birthdate, TODAY() is a volatile function that always returns the current system date, and 'Y' tells Excel to return only complete years passed. For a more granular age, such as '25 Years, 3 Months', you must combine multiple DATEDIF functions using ampersands (&) for concatenation. The formula becomes: =DATEDIF(A2, TODAY(), 'Y') & ' Years, ' & DATEDIF(A2, TODAY(), 'YM') & ' Months'. The 'YM' unit calculates the remaining months after subtracting the full years. Another common method is =INT(YEARFRAC(A2, TODAY())), which calculates the fractional years between two dates and then uses INT to drop the decimal, leaving only the whole age. Using proper absolute and relative cell references ensures the formula works perfectly when dragged down thousands of rows.",
  exampleCalculation: "Example 1 (Basic Years): Cell A2 contains the date '05/15/1990'. Today is '10/20/2023'. If you paste =DATEDIF(A2, TODAY(), 'Y') into cell B2, Excel calculates the difference and returns '33'. When you open the file on '05/16/2024', the number will automatically change to '34'. Example 2 (Years and Months): Using the same dates, if you paste =DATEDIF(A2, TODAY(), 'Y') & ' Yrs, ' & DATEDIF(A2, TODAY(), 'YM') & ' Mos' into B2, Excel will output '33 Yrs, 5 Mos'. Example 3 (Legal Verification): You need to flag if an applicant is a minor. You can use the age formula inside an IF statement: =IF(DATEDIF(A2, TODAY(), 'Y') < 18, 'Minor', 'Adult'). The calculator generates these exact syntax strings tailored to your specific cell references, preventing the frustrating '#VALUE!' or '#NUM!' errors common in Excel date math, allowing you to seamlessly integrate age validation into larger conditional formatting or pivot table workflows.",
  philippinesContext: "In the Philippine corporate environment and government agencies, spreadsheet proficiency is often the backbone of administrative operations. Human Resources (HR) departments in the booming BPO sector heavily rely on Excel to manage massive employee databases, tracking metrics like tenure, age demographics, and retirement eligibility. Furthermore, government agencies like the SSS, PhilHealth, and Pag-IBIG have strict age-based brackets for contributions and benefits. For instance, computing the exact age is necessary to determine if an employee is eligible for the mandated Senior Citizen discount or specific tax exemptions under the BIR. In public schools under DepEd, teachers manage large registries of students and must constantly verify ages for grade-level eligibility and sports divisions (like the Palarong Pambansa age cut-offs). Providing Filipino administrative professionals and educators with the exact, copy-paste formulas for these tasks drastically reduces their administrative burden, allowing them to focus on substantive work rather than battling Excel syntax errors. It empowers local teams to operate with the same data efficiency as global corporations.",
  faqs: [
    { question: "What is the best Excel formula to calculate age?", answer: "The most reliable and standard formula is =DATEDIF(A2, TODAY(), 'Y'), assuming the birthdate is in cell A2. This function accurately calculates the number of complete years that have passed between the birthdate and the current date." },
    { question: "Why is the DATEDIF function not in the Excel menu?", answer: "DATEDIF is considered an 'undocumented' function in modern versions of Excel. It was originally included for compatibility with Lotus 1-2-3 (an ancient spreadsheet program). Excel won't auto-suggest it when you type, but the formula still works perfectly." },
    { question: "How do I get the age in exact Years, Months, and Days?", answer: "You have to combine three separate DATEDIF formulas using the & symbol. The syntax is: =DATEDIF(A2, TODAY(), 'Y') & ' Years, ' & DATEDIF(A2, TODAY(), 'YM') & ' Months, ' & DATEDIF(A2, TODAY(), 'MD') & ' Days'." },
    { question: "What does the TODAY() function do?", answer: "The TODAY() function is a 'volatile' function that reads your computer's system clock. Every time you open or recalculate the Excel file, TODAY() updates to the current date. This ensures your age calculations are never outdated." },
    { question: "Why am I getting a '#NUM!' error?", answer: "A '#NUM!' error in DATEDIF usually means the start date (birthdate) is greater than the end date (today). Check your birthdate column to ensure there are no futuristic dates or typos (e.g., typing 2090 instead of 1990)." },
    { question: "Why am I getting a '#VALUE!' error?", answer: "A '#VALUE!' error means Excel does not recognize the data in your birthdate cell as a valid date. It might be formatted as text. You need to ensure your birthdate column is formatted properly as Date (e.g., MM/DD/YYYY)." },
    { question: "Does this formula work in Google Sheets?", answer: "Yes. The DATEDIF, TODAY, and YEARFRAC functions operate exactly the same way in Google Sheets as they do in Microsoft Excel. The generated formulas from this calculator can be pasted into either program." },
    { question: "How do I calculate age on a specific past date, not today?", answer: "Instead of using TODAY(), replace it with a cell reference containing your specific target date. For example, if A2 is the birthdate and B2 is the date of an event, use: =DATEDIF(A2, B2, 'Y')." },
    { question: "Can I just subtract the birth year from the current year?", answer: "No. Using =YEAR(TODAY()) - YEAR(A2) is inaccurate. It will add a year on January 1st, regardless of whether the person's actual birthday has passed yet this year. DATEDIF accounts for the exact month and day." },
    { question: "How do I calculate age based on a specific format (e.g., DD/MM/YYYY vs MM/DD/YYYY)?", answer: "The formula itself does not change. Excel reads the underlying serial number of the date, regardless of how you have the cell formatted visually. As long as Excel recognizes it as a date, DATEDIF will work." },
    { question: "What is the YEARFRAC method?", answer: "Another way to calculate age is =INT(YEARFRAC(A2, TODAY())). YEARFRAC calculates the exact fractional number of years between two dates (e.g., 25.6 years). The INT function then rounds it down to the nearest whole number (25), effectively giving the completed age." },
    { question: "How can I apply this formula to 1,000 rows at once?", answer: "Paste the formula into the first row of your 'Age' column (e.g., B2). Click on cell B2, find the small green square in the bottom-right corner of the cell boundary (the fill handle), and double-click it. Excel will instantly copy the formula down to all 1,000 rows." }
  ]
});

upgrade("dog-pregnancy-calculator", {
  description: "Accurately estimate your dog's whelping date (due date) using this specialized Canine Pregnancy Calculator. For responsible dog breeders and loving pet owners, knowing exactly when a pregnant dog is expected to give birth is paramount for ensuring the health and safety of both the mother (dam) and her puppies. Unlike humans, dogs have a very short gestation period—averaging just 63 days. This small window means that preparation must begin almost immediately after a successful mating. This calculator takes the exact date of the first successful mating (or ovulation, if known through progesterone testing) and instantly generates the projected whelping window. This allows owners to properly schedule veterinary ultrasounds, transition the mother to high-calorie puppy food, build a safe and warm whelping box, and prepare emergency supplies in case of a difficult delivery (dystocia). By providing a clear timeline, this tool reduces anxiety and ensures you are fully prepared to assist your dog during the critical final days of her pregnancy. Proper planning is the difference between a smooth delivery and an emergency trip to the veterinary hospital.",
  formulaExplanation: "The calculation for canine gestation is relatively straightforward but is subject to natural biological variation. The average gestation period for dogs, regardless of breed size, is 63 days from the date of ovulation. However, because sperm can survive inside the female's reproductive tract for several days, and ovulation timing can be tricky to pinpoint without blood tests, the actual whelping date can range anywhere from 58 to 68 days from the date of the first mating. This calculator uses the standard 63-day rule. The formula is simply: Mating Date + 63 Days = Estimated Whelping Date. The calculator then typically provides a 'safe window' of +/- 2 to 3 days around that target date. For breeders who utilize progesterone blood testing to identify the exact day of ovulation or the Luteinizing Hormone (LH) surge, the 63-day calculation becomes highly precise, often accurate to within 24 hours. Tracking this timeline closely allows you to monitor for signs of premature labor or dangerous delays that require veterinary intervention.",
  exampleCalculation: "Example 1 (Standard Mating): Your Golden Retriever was successfully mated on January 1st. Using the standard 63-day gestation rule, the calculator adds 63 days to January 1st. The estimated whelping date is March 5th. You should begin checking her temperature twice daily starting around March 1st. Example 2 (Progesterone Tested): A breeder does blood testing and determines ovulation occurred on May 10th. The breeder inputs May 10th into the calculator. The projected due date is precisely July 12th. Example 3 (Late Window): If a dog was mated over three consecutive days (e.g., October 1st, 2nd, and 3rd), you input the first date (Oct 1). The 63-day mark is December 3rd. However, if conception actually occurred from the 3rd mating, she might not whelp until December 5th. The calculator provides the timeline needed to manage these variations safely, ensuring you are present and prepared with fresh towels and heating pads when labor finally initiates.",
  philippinesContext: "The dog breeding industry in the Philippines is thriving, ranging from large, registered kennels under the Philippine Canine Club, Inc. (PCCI) to casual 'backyard breeders' of popular breeds like Shih Tzus, Pomeranians, and American Bullies. While PCCI-registered breeders often utilize advanced veterinary services like progesterone testing and transabdominal ultrasounds (available in major vet clinics in Metro Manila and Cebu), casual owners usually rely on counting days from the physical mating. The tropical climate of the Philippines requires extra preparation for whelping; the whelping box must be kept warm but well-ventilated to prevent heatstroke in the mother, while still protecting the puppies from drafts. Furthermore, access to 24-hour emergency veterinary clinics is limited outside major urban centers. Therefore, knowing the exact whelping window is critical for provincial owners, allowing them to arrange transportation or alert their local veterinarian in advance should the mother require an emergency Cesarean section (common in brachycephalic breeds like Pugs and French Bulldogs). Early coordination is vital for survival.",
  faqs: [
    { question: "How long is a dog pregnant?", answer: "The normal gestation period for a dog is approximately 63 days from conception (ovulation). However, because determining the exact day of conception can be difficult without blood tests, a normal pregnancy can appear to last anywhere from 58 to 68 days from the time of mating." },
    { question: "How accurate is the 63-day rule?", answer: "It is highly accurate if counted from the exact day of ovulation. If you are counting from the day of mating, it is slightly less precise, as sperm can live inside the female for up to 5 days before fertilizing the eggs. Always consider the due date as a window of +/- 3 days." },
    { question: "What are the early signs that my dog is pregnant?", answer: "In the first few weeks, there are very few physical signs. Around week 3 to 4, she may experience 'morning sickness' (loss of appetite or slight vomiting). Around week 5, her teats may become enlarged and pinker, and she may start gaining weight around the abdomen." },
    { question: "When can a vet confirm the pregnancy?", answer: "A veterinarian can confirm pregnancy via a blood test (measuring the hormone relaxin) around 25 to 30 days after mating. An ultrasound can confirm fetal heartbeats around day 28 to 30. An X-ray to count the exact number of puppies is best done after day 45, when fetal skeletons calcify." },
    { question: "Do small breeds have shorter pregnancies than large breeds?", answer: "No. The 63-day gestation period is the biological standard across all domestic dog breeds, from Chihuahuas to Great Danes. However, large litters may trigger labor a day or two earlier than small litters." },
    { question: "What is a whelping box?", answer: "A whelping box is a safe, enclosed, draft-free area designed specifically for the mother to give birth and nurse her puppies. It should have low sides so the mother can step in and out, but high enough to keep the newborn puppies safely inside. It must be prepared at least a week before the due date." },
    { question: "How can I predict when labor is about to start?", answer: "The most reliable at-home method is taking the mother's rectal temperature twice a day starting a week before the due date. A normal dog's temperature is around 101°F to 102.5°F. About 12 to 24 hours before labor begins, her temperature will suddenly drop below 99°F." },
    { question: "What are the signs of labor?", answer: "Stage 1 labor involves restlessness, pacing, panting, shivering, and 'nesting' behavior (digging at blankets). She may refuse food. This stage can last 6 to 12 hours. Stage 2 is the actual delivery, characterized by strong abdominal contractions and the birth of the puppies." },
    { question: "When should I call the vet during labor?", answer: "Seek immediate emergency veterinary care if: 1) She has been experiencing strong, visible contractions for over 45 minutes without producing a puppy. 2) More than 2 hours pass between puppies without labor resuming. 3) You see a puppy stuck in the birth canal. 4) She appears extremely lethargic or is bleeding heavily." },
    { question: "Should I change my pregnant dog's diet?", answer: "Yes. For the first 4 weeks, feed her normal diet. From week 5 onward, the puppies grow rapidly. You should slowly transition her to a high-quality, calorie-dense puppy food and increase her portion size to support fetal growth and prepare her for lactation." },
    { question: "Can a dog give birth at 55 days?", answer: "Whelping before day 58 is considered premature. Puppies born at 55 days have underdeveloped lungs and a very low survival rate. If your dog goes into labor this early, contact a veterinarian immediately." },
    { question: "What is a 'tie' during dog mating?", answer: "A 'tie' occurs when the male and female remain physically locked together for 10 to 30 minutes after mating. This is a natural mechanism to ensure semen is deposited deeply. While a tie increases the chances of pregnancy, conception can still occur from a 'slip mating' without a tie." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 14 safe upgrade complete');
