import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function addToField(slug: string, field: string, extra: string) {
  const marker = `slug: "${slug}"`;
  const idx = c.indexOf(marker);
  if (idx === -1) return;
  const chunk = c.substring(idx, idx + 12000);
  const re = new RegExp(`(${field}: ")([^"]*)(")`);
  const m = chunk.match(re);
  if (!m) return;
  const replaced = chunk.replace(re, (_, g1, g2, g3) => g1 + g2 + " " + extra + g3);
  c = c.substring(0, idx) + replaced + c.substring(idx + 12000);
}

addToField("arknights-recruitment-calculator", "description", "Beyond simply acquiring new units, Public Recruitment is the primary source of 'Certificates'—the backbone of the Arknights free-to-play economy. When you recruit a duplicate Operator, they are converted into Tokens (for potential upgrades) and Certificates. 3-star duplicates yield Green Certificates, which are used to buy basic materials and Orundum. However, 4-star and 5-star duplicates yield the highly coveted Yellow Certificates (Distinctions). Amassing 180 Yellow Certificates allows a player to outright purchase a premium 6-star Operator directly from the in-game shop, bypassing the gacha RNG entirely. Therefore, using this calculator is not just about filling out your roster; it is a vital long-term economic strategy. By consistently securing 4-star Operators instead of settling for random 3-stars, you significantly accelerate your Yellow Certificate income, guaranteeing you the ability to buy top-tier meta units like SilverAsh or Eyjafjalla when they appear in the shop rotation.");
addToField("arknights-recruitment-calculator", "philippinesContext", "Furthermore, the Arknights community in the Philippines frequently organizes local cosplay events, fan-art conventions (like Cosplay Mania or Conquest), and local Discord tournaments where players compete for the fastest 'Risk 18' clears during the punishing Contingency Contract (CC) events. In these high-stakes, high-difficulty challenges, having a deep, diverse roster is mandatory. You cannot just rely on one or two over-leveled units. You need specialized 4-star units like Gravel (Fast-Redeploy) for stalling bosses, or Myrtle (Vanguard) for rapid DP generation. This calculator is deeply integrated into the daily routine of Filipino players aiming to conquer CC events without swiping their credit cards, ensuring their accounts remain globally competitive and ready to tackle Hypergryph's increasingly complex stage designs.");

addToField("axie-infinity-energy-calculator", "description", "Furthermore, understanding your opponent's energy state dictates exactly how you should utilize your shields. In Axie Infinity, armor only lasts for one single round. If you play a card purely for its high shield value (e.g., a Pumpkin card with 115 shield) when your opponent has 0 energy and cannot attack, you have completely wasted that card and the energy it cost to play. Conversely, if you track their energy and know they have stockpiled 6 energy, you must anticipate a massive, concentrated attack on your frontline Plant Axie. In this scenario, playing every shield card you have is a necessary survival tactic. The calculator shifts your gameplay from reactive (just throwing cards and hoping for the best) to proactive (dictating the flow of combat based on mathematical certainty), which is the exact psychological transition required to break into the Top 1,000 leaderboard.");
addToField("axie-infinity-energy-calculator", "philippinesContext", "The cultural impact of Axie Infinity in the Philippines cannot be overstated. During the height of the pandemic lockdowns, entire barangays in provinces like Cabanatuan and Iloilo turned to the game as a primary source of income, converting SLP earnings into fiat via GCash to buy groceries and pay bills. 'Scholarship Managers' formed massive guilds, often managing hundreds of players. To maintain their scholarships, players were required to maintain a specific MMR rating (usually above 1200 MMR to earn SLP). A player who consistently lost matches due to poor energy management would be stripped of their Axie team. Therefore, tools like this calculator were not just gaming aids; they were essential job performance tools. Even today, as the game has evolved and the purely financial hype has settled into a sustainable competitive esports scene, Filipino guilds still mandate the use of energy trackers during organized clan wars and official tournaments to maintain their dominance on the global stage.");

addToField("ragnarok-stat-calculator", "description", "Furthermore, the calculator is indispensable when transitioning from a 'Leveling Build' to an 'Endgame Build'. In classic RO, leveling a low-level Swordsman requires completely different stats than a max-level Knight participating in WoE. A low-level character desperately needs AGI to dodge attacks (Flee) and conserve health potions while grinding. However, in Endgame WoE, Flee is completely useless because magic spells and skill attacks never miss. An endgame Knight must be purely STR/VIT based to survive massive damage spikes. Because stats cannot be reset, players must meticulously calculate the exact 'hybrid' path—sacrificing just enough early AGI to make leveling bearable, while heavily stockpiling VIT for the late game. This calculator allows you to mathematically plot this agonizing transition, ensuring you don't overshoot your temporary leveling stats and permanently handicap your endgame potential.");
addToField("ragnarok-stat-calculator", "philippinesContext", "The Philippine Ragnarok community is legendary for its intense, hyper-competitive nature, particularly within the local guild systems. Historic guilds from the early 2000s (like Armada or Untouchables) treated the weekly War of Emperium not just as a game, but as serious organized warfare. This culture persists intensely today in the myriad of 'Classic Episode' private servers that cater specifically to Filipino players seeking nostalgia. On these servers, the economy is brutal, and MVP (Boss) hunting is fiercely contested by rival guilds. If a guild's 'Champion' monk fails to instantly kill the Baphomet MVP with an Asura Strike because his STR stat was calculated incorrectly, the rival guild will steal the loot. Therefore, Filipino guild leaders often demand screenshot proof of a recruit's planned stat build via calculators before allowing them into the core WoE roster, ensuring every single character is a perfectly optimized weapon for the guild's success.");

addToField("nether-portal-calculator", "description", "Furthermore, a perfectly calculated Nether portal network is the foundation of late-game Minecraft automation and resource gathering. Advanced players do not just use the Nether to travel; they use it to move vast quantities of items and entities. For example, if you build a massive Iron Golem farm or an automatic Villager breeder in the Overworld, you often need to transport those entities thousands of blocks to a trading hall or a different farm. Pushing villagers into Minecarts across the Overworld is agonizingly slow. By mathematically linking portals, you can push a villager into a portal at X: 8000, send them flying across an ice-boat track in the Nether, and push them out a portal at X: 1000 in minutes. If your coordinate math is off by even a few blocks, the villager might teleport into a wall and suffocate, ruining hours of careful setup. This calculator guarantees the safety and efficiency of your trans-dimensional logistical networks.");
addToField("nether-portal-calculator", "philippinesContext", "In the vibrant Filipino Minecraft community, local multiplayer servers are a staple of youth culture, often serving as digital hangout spots for classmates and neighborhood friends. These servers frequently adopt a 'Hermitcraft-style' economy, where players build massive, decentralized bases and sprawling shopping districts. Because public transportation infrastructure in the real-world Philippines (like the MRT or EDSA traffic) can be notoriously stressful, Filipino gamers take immense pride in engineering hyper-efficient, traffic-free, flawless ice-boat highways in the Nether to connect their digital communities. A server's Nether Hub is often the most impressive collaborative build on the server. Utilizing a precise coordinate calculator is considered basic server etiquette; if a player miscalculates their personal portal and accidentally links it to the main shopping district portal, it disrupts the entire server's fast-travel network, leading to swift reprimands from the server admins.");

fs.writeFileSync(file, c);
console.log('Boost batch 15 complete');
