import * as fs from 'fs';
const file = './data/calculators.ts';
let c = fs.readFileSync(file, 'utf-8');

function upgrade(slug: string, data: {description: string, formulaExplanation: string, exampleCalculation: string, philippinesContext: string, faqs: {question:string,answer:string}[]}) {
  const descRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?description: ")([^"]*)(")`, 'm');
  c = c.replace(descRe, `$1${data.description}$3`);
  const feRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?formulaExplanation: ")([^"]*)(")`, 'm');
  c = c.replace(feRe, `$1${data.formulaExplanation}$3`);
  const ecRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?exampleCalculation: ")([^"]*)(")`, 'm');
  c = c.replace(ecRe, `$1${data.exampleCalculation}$3`);
  const pcRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?philippinesContext: ")([^"]*)(")`, 'm');
  c = c.replace(pcRe, `$1${data.philippinesContext}$3`);
  const faqStr = data.faqs.map(f => `      { question: "${f.question}", answer: "${f.answer}" }`).join(',\n');
  const faqRe = new RegExp(`(slug: "${slug}",[\\s\\S]*?faqs: \\[)[\\s\\S]*?(\\],\\s*relatedSlugs)`, 'm');
  c = c.replace(faqRe, `$1\n${faqStr},\n    $2`);
  console.log(`Upgraded: ${slug}`);
}

upgrade("bore-stroke-calculator", {
  description: "Calculate the total engine displacement and assess the oversquare/undersquare ratio of any internal combustion engine using the Bore and Stroke Calculator. Whether you are an automotive engineering student, a professional mechanic, or a motorcycle tuning enthusiast, understanding the physical dimensions of an engine's cylinder is fundamental to predicting its performance characteristics. The 'bore' is the diameter of the cylinder, while the 'stroke' is the distance the piston travels up and down inside it. This calculator instantly computes the total displacement in cubic centimeters (cc) or liters (L) based on these measurements and the number of cylinders. Beyond simple displacement, this tool calculates the Bore/Stroke ratio. An engine with a bore larger than its stroke (oversquare) is typically designed to rev high and produce peak horsepower, commonly found in sportbikes and race cars. Conversely, an engine with a stroke longer than its bore (undersquare) is designed for low-end torque and fuel efficiency, typical in diesel trucks and economy cars. This calculator demystifies engine design, allowing builders to optimize their setups before machining any metal.",
  formulaExplanation: "The formula for calculating engine displacement relies on the volume of a cylinder: Volume = π * (Radius)^2 * Stroke. Since the 'Bore' is the diameter, the Radius is (Bore / 2). The formula becomes: Displacement per Cylinder = π * (Bore / 2)^2 * Stroke. To find the Total Displacement, you multiply this by the number of cylinders. Because bore and stroke are often measured in millimeters (mm), the result will initially be in cubic millimeters. To convert this to the standard cubic centimeters (cc), you must divide the final result by 1,000. The calculator also computes the Bore-to-Stroke Ratio by simply dividing the Bore by the Stroke. A ratio > 1.0 is oversquare (short stroke, high revving). A ratio < 1.0 is undersquare (long stroke, high torque). A ratio of exactly 1.0 is considered a 'square' engine, offering a balance of torque and horsepower.",
  exampleCalculation: "Example 1 (Motorcycle Tuning): You are rebuilding a single-cylinder motorcycle engine. You measure a bore of 62 mm and a stroke of 48.8 mm. Radius = 31 mm. Volume = 3.14159 * (31)^2 * 48.8 = 147,333 cubic mm. Divide by 1000 = 147.3 cc. Ratio = 62 / 48.8 = 1.27 (highly oversquare). Example 2 (V8 Car Engine): A V8 engine (8 cylinders) has a bore of 101.6 mm (4.00 inches) and a stroke of 88.4 mm (3.48 inches). Radius = 50.8 mm. Volume per cylinder = 3.14159 * (50.8)^2 * 88.4 = 716,678 cubic mm (716.6 cc). Total Displacement = 716.6 cc * 8 cylinders = 5,733 cc (or 5.7 Liters). Ratio = 101.6 / 88.4 = 1.15 (oversquare). The calculator handles these multi-step geometric conversions instantly, ensuring precision when ordering aftermarket pistons or planning an engine boring project.",
  philippinesContext: "In the Philippines, motorcycle tuning and engine modification is a massive cultural phenomenon, particularly with ubiquitous underbone models like the Yamaha Sniper, Honda Click, and Suzuki Raider. Local mechanical shops frequently 'bore up' these engines to increase top speed and acceleration for everyday commuting or legal track racing. This process involves machining the cylinder block to fit a larger piston. However, mechanics must calculate the new displacement accurately because the Land Transportation Office (LTO) has strict regulations regarding major engine modifications; significant alterations may require securing an LTO clearance and a new Certificate of Registration to remain street-legal. Furthermore, engineering students at institutions like Don Bosco Technical College or Mapúa University rely on these exact calculations during their thermodynamics and internal combustion engine design courses. The calculator bridges the gap between theoretical classroom physics and hands-on, greasy-knuckle garage tuning.",
  faqs: [
    { question: "What is Engine Bore?", answer: "The 'bore' is the internal diameter of the engine's cylinder, usually measured in millimeters (mm) or inches. A larger bore allows for larger valves, which improves the engine's ability to 'breathe' (intake air and exhaust gases) at high RPMs." },
    { question: "What is Engine Stroke?", answer: "The 'stroke' is the total distance the piston travels from its lowest point (Bottom Dead Center) to its highest point (Top Dead Center) inside the cylinder. A longer stroke generally produces more torque but limits the maximum RPM of the engine." },
    { question: "What does 'CC' mean in engines?", answer: "CC stands for Cubic Centimeters. It is the metric measurement of an engine's total displacement volume. For example, a 150cc motorcycle engine can displace 150 cubic centimeters of an air-fuel mixture during one complete cycle of all its cylinders." },
    { question: "What is an Oversquare (Short Stroke) engine?", answer: "An oversquare engine has a bore diameter that is larger than its stroke length (Ratio > 1.0). These engines have shorter piston travel, allowing them to safely reach much higher RPMs, producing peak horsepower. Sportbikes and Formula 1 cars use highly oversquare engines." },
    { question: "What is an Undersquare (Long Stroke) engine?", answer: "An undersquare engine has a stroke length that is longer than its bore diameter (Ratio < 1.0). The longer lever arm on the crankshaft produces more turning force (torque) at lower RPMs. Diesel trucks, tractors, and economy cars use undersquare engines for better pulling power and fuel efficiency." },
    { question: "What is a 'Square' engine?", answer: "A square engine has a bore exactly equal to its stroke (Ratio = 1.0). These engines aim to strike a perfect compromise, offering a wide, usable powerband with adequate low-end torque and decent high-RPM horsepower capabilities." },
    { question: "Does increasing the bore always increase horsepower?", answer: "Increasing the bore increases total displacement, which generally increases the potential for more horsepower. However, to fully realize this gain, the engine must also receive corresponding upgrades to the carburetor/fuel injector, intake valves, and exhaust system to handle the increased air volume." },
    { question: "Why do mechanics 'bore up' motorcycle engines?", answer: "Mechanics machine the cylinder to widen the bore so a larger aftermarket piston can be installed. This directly increases the engine's CC, resulting in faster acceleration and a higher top speed, which is a popular modification in the Philippine underbone racing scene." },
    { question: "Is it illegal to bore up an engine in the Philippines?", answer: "It is not strictly illegal, but the Land Transportation Office (LTO) requires that any major modification that changes the engine's specifications (including significant displacement changes) be inspected, cleared by the Highway Patrol Group (HPG), and updated on the vehicle's Certificate of Registration." },
    { question: "How do I convert inches to millimeters for this calculator?", answer: "To convert inches to millimeters, multiply the inch value by 25.4. For example, a 4.00-inch bore is exactly 101.6 mm. American V8 engines are traditionally measured in inches, while Japanese and European engines use metric millimeters." },
    { question: "What is the difference between Displacement and Horsepower?", answer: "Displacement is a physical measurement of the engine's volume capacity (size). Horsepower is a measurement of the actual work the engine can perform over time. While larger displacement engines generally produce more horsepower, efficient modern small engines with turbochargers can produce more power than older, larger engines." },
    { question: "Why does my 150cc motorcycle registration say 149cc?", answer: "Manufacturers typically round up engine displacement for marketing purposes. Because of the mathematical formula involving Pi (3.14159), engine volumes rarely land on perfectly round numbers. A '150cc' scooter mathematically usually displaces around 149.3cc to 149.8cc." }
  ]
});

upgrade("engine-displacement-calculator", {
  description: "Calculate the exact engine displacement of your vehicle in cubic centimeters (cc) and Liters (L) using this precise mathematical tool. Engine displacement is the fundamental metric used globally to define the size, classification, and power potential of an internal combustion engine. It represents the total swept volume of all the pistons inside the cylinders during one complete cycle. Whether you are registering a vehicle, buying car insurance, or planning an engine modification (like a 'bore up' kit), knowing the exact displacement is critical. This calculator eliminates the complex geometry involved in computing cylinder volume. By simply entering the engine's bore (cylinder diameter), stroke (piston travel distance), and the total number of cylinders, users receive an instant, accurate measurement. It is an invaluable resource for automotive engineering students verifying their textbook computations, mechanics matching aftermarket parts, and car enthusiasts comparing the theoretical capabilities of different engine architectures (e.g., inline-4 versus V6) before committing to an expensive build or purchase.",
  formulaExplanation: "The formula to calculate total engine displacement is derived from the geometric formula for the volume of a cylinder. Volume = π * (Radius)^2 * Height. In engine terms, the 'Radius' is half of the Bore (Bore / 2), and the 'Height' is the Stroke. Therefore, the volume of a single cylinder is: π * (Bore / 2)^2 * Stroke. To find the Total Engine Displacement, you multiply this single-cylinder volume by the Total Number of Cylinders. Since engine measurements (bore and stroke) are predominantly given in millimeters (mm), this formula initially yields a result in cubic millimeters (mm³). To convert this vast number into the standard automotive measurement of cubic centimeters (cc), the result is divided by 1,000. To further convert cubic centimeters into Liters (L)—the standard for car engines—you divide the cc value by an additional 1,000. For instance, a 1,998 cc engine is marketed as a 2.0-Liter engine.",
  exampleCalculation: "Example 1 (Four-Cylinder Car Engine): You have a typical inline-4 engine. The specifications list a bore of 86 mm and a stroke of 86 mm (a 'square' engine). Radius = 43 mm. Volume of one cylinder = 3.14159 * (43)^2 * 86 = 499,557 cubic mm. Convert to cc: 499.5 cc per cylinder. Multiply by 4 cylinders = 1,998 cc. In Liters, this is 1.998 L, commonly badged as a 2.0L engine. Example 2 (Six-Cylinder Truck Engine): A V6 engine with a bore of 94 mm and a stroke of 90 mm. Radius = 47 mm. Volume of one cylinder = 3.14159 * (47)^2 * 90 = 624,561 cubic mm, or 624.5 cc. Total displacement for 6 cylinders = 624.5 * 6 = 3,747 cc. This would be marketed as a 3.7L or 3.8L engine. The calculator guarantees precision without rounding errors during the intermediate steps.",
  philippinesContext: "In the Philippines, engine displacement is not just a performance metric; it is a critical legal and financial classification. The Land Transportation Office (LTO) uses engine displacement to determine Motor Vehicle User's Charge (MVUC) or annual registration fees. Vehicles with larger displacements (e.g., SUVs with 2.5L to 3.0L engines) pay significantly higher registration fees than economy cars with 1.2L engines. Furthermore, under the Philippine Highway Patrol Group (HPG) rules, motorcycles must have a minimum engine displacement of 400cc to be legally allowed to enter and traverse the country's tollways (NLEX, SLEX, Skyway). Because manufacturers often round up (a 398cc bike might be marketed as 400cc), riders must ensure their actual displacement recorded on the Certificate of Registration strictly meets the 400cc threshold to avoid hefty fines or confiscation at toll gates. This calculator allows riders and mechanics to verify these exact numbers before making a purchase or undergoing LTO inspection.",
  faqs: [
    { question: "What is Engine Displacement?", answer: "Engine displacement is the total volume of air and fuel mixture that all the pistons in an engine can draw in (or 'sweep') during one complete cycle. It is the primary measurement of an engine's physical size." },
    { question: "Why is engine size measured in CC and Liters?", answer: "CC (Cubic Centimeters) is the standard metric measurement for small engines like motorcycles and lawnmowers. For larger car and truck engines, the numbers become too large to read easily, so they are converted into Liters (1 Liter = 1,000 CC)." },
    { question: "Does higher displacement mean a faster car?", answer: "Generally, a larger displacement engine can burn more fuel and air, generating more power and torque. However, modern smaller engines equipped with turbochargers or superchargers (forced induction) can easily outperform older, larger naturally aspirated engines." },
    { question: "Why is a 2.0L engine only 1,998cc?", answer: "Automakers round the displacement numbers for marketing simplicity. Because the calculation involves Pi (3.14159) and the physical limits of machining metal, exact numbers like 2,000.0 cc are virtually impossible to manufacture. A 1,998cc engine is mathematically closest to 2.0 Liters." },
    { question: "How do I find the bore and stroke of my engine?", answer: "The bore and stroke dimensions are typically listed in the vehicle's owner's manual under the 'Specifications' section. You can also easily find them by searching online for your specific engine code (e.g., Honda K20A, Toyota 2TR-FE)." },
    { question: "Can I increase my engine's displacement?", answer: "Yes, by 'boring' the cylinders wider to fit larger pistons, or by 'stroking' the engine (installing a crankshaft that pushes the pistons further up and down). These are major, expensive mechanical modifications usually reserved for racing." },
    { question: "What is the 400cc rule in the Philippines?", answer: "The Toll Regulatory Board (TRB) in the Philippines strictly prohibits motorcycles with an engine displacement of less than 400cc from entering limited-access expressways (like SLEX, NLEX, and Skyway) for safety reasons." },
    { question: "Does engine displacement affect my LTO registration fee?", answer: "Yes. The Land Transportation Office (LTO) calculates the annual Motor Vehicle User's Charge (MVUC) based primarily on the vehicle type and its engine displacement. Larger engines fall into higher tax brackets and pay significantly more." },
    { question: "Does displacement affect fuel consumption?", answer: "Usually, yes. Larger displacement engines generally require more fuel to run, resulting in lower kilometers per liter (km/L). However, driving habits, vehicle weight, and transmission gearing also heavily influence actual fuel economy." },
    { question: "What does it mean if an engine is an 'Inline 4' or 'V6'?", answer: "This refers to the layout and number of cylinders. An 'Inline 4' has 4 cylinders arranged in a straight line. A 'V6' has 6 cylinders arranged in two banks of 3, forming a 'V' shape. Both types require the total number of cylinders to be multiplied in the displacement formula." },
    { question: "Is this calculator accurate for rotary (Wankel) engines?", answer: "No. Rotary engines (like those found in the Mazda RX-7 or RX-8) do not have traditional pistons, bores, or strokes. They use spinning triangular rotors. Their displacement is calculated using a completely different geometric formula." },
    { question: "Why do some bikes have 155cc instead of 150cc?", answer: "Manufacturers sometimes increase the bore or stroke slightly by just a few millimeters to edge out competitors in the same market segment. A 155cc engine provides slightly more power than a standard 150cc while remaining in the same general tax/license category." }
  ]
});

upgrade("differential-equation-calculator", {
  description: "Solve complex First-Order Ordinary Differential Equations (ODEs) step-by-step using this advanced computational tool. Differential equations are the mathematical language of change, describing everything from population growth and radioactive decay to the cooling of a cup of coffee and the motion of a spring. For engineering, physics, and advanced mathematics students, solving ODEs manually involves identifying the type of equation (separable, linear, exact, Bernoulli) and applying lengthy integration techniques. A single integration error can ruin an hour of work. This calculator acts as a digital tutor and verification engine. By inputting your equation, it not only provides the final mathematical solution (the function that satisfies the equation) but serves as a critical check against manual computations. Whether you are a civil engineering student calculating beam deflection, an electrical engineer modeling an RLC circuit transient response, or a researcher modeling epidemiological curves, this tool provides the mathematical certainty required to move forward with complex theoretical designs and practical applications.",
  formulaExplanation: "A first-order Ordinary Differential Equation typically takes the form dy/dx = f(x,y). The goal is to find the unknown function y(x). The solver attempts various standard analytical methods to find an exact symbolic solution. First, it checks if it is 'Separable' (can be written as g(y)dy = h(x)dx), where it simply integrates both sides. If not, it checks if it is a 'First-Order Linear' equation of the form dy/dx + P(x)y = Q(x). For linear equations, the solver computes an Integrating Factor, I(x) = e^(∫P(x)dx), multiplies the entire equation by this factor, and then integrates. It also checks for 'Exact' equations where ∂M/∂y = ∂N/∂x, or applies substitutions for homogeneous equations. If an analytical solution cannot be found using these standard algebraic integration techniques, numerical approximation methods (like Euler's Method or Runge-Kutta) would be required, though this calculator prioritizes exact algebraic solutions.",
  exampleCalculation: "Example 1 (Separable Equation): dy/dx = 2x. This represents a curve whose slope is always twice its x-coordinate. We separate the variables: dy = 2x dx. We integrate both sides: ∫dy = ∫2x dx. The solution is y = x^2 + C, where C is the constant of integration. This represents a family of parabolas. Example 2 (First-Order Linear): dy/dx + y = e^x. Here, P(x) = 1 and Q(x) = e^x. The integrating factor is I(x) = e^(∫1 dx) = e^x. Multiplying the equation by e^x gives: e^x(dy/dx) + e^x * y = e^(2x). The left side is the derivative of (y * e^x). So, d/dx(y * e^x) = e^(2x). Integrating both sides: y * e^x = (1/2)e^(2x) + C. Finally, solve for y: y = (1/2)e^x + C*e^(-x). The calculator performs these complex integrations and algebraic manipulations automatically.",
  philippinesContext: "In the Philippine higher education system, Differential Equations (DE) is a notorious 'make-or-break' subject for all engineering and applied physics students. At premier institutions like UP Diliman, Mapúa University, DLSU, and various state universities, passing DE is a strict prerequisite for advancing to major subjects. The Professional Regulation Commission (PRC) Board Exams for Civil, Mechanical, and Electrical Engineering heavily feature problems that require setting up and solving differential equations to model physical phenomena. Because calculators with Computer Algebra Systems (CAS) capable of symbolic integration are strictly banned inside PRC examination rooms, students must master manual solving techniques. This online calculator is heavily utilized during the review phase. Engineering review centers across Manila encourage students to use such tools to instantly verify their manual homework, allowing them to rapidly identify mistakes in their integration steps and master the patterns required to pass the rigorous board exams.",
  faqs: [
    { question: "What is a Differential Equation?", answer: "A differential equation is a mathematical equation that relates one or more functions and their derivatives. In practical applications, the functions represent physical quantities, the derivatives represent their rates of change, and the equation defines the relationship between the two." },
    { question: "What does 'First-Order' mean?", answer: "The 'order' of a differential equation is the highest derivative it contains. A first-order equation only contains the first derivative (dy/dx or y'). A second-order equation would contain a second derivative (d²y/dx² or y''), which describes acceleration in physics." },
    { question: "What is the difference between an ODE and a PDE?", answer: "An Ordinary Differential Equation (ODE) contains a function of only ONE independent variable (usually 'x' or 't' for time). A Partial Differential Equation (PDE) contains multivariable functions and their partial derivatives, which are much more complex (e.g., modeling heat flow in 3D space)." },
    { question: "What does the 'C' mean in the answer?", answer: "The 'C' is the constant of integration. Because the derivative of any constant number is zero, integrating a function yields a 'family' of possible curves. 'C' represents this infinite set of possibilities. To find the exact value of C, you need an Initial Condition." },
    { question: "What is an Initial Value Problem (IVP)?", answer: "An IVP is a differential equation accompanied by a specific starting point, called an initial condition (e.g., y(0) = 5). This allows you to solve for the exact value of 'C', providing one unique, specific function as the answer rather than a general family of curves." },
    { question: "Why do we need to learn Differential Equations?", answer: "They are the foundation of modern engineering and physics. They are used to calculate the trajectory of rockets, design earthquake-resistant buildings, model the spread of infectious diseases, predict financial market movements, and design electrical circuits." },
    { question: "Can this calculator solve second-order equations?", answer: "This specific calculator module is optimized for solving First-Order ODEs. Second-order equations (like those describing harmonic oscillators or structural vibrations) require different analytical techniques like the Characteristic Equation method or Laplace Transforms." },
    { question: "What is a Separable Differential Equation?", answer: "It is the simplest type of ODE where you can algebraically move all the 'y' terms to one side of the equals sign with 'dy', and all the 'x' terms to the other side with 'dx'. Once separated, you simply integrate both sides independently." },
    { question: "What is an Integrating Factor?", answer: "An integrating factor is a specific mathematical multiplier (often involving the natural exponential function, 'e') used to solve linear ODEs. Multiplying the equation by this factor transforms the left side into an exact derivative, making it easy to integrate." },
    { question: "Are these calculators allowed in Philippine Board Exams?", answer: "No. The PRC strictly prohibits calculators with Computer Algebra Systems (CAS) that can perform symbolic algebra or calculus. You must solve DE problems manually during the board exam. This tool is meant for study, homework verification, and review." },
    { question: "What if the calculator cannot find an answer?", answer: "Not all differential equations have exact analytical (algebraic) solutions. In fact, many real-world ODEs are impossible to solve symbolically. In these cases, engineers rely on numerical methods (run via computer software) to approximate the answer." },
    { question: "Is this useful for computer science students?", answer: "Yes. Computer Science students studying machine learning, neural networks (gradient descent), and computer graphics/physics engines must understand how to model rates of change. DEs are fundamental to writing algorithms that simulate real-world physics." }
  ]
});

upgrade("k-map-calculator", {
  description: "Simplify complex Boolean algebra expressions instantly using this digital Karnaugh Map (K-Map) Calculator. A K-Map is a visual, grid-based method used to minimize Boolean logic functions without the tedious, error-prone application of Boolean theorems (like De Morgan's laws). For electronics engineering and computer science students, logic minimization is a foundational skill. Minimizing an expression means reducing the number of logic gates (AND, OR, NOT) required to build a digital circuit. Fewer gates mean cheaper manufacturing, lower power consumption, faster processing speeds, and smaller microchips. This calculator handles 2, 3, and 4-variable K-Maps. By simply inputting the minterms (the specific binary combinations where your desired output is '1') or the maxterms, the tool automatically groups the 1s into optimal rectangles and outputs the simplified Sum of Products (SOP) or Product of Sums (POS) expression. It acts as an essential verification tool for students designing multiplexers, adders, and state machines, ensuring their final circuit designs are as efficient and cost-effective as mathematically possible.",
  formulaExplanation: "The K-Map operates on the principle of Gray Code, where adjacent cells in the grid differ by only one variable (one bit). This spatial arrangement ensures that any adjacent cells containing a '1' represent a redundant variable that can be eliminated. The algorithm groups the 1s in rectangular blocks of size 2^n (i.e., 1, 2, 4, 8, or 16 cells). The larger the group, the more variables are eliminated. The K-Map essentially automates the Boolean theorem: AB + AB' = A(B + B') = A(1) = A. In a 4-variable map (A, B, C, D), the edges wrap around, meaning the top row is adjacent to the bottom row, and the left column is adjacent to the right column. The simplified expression is formed by taking the variables that remain constant within each grouped block. The final answer is the logical OR (Sum) of all these grouped terms, known as the Sum of Products (SOP). The calculator algorithm mathematically performs this grouping to find the absolute minimum expression.",
  exampleCalculation: "Example: You are designing a security system circuit with 3 sensors (Variables A, B, C). The alarm should trigger (output = 1) for minterms: m(0, 2, 4, 6). This means the output is 1 when the binary inputs are 000, 010, 100, and 110. Step 1: Place 1s in the corresponding cells of a 3-variable K-Map. Step 2: Look for groupings. You will see that m(0) and m(2) can group together, and m(4) and m(6) can group together. More efficiently, because the map wraps around, all four of these cells can be grouped into one large block of four. Step 3: Analyze the block. The variables A and B change values within this block, so they are eliminated. The only variable that remains constant across all four cells is C being 0 (which is C'). Therefore, the simplified Boolean expression is simply: Output = C'. A circuit that originally required multiple AND/OR gates is simplified to a single NOT gate connected to sensor C. The calculator performs this entire optimization instantly.",
  philippinesContext: "In Philippine technological institutes and engineering universities like Mapúa, DLSU, and TIP, Digital Logic Design is a core curriculum requirement for Electronics Engineering (ECE) and Computer Engineering (CpE) students. During laboratory classes, students use breadboards and physical TTL (Transistor-Transistor Logic) IC chips, like the 7400 series, to physically wire their K-Map designs. A failure to minimize a Boolean expression properly means a student might need to buy and wire five IC chips instead of just two, resulting in a messy, difficult-to-debug breadboard ('spaghetti wiring') that often fails grading due to loose connections. During the rigorous ECE Board Examinations, rapid K-Map solving is essential, as logic problems must be solved in minutes without the aid of software. This online calculator is heavily utilized by Filipino students during late-night study sessions and review periods to cross-check their manual K-Map groupings and ensure they haven't missed a larger, more optimal grouping.",
  faqs: [
    { question: "What is a Karnaugh Map (K-Map)?", answer: "A K-Map is a graphical method used to simplify Boolean algebra expressions. It organizes binary truth tables into a grid where adjacent cells differ by only one bit. By visually grouping 1s in this grid, you can easily identify and eliminate redundant logic variables." },
    { question: "Why is minimizing logic circuits important?", answer: "Minimizing a logic expression reduces the physical number of logic gates (AND, OR, NOT) needed to build a circuit. Fewer gates result in a circuit that is cheaper to manufacture, consumes less electricity, takes up less physical space, and operates faster." },
    { question: "What are Minterms?", answer: "A minterm is a specific combination of all input variables in a Boolean function that results in an output of '1'. In a truth table, every row that has a '1' as the output represents one minterm. They are usually expressed as a Sum of Products (SOP)." },
    { question: "What are Maxterms?", answer: "A maxterm is a specific combination of all input variables that results in an output of '0'. They are the opposite of minterms and are used to create Product of Sums (POS) expressions." },
    { question: "What is Gray Code and why does the K-Map use it?", answer: "Gray Code is a binary numeral system where two successive values differ in only one bit (e.g., 00, 01, 11, 10). The K-Map grid uses this numbering so that any adjacent cells represent terms that can be algebraically simplified." },
    { question: "What are the rules for grouping 1s in a K-Map?", answer: "1s must be grouped in rectangles. The number of 1s in a group must be a power of 2 (1, 2, 4, 8, 16). Groups can overlap. You must make the groups as large as possible to eliminate the most variables. Every '1' on the map must belong to at least one group." },
    { question: "Does the K-Map 'wrap around'?", answer: "Yes. In 3-variable and 4-variable maps, the left edge is considered adjacent to the right edge, and the top edge is adjacent to the bottom edge. This means you can group a '1' on the far left with a '1' on the far right." },
    { question: "What are 'Don't Care' conditions?", answer: "Don't Care conditions (usually marked as 'X') are specific input combinations that will never physically occur in your circuit, or where the output doesn't matter. You can treat an 'X' as either a 1 or a 0—whichever helps you create a larger group and a simpler equation." },
    { question: "Can a K-Map handle more than 4 variables?", answer: "While a 4-variable K-Map is a simple 4x4 2D grid, a 5-variable or 6-variable K-Map requires drawing multiple 4x4 grids and visualizing them in 3D layers. It becomes highly complex for humans to solve manually, which is why software algorithms (like Quine-McCluskey) are used for larger systems." },
    { question: "What is Sum of Products (SOP)?", answer: "SOP is a standard format for Boolean expressions where several AND terms (products) are joined by OR gates (sums). Example: AB + CD. It is the most common output derived from grouping the 1s on a K-Map." },
    { question: "What is Product of Sums (POS)?", answer: "POS is the inverse format where several OR terms (sums) are joined by AND gates (products). Example: (A+B)(C+D). It is derived by grouping the 0s on a K-Map instead of the 1s." },
    { question: "Are K-Maps still used in modern engineering?", answer: "Yes, as a teaching tool. While professional engineers designing computer CPUs with billions of transistors use specialized software (EDA tools) to optimize logic automatically, K-Maps remain the fundamental academic method to teach students the core concepts of logic minimization." }
  ]
});

fs.writeFileSync(file, c);
console.log('Batch 13 complete');
